// This file was generated by agent-compose 0.0.0-dev from `main.yml` (target `local`).
//
// It is a build artifact, not source: `agent-compose build` overwrites it,
// and `agent-compose build --check` fails when it has been edited. The spec
// is the single source of truth (PRD 5.12); to own this code instead, copy
// the whole directory out and stop regenerating it.
//
// What this artifact's deploy layer declares: the placements a worker may claim,
// the environment partition of `docs/distributed.md` §9.1, and the hub's own two
// keys (grammar §14.1, §14.2).
//
// The partition is emitted here rather than derived at either end because §9.1
// requires one answer under one artifact hash: the hub checks a join's `env_ok`
// against the claimed placements' lists, and the worker reads the list it is
// reporting against out of the very tree the hub served it.
//
// `hubEnvironment` is the hub's own side of that partition, stated as names.
// **It is not what `readEnvironment()` reads**: `./env.ts` carries the same
// variables with the spec sites that wrote each one, because a launch that is
// short a key should name where the key was asked for, and that is the list
// `./index.ts` checks at start. This one is the manifest form — names only, like
// a placement's — so a reader of the artifact, or of the tarball a worker
// unpacked, can see what the hub holds beside what each placement holds without
// reading two shapes. The two are one derivation filtered two ways
// (`References::for_process`), and a test pins them equal.
//
// Both are narrower than the composition's whole environment exactly when a
// placement takes something off the hub's — the least-privilege line PRD 5.10
// draws and §9.1 computes: the hub cannot leak what it never held.

/** One placement, and the environment a worker claiming it has to satisfy. */
export interface PlacementManifest {
  /** The name a worker claims at join (`docs/distributed.md` §3.1). */
  readonly name: string;
  /**
   * `members:`, in the order the deploy file writes them (grammar §14.1).
   *
   * For a **reader**, not for a caller: the scheduler queues work to a placement
   * by name and never consults this list (`docs/distributed.md` §2), and the
   * `environment` beside it is already the answer to what a worker must satisfy.
   * It is here because a worker holds no YAML — the artifact is the only thing
   * it is served — so "what did I just claim" is otherwise unanswerable on the
   * machine that claimed it.
   */
  readonly members: readonly string[];
  /**
   * The variables of every component that can execute in this placement's
   * process, sorted by name — `docs/distributed.md` §9.1's partition.
   *
   * Names only. A manifest carries no value and no site: what a join reports is
   * a subset of this list (§9.2), and a report scoped to anything wider would be
   * telling the hub about credentials that are none of its business.
   */
  readonly environment: readonly string[];
}

export const placements: readonly PlacementManifest[] = [];

export const hubEnvironment: readonly string[] = [
  "SHAPES_KEY",
  "SHAPES_URL",
  "SHAPE_CALLBACK_SECRET",
  "SHAPE_CALLBACK_TOKEN",
  "SHAPE_SECRET",
  "SHAPE_TOKEN",
  "WORKSPACE",
];

export const joinTokenEnv: string | undefined = undefined;

export const publicUrl: string | undefined = undefined;
