// This file was generated by agent-compose 0.2.0 from `main.yml` (target `local`).
//
// It is a build artifact, not source: `agent-compose build` overwrites it,
// and `agent-compose build --check` fails when it has been edited. The spec
// is the single source of truth (PRD 5.12); to own this code instead, copy
// the whole directory out and stop regenerating it.
//
// Every `${ENV}` reference the composition makes, and `readEnvironment()`, the
// presence check over them (PRD 5.9, grammar 4.3). `./index.ts` is what calls
// it, at module scope, so loading this project is what checks its environment.
// No value is baked in here: the spec never contains a credential, and neither
// does this file — `agent-compose build` resolved nothing.

import process from "node:process";

/** One `${ENV}` reference, and the surfaces that wrote it. */
export interface EnvironmentReference {
  /** The variable name, between the braces. */
  readonly name: string;
  /** Where it is referenced, as spec addresses. */
  readonly sites: readonly string[];
}

/**
 * Every reference this composition makes, sorted by name.
 *
 * This is also the least-privilege list of PRD 5.9: a deployment of this graph
 * needs these variables and no others.
 */
export const environmentReferences: readonly EnvironmentReference[] = [
  {
    name: "SHAPES_KEY",
    sites: [
      "provider.p.api_key",
    ],
  },
  {
    name: "SHAPES_URL",
    sites: [
      "provider.p.base_url",
    ],
  },
  {
    name: "SHAPE_CALLBACK_SECRET",
    sites: [
      "triggers.signed_in.callback_auth.hmac.secret",
    ],
  },
  {
    name: "SHAPE_CALLBACK_TOKEN",
    sites: [
      "triggers.signed_in.callback_auth.bearer.token",
    ],
  },
  {
    name: "SHAPE_SECRET",
    sites: [
      "triggers.vendor_signed.auth.hmac.secret",
    ],
  },
  {
    name: "SHAPE_TOKEN",
    sites: [
      "triggers.signed_in.auth.bearer.token",
    ],
  },
  {
    name: "WORKSPACE",
    sites: [
      "agent.shaper.tools.builtin.read_file.root",
      "agent.shaper.tools.builtin.write_file.root",
      "agent.shaper.tools.builtin.list.root",
      "agent.shaper.tools.builtin.bash.root",
    ],
  },
];

/** Raised when the process starts without a variable the composition needs. */
export class MissingEnvironmentError extends Error {
  /** Every variable that was missing, sorted by name. */
  readonly missing: readonly EnvironmentReference[];

  constructor(missing: readonly EnvironmentReference[]) {
    const detail = missing
      .map((reference) => `${reference.name} (referenced by ${reference.sites.join(", ")})`)
      .join("; ");
    super(`missing environment ${missing.length === 1 ? "variable" : "variables"}: ${detail}`);
    this.name = "MissingEnvironmentError";
    this.missing = missing;
  }
}

/**
 * Resolve every reference at process start, or throw naming all of them.
 *
 * Presence is `!== undefined`: a variable set to the empty string is set. All
 * missing variables are reported at once, because a deployment that is short
 * three keys should learn that in one run rather than in three.
 */
export function readEnvironment(
  source: Record<string, string | undefined> = process.env,
): ReadonlyMap<string, string> {
  const resolved = new Map<string, string>();
  const missing: EnvironmentReference[] = [];
  for (const reference of environmentReferences) {
    const value = source[reference.name];
    if (value === undefined) {
      missing.push(reference);
    } else {
      resolved.set(reference.name, value);
    }
  }
  if (missing.length > 0) {
    throw new MissingEnvironmentError(missing);
  }
  return resolved;
}
