// This file was generated by agent-compose 0.0.0-dev from `main.yml` (target `local`).
//
// It is a build artifact, not source: `agent-compose build` overwrites it,
// and `agent-compose build --check` fails when it has been edited. The spec
// is the single source of truth (PRD 5.12); to own this code instead, copy
// the whole directory out and stop regenerating it.
//
// Every schema the composition declares, lowered per grammar 3.8. These are the
// runtime contract: an agent's output is parsed with the schema named for it
// before any edge is evaluated, a tool's arguments are parsed with its input
// schema, and a state channel's type is the schema its channel is built from.

import { z } from "zod";

/**
 * The length `min_length` and `max_length` bound (grammar 3.4).
 *
 * JSON Schema counts a string's length in Unicode **code points**, and
 * `String.prototype.length` — which `.min()` and `.max()` count — is UTF-16
 * **code units**. Every character outside the BMP is one of the first and two of
 * the second, so the two disagree in both directions on any string carrying one:
 * `"😀"` is one code point and two units. Spreading a string iterates it by code
 * point, which is the rule the schema this composition published states.
 */
const codePoints = (value: string): number => [...value].length;

/**
 * `unique_items: true` (grammar 3.5). Zod has no built-in.
 *
 * JSON Schema's `uniqueItems` compares *instances*: two objects are one item
 * when they carry the same keys with equal values, in whatever order those keys
 * were written. `JSON.stringify` compares encodings, and an object's encoding
 * follows its key order — so the two are not the same rule in general.
 *
 * They are the same rule **here**. `.refine` runs over the array's already
 * *parsed* elements, and `z.object({…}).strict()` rebuilds every object in the
 * order its own shape declares, so two equal instances have identical encodings
 * by the time this is called. That is a fact about where this is used, which is
 * why it is not exported: applied to raw input, it would call
 * `[{a: 1, b: 2}, {b: 2, a: 1}]` unique and JSON Schema would not.
 *
 * One instance of that fact runs the other way. A property with a `default:` is
 * filled in before this is called, so two items that differ only in omitting it
 * — two instances to JSON Schema — arrive here as one. The parse is stricter
 * than the published schema on exactly those arrays, deliberately: see
 * `omitted-default-is-the-same-item` in the compiler's divergence ledger.
 */
const uniqueItems = (items: readonly unknown[]): boolean =>
  new Set(items.map((item) => JSON.stringify(item))).size === items.length;

/**
 * `format: hostname` (grammar 3.3): an RFC 1123 host name, which is what JSON
 * Schema's `hostname` means. `z.hostname()` is a looser reading — it accepts the
 * root-relative `example.test.`, which JSON Schema refuses — and a value one
 * column accepts and the other refuses is the drift grammar 3.8's table exists
 * to prevent, so the rule is written out.
 */
const rfc1123Hostname = (value: string): boolean => {
  if (value.length === 0 || value.length > 253 || value.endsWith(".")) {
    return false;
  }
  return value.split(".").every((label) => {
    if (label.length === 0 || label.length > 63) {
      return false;
    }
    if (!/^[A-Za-z0-9](?:[A-Za-z0-9-]*[A-Za-z0-9])?$/.test(label)) {
      return false;
    }
    // RFC 5891: hyphens in the third and fourth positions are reserved for the
    // `xn--` prefix of an internationalized label.
    return !(label.length >= 4 && label[2] === "-" && label[3] === "-") || label.startsWith("xn--");
  });
};

/**
 * `format: date` (grammar 3.3): an RFC 3339 `full-date`, calendar-checked — the
 * month bounds the day, and February bounds it by the proleptic Gregorian leap
 * rule, so `2026-02-30` is not a date.
 */
const rfc3339Date = (value: string): boolean => {
  const parts = /^(\d{4})-(\d{2})-(\d{2})$/.exec(value);
  if (parts === null) {
    return false;
  }
  const [, year, month, day] = parts.map(Number);
  if (month < 1 || month > 12 || day < 1) {
    return false;
  }
  const leap = (year % 4 === 0 && year % 100 !== 0) || year % 400 === 0;
  return day <= [31, leap ? 29 : 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31][month - 1];
};

/**
 * `format: time` (grammar 3.3), which JSON Schema reads as RFC 3339 `full-time`
 * — an offset is required. Zod's `z.iso.time()` refuses an offset outright, so
 * the check is written here rather than borrowed from a constructor that means
 * something else. The offset may be `Z`, `z`, or `±HH:MM`, and a leap second is
 * spelled `:60`.
 */
const rfc3339Time =
  /^([01]\d|2[0-3]):[0-5]\d:([0-5]\d|60)(\.\d+)?([Zz]|[+-]([01]\d|2[0-3]):[0-5]\d)$/;

/**
 * `format: date-time` (grammar 3.3): an RFC 3339 `date-time`, which is a
 * `full-date`, the separator, and a `full-time`. The separator is `T` or `t` and
 * the offset may be `Z` or `z`: RFC 3339 says so in as many words, and the JSON
 * Schema column agrees, while `z.iso.datetime()` accepts only the upper-case
 * spellings.
 */
const rfc3339DateTime = (value: string): boolean => {
  const separator = value.search(/[Tt]/);
  return (
    separator > 0 &&
    rfc3339Date(value.slice(0, separator)) &&
    rfc3339Time.test(value.slice(separator + 1))
  );
};

/**
 * `format: uri` (grammar 3.3): an absolute RFC 3986 URI — a scheme, a
 * hierarchical part, and the optional query and fragment — spelled as the
 * grammar's own production. `z.url()` is not this check: it is `new URL()`,
 * which is the WHATWG parser, and that one *repairs* what it is given. It
 * accepts a space and a non-ASCII character in a path (percent-encoding them)
 * and rejects `https://`, which RFC 3986 admits as a URI with an empty
 * authority — divergences in both directions from the column beside it.
 */
const rfc3986Uri =
  /^[A-Za-z][A-Za-z0-9+\-.]*:(?:\/\/(?:(?:[A-Za-z0-9\-._~!$&'()*+,;=:]|%[0-9A-Fa-f]{2})*@)?(?:\[[A-Za-z0-9:.]+\]|(?:[A-Za-z0-9\-._~!$&'()*+,;=]|%[0-9A-Fa-f]{2})*)(?::\d*)?(?:\/(?:[A-Za-z0-9\-._~!$&'()*+,;=:@]|%[0-9A-Fa-f]{2})*)*|\/?(?:(?:[A-Za-z0-9\-._~!$&'()*+,;=:@]|%[0-9A-Fa-f]{2})+(?:\/(?:[A-Za-z0-9\-._~!$&'()*+,;=:@]|%[0-9A-Fa-f]{2})*)*)?)(?:\?(?:[A-Za-z0-9\-._~!$&'()*+,;=:@/?]|%[0-9A-Fa-f]{2})*)?(?:#(?:[A-Za-z0-9\-._~!$&'()*+,;=:@/?]|%[0-9A-Fa-f]{2})*)?$/;

/**
 * `format: uuid` (grammar 3.3): the RFC 4122 (now RFC 9562) string
 * representation — five hyphen-separated groups of hex digits, in either case,
 * which is exactly what JSON Schema's `uuid` reads. `z.uuid()` is a narrower
 * check: it also enforces the version and variant nibbles of the *layout*, so it
 * refuses a Microsoft GUID (`…-c456-…`), a version-0 or version-9 value, and
 * anything else a system upstream of this one minted without following RFC
 * 9562's field rules. The published schema blesses those, so the parse beside it
 * has to as well.
 */
const rfc4122Uuid = /^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}$/;

/**
 * `format: email` (grammar 3.3): an RFC 5322 `addr-spec` whose domain is an RFC
 * 1123 host name or an address literal — the reading JSON Schema's `email`
 * takes. `z.email()` is a deliberately narrow subset of it and refuses three
 * things the column beside it accepts: a quoted local part, a single-label
 * domain (`a@b`), and `a@[192.0.2.1]`.
 */
const rfc5321Email = (value: string): boolean => {
  // The *last* `@` splits: an unquoted local part cannot hold one, and a quoted
  // one can hold as many as it likes.
  const at = value.lastIndexOf("@");
  if (at <= 0 || at === value.length - 1 || at > 64) {
    return false;
  }
  const local = value.slice(0, at);
  const domain = value.slice(at + 1);
  const atext = /^[A-Za-z0-9!#$%&'*+\-/=?^_`{|}~\u0080-\uffff]+$/;
  const quoted = /^(?:[\t \x21\x23-\x5b\x5d-\x7e\u0080-\uffff]|\\[\x21-\x7e])*$/;
  const localOk =
    local.length > 2 && local.startsWith('"') && local.endsWith('"')
      ? quoted.test(local.slice(1, -1))
      : local.split(".").every((atom) => atext.test(atom));
  if (!localOk) {
    return false;
  }
  if (domain.length > 2 && domain.startsWith("[") && domain.endsWith("]")) {
    const literal = domain.slice(1, -1);
    return literal.startsWith("IPv6:")
      ? z.ipv6().safeParse(literal.slice(5)).success
      : z.ipv4().safeParse(literal).success;
  }
  return rfc1123Hostname(domain);
};

/** `agent.shaper` — its declared input (grammar 5.3). */
export const agentShaperInput = z.object({
  goal: z.string().describe("What to shape."),
}).strict();
export type AgentShaperInput = z.infer<typeof agentShaperInput>;

/**
 * `agent.shaper` — the structured output the model is constrained to, and what routing reads (PRD 5.2, 5.3).
 */
export const agentShaperOutput = z.object({
  draft: z.string().refine((value) => codePoints(value) >= 1, { message: "expected at least 1 character" }),
  findings: z.array(z.discriminatedUnion("kind", [
    z.object({
      kind: z.literal("auto_fixable"),
      file: z.string(),
      confidence: z.number().min(0).max(1),
    }).strict(),
    z.object({
      kind: z.literal("needs_human"),
      summary: z.string(),
      severity: z.enum(["low", "high", "critical"]),
    }).strict(),
  ])).max(16).describe("A union inside a bounded array, the fan-out shape."),
  author: z.object({
    name: z.string(),
    email: z.string().refine(rfc5321Email, { message: "expected an email address" }).optional(),
  }).strict(),
}).strict();
export type AgentShaperOutput = z.infer<typeof agentShaperOutput>;

/** `agent.spreader` — its declared input (grammar 5.3). */
export const agentSpreaderInput = z.object({
  goal: z.string(),
}).strict();
export type AgentSpreaderInput = z.infer<typeof agentSpreaderInput>;

/**
 * `agent.spreader` — the structured output the model is constrained to, and what routing reads (PRD 5.2, 5.3).
 */
export const agentSpreaderOutput = z.object({
  note: z.string().refine((value) => codePoints(value) >= 1, { message: "expected at least 1 character" }),
}).strict();
export type AgentSpreaderOutput = z.infer<typeof agentSpreaderOutput>;

/** `flow.condense` — the module's parameters (grammar 7.5). */
export const flowCondenseInputs = z.object({
  passage: z.string().refine((value) => codePoints(value) >= 1, { message: "expected at least 1 character" }).refine((value) => codePoints(value) <= 4096, { message: "expected at most 4096 characters" }),
}).strict();
export type FlowCondenseInputs = z.infer<typeof flowCondenseInputs>;

/**
 * `flow.condense` — the module's result, materialized from the state channels of the same names at quiescence (grammar 7.5, 7.6.3).
 */
export const flowCondenseOutputs = z.object({
  latest: z.string(),
}).strict();
export type FlowCondenseOutputs = z.infer<typeof flowCondenseOutputs>;

/**
 * `flow.condense` node `reduce` — what the subprocess produces (grammar 8.2).
 */
export const flowCondenseNodeReduceOutput = z.object({
  latest: z.string(),
}).strict();
export type FlowCondenseNodeReduceOutput = z.infer<typeof flowCondenseNodeReduceOutput>;

/** `flow.shape` — the module's parameters (grammar 7.5). */
export const flowShapeInputs = z.object({
  goal: z.string().refine((value) => codePoints(value) >= 1, { message: "expected at least 1 character" }),
  goals: z.array(z.object({
    goal: z.string(),
  }).strict()).max(8),
}).strict();
export type FlowShapeInputs = z.infer<typeof flowShapeInputs>;

/**
 * `flow.shape` — the module's result, materialized from the state channels of the same names at quiescence (grammar 7.5, 7.6.3).
 */
export const flowShapeOutputs = z.object({
  draft: z.string(),
  notes: z.array(z.string()).max(32),
}).strict();
export type FlowShapeOutputs = z.infer<typeof flowShapeOutputs>;

/** `flow.shape` node `ask` — what the human is shown (grammar 8.7). */
export const flowShapeNodeAskInput = z.object({
  draft: z.string(),
}).strict();
export type FlowShapeNodeAskInput = z.infer<typeof flowShapeNodeAskInput>;

/**
 * `flow.shape` node `ask` — what the human returns, routable like any structured output (grammar 8.7).
 */
export const flowShapeNodeAskOutput = z.object({
  decision: z.enum(["approve", "reject"]),
}).strict();
export type FlowShapeNodeAskOutput = z.infer<typeof flowShapeNodeAskOutput>;

/**
 * `flow.shape` node `probe` — what the subprocess produces (grammar 8.2), which it does not declare, so this is the kind default.
 */
export const flowShapeNodeProbeOutput = z.object({
  exit_code: z.number().int(),
  stdout: z.string(),
}).strict();
export type FlowShapeNodeProbeOutput = z.infer<typeof flowShapeNodeProbeOutput>;

/**
 * `flow.shape` node `notify` — what the response decodes to (grammar 8.3), which it does not declare, so this is the kind default.
 */
export const flowShapeNodeNotifyOutput = z.object({
  status: z.number().int(),
  body: z.string(),
}).strict();
export type FlowShapeNodeNotifyOutput = z.infer<typeof flowShapeNodeNotifyOutput>;

/**
 * `flow.shape` node `recall` — what the `search` of `store.docs` answers, derived from the op and the store (grammar 11.4, Decision D34).
 */
export const flowShapeNodeRecallOutput = z.object({
  matches: z.array(z.object({
    id: z.string(),
    score: z.number(),
    text: z.string(),
    metadata: z.object({
      source: z.string(),
      updated_at: z.string().refine(rfc3339DateTime, { message: "expected an RFC 3339 date-time" }),
    }).strict(),
  }).strict()).max(3),
}).strict();
export type FlowShapeNodeRecallOutput = z.infer<typeof flowShapeNodeRecallOutput>;

/** `store.docs` — the metadata a match carries (grammar 11.1). */
export const storeDocsMetadataSchema = z.object({
  source: z.string(),
  updated_at: z.string().refine(rfc3339DateTime, { message: "expected an RFC 3339 date-time" }),
}).strict();
export type StoreDocsMetadataSchema = z.infer<typeof storeDocsMetadataSchema>;

/** `store.notes` — the value it stores (grammar 11.1). */
export const storeNotesValueSchema = z.object({
  body: z.string(),
  weight: z.number().min(0),
}).strict();
export type StoreNotesValueSchema = z.infer<typeof storeNotesValueSchema>;

/** `tool.dispatch` — its parameters (grammar 6). */
export const toolDispatchInput = z.object({
  trace: z.string(),
  payload: z.object({
    kind: z.string(),
  }).strict(),
}).strict();
export type ToolDispatchInput = z.infer<typeof toolDispatchInput>;

/** `tool.dispatch` — its result (grammar 6). */
export const toolDispatchOutput = z.object({
  accepted: z.boolean(),
}).strict();
export type ToolDispatchOutput = z.infer<typeof toolDispatchOutput>;

/** `tool.file_ticket` — its parameters (grammar 6). */
export const toolFileTicketInput = z.object({
  title: z.string(),
  summary: z.string(),
}).strict();
export type ToolFileTicketInput = z.infer<typeof toolFileTicketInput>;

/** `tool.file_ticket` — its result (grammar 6). */
export const toolFileTicketOutput = z.object({
  id: z.string(),
}).strict();
export type ToolFileTicketOutput = z.infer<typeof toolFileTicketOutput>;

/** `tool.lookup` — its parameters (grammar 6). */
export const toolLookupInput = z.object({
  term: z.string(),
  limit: z.number().int().min(1),
}).strict();
export type ToolLookupInput = z.infer<typeof toolLookupInput>;

/** `tool.lookup` — its result (grammar 6). */
export const toolLookupOutput = z.object({
  hits: z.array(z.string()).max(8),
}).strict();
export type ToolLookupOutput = z.infer<typeof toolLookupOutput>;

/** `tool.ping` — its parameters (grammar 6). */
export const toolPingInput = z.object({}).strict();
export type ToolPingInput = z.infer<typeof toolPingInput>;

/** `tool.ping` — its result (grammar 6). */
export const toolPingOutput = z.object({}).strict();
export type ToolPingOutput = z.infer<typeof toolPingOutput>;

/** `tool.sandbox` — its parameters (grammar 6). */
export const toolSandboxInput = z.object({
  command: z.string().describe("The shell command to run, as one line of `bash`.").default(""),
  restart: z.boolean().describe("Set to `true` to end this shell session and start a fresh one in the workspace, which is how a wedged shell is recovered. No `command` is run on a call that restarts.").default(false),
}).strict();
export type ToolSandboxInput = z.infer<typeof toolSandboxInput>;

/** `tool.sandbox` — its result (grammar 6). */
export const toolSandboxOutput = z.object({}).strict();
export type ToolSandboxOutput = z.infer<typeof toolSandboxOutput>;

/**
 * `builtin.bash` — the arguments of the runtime built-in of that name, which every attachment of it offers (grammar 5.5).
 */
export const builtinBashInput = z.object({
  command: z.string().describe("The shell command to run, as one line of `bash`.").default(""),
  restart: z.boolean().describe("Set to `true` to end this shell session and start a fresh one in the workspace, which is how a wedged shell is recovered. No `command` is run on a call that restarts.").default(false),
}).strict();
export type BuiltinBashInput = z.infer<typeof builtinBashInput>;

/**
 * `builtin.files` — the arguments of the runtime built-in of that name, which every attachment of it offers (grammar 5.5).
 */
export const builtinFilesInput = z.object({
  command: z.enum(["view", "create", "str_replace", "insert"]).describe("The file operation to perform: `view` reads a file or lists a directory, `create` writes a whole file, `str_replace` swaps one occurrence of a string, `insert` adds text at a line."),
  path: z.string().refine((value) => codePoints(value) >= 1, { message: "expected at least 1 character" }).describe("The file or directory, relative to this tool's workspace."),
  file_text: z.string().describe("The whole contents of the file, for `create`.").default(""),
  old_str: z.string().describe("The exact text to replace, for `str_replace`. It must appear exactly once.").default(""),
  new_str: z.string().describe("The text to put in its place, for `str_replace` and `insert`.").default(""),
  insert_line: z.number().int().min(0).max(1000000).describe("The line to insert after, for `insert`; `0` inserts at the top of the file.").default(0),
}).strict();
export type BuiltinFilesInput = z.infer<typeof builtinFilesInput>;

/** State channel `anything` — its declared type (grammar 10.1). */
export const stateAnything = z.string().regex(/(?:)/);
export type StateAnything = z.infer<typeof stateAnything>;

/** State channel `at` — its declared type (grammar 10.1). */
export const stateAt = z.string().refine(rfc3339DateTime, { message: "expected an RFC 3339 date-time" });
export type StateAt = z.infer<typeof stateAt>;

/** State channel `at_time` — its declared type (grammar 10.1). */
export const stateAtTime = z.string().regex(rfc3339Time);
export type StateAtTime = z.infer<typeof stateAtTime>;

/** State channel `author` — its declared type (grammar 10.1). */
export const stateAuthor = z.object({
  name: z.string(),
  email: z.string().refine(rfc5321Email, { message: "expected an email address" }).optional(),
  home: z.string().regex(rfc3986Uri).optional(),
}).strict();
export type StateAuthor = z.infer<typeof stateAuthor>;

/** State channel `authors` — its declared type (grammar 10.1). */
export const stateAuthors = z.array(z.object({
  name: z.string(),
  rank: z.number().int(),
}).strict()).max(4).refine(uniqueItems, { message: "expected unique items" });
export type StateAuthors = z.infer<typeof stateAuthors>;

/** State channel `cadence` — its declared type (grammar 10.1). */
export const stateCadence = z.number().multipleOf(0.3);
export type StateCadence = z.infer<typeof stateCadence>;

/** State channel `digits` — its declared type (grammar 10.1). */
export const stateDigits = z.string().regex(/^\d{3}-\d{4}$/);
export type StateDigits = z.infer<typeof stateDigits>;

/** State channel `draft` — its declared type (grammar 10.1). */
export const stateDraft = z.string();
export type StateDraft = z.infer<typeof stateDraft>;

/** State channel `glyph` — its declared type (grammar 10.1). */
export const stateGlyph = z.string().regex(/^.$/);
export type StateGlyph = z.infer<typeof stateGlyph>;

/** State channel `host` — its declared type (grammar 10.1). */
export const stateHost = z.string().refine(rfc1123Hostname, { message: "expected a hostname" });
export type StateHost = z.infer<typeof stateHost>;

/** State channel `lasting` — its declared type (grammar 10.1). */
export const stateLasting = z.iso.duration();
export type StateLasting = z.infer<typeof stateLasting>;

/** State channel `latest` — its declared type (grammar 10.1). */
export const stateLatest = z.string().default("");
export type StateLatest = z.infer<typeof stateLatest>;

/** State channel `mark` — its declared type (grammar 10.1). */
export const stateMark = z.string().refine((value) => codePoints(value) >= 2, { message: "expected at least 2 characters" }).refine((value) => codePoints(value) <= 4, { message: "expected at most 4 characters" });
export type StateMark = z.infer<typeof stateMark>;

/** State channel `mood` — its declared type (grammar 10.1). */
export const stateMood = z.enum(["calm", "brisk"]).default("calm");
export type StateMood = z.infer<typeof stateMood>;

/** State channel `notes` — its declared type (grammar 10.1). */
export const stateNotes = z.array(z.string()).max(32).describe("One element per write, in canonical write order.");
export type StateNotes = z.infer<typeof stateNotes>;

/** State channel `on_day` — its declared type (grammar 10.1). */
export const stateOnDay = z.string().refine(rfc3339Date, { message: "expected an RFC 3339 date" });
export type StateOnDay = z.infer<typeof stateOnDay>;

/** State channel `origin` — its declared type (grammar 10.1). */
export const stateOrigin = z.object({
  source: z.discriminatedUnion("kind", [
    z.object({
      kind: z.literal("upload"),
      filename: z.string(),
    }).strict(),
    z.object({
      kind: z.literal("crawl"),
      url: z.string().regex(rfc3986Uri),
      depth: z.number().int().min(0),
    }).strict(),
  ]),
}).strict();
export type StateOrigin = z.infer<typeof stateOrigin>;

/** State channel `ratio` — its declared type (grammar 10.1). */
export const stateRatio = z.number().gt(0).lt(1);
export type StateRatio = z.infer<typeof stateRatio>;

/** State channel `round` — its declared type (grammar 10.1). */
export const stateRound = z.number().int().min(0).multipleOf(1).default(1);
export type StateRound = z.infer<typeof stateRound>;

/** State channel `seen` — its declared type (grammar 10.1). */
export const stateSeen = z.object({
  count: z.number().int().min(0),
}).strict().default({ "count": 0 });
export type StateSeen = z.infer<typeof stateSeen>;

/** State channel `slug` — its declared type (grammar 10.1). */
export const stateSlug = z.string().refine((value) => codePoints(value) >= 1, { message: "expected at least 1 character" }).refine((value) => codePoints(value) <= 64, { message: "expected at most 64 characters" }).regex(/^[a-z][a-z0-9-]*$/);
export type StateSlug = z.infer<typeof stateSlug>;

/** State channel `step` — its declared type (grammar 10.1). */
export const stateStep = z.number().min(-1.5).max(1.5).multipleOf(0.5);
export type StateStep = z.infer<typeof stateStep>;

/** State channel `tags` — its declared type (grammar 10.1). */
export const stateTags = z.array(z.string()).min(1).max(8).refine(uniqueItems, { message: "expected unique items" });
export type StateTags = z.infer<typeof stateTags>;

/** State channel `totals` — its declared type (grammar 10.1). */
export const stateTotals = z.object({
  fixed: z.number().int(),
  skipped: z.number().int(),
}).strict().describe("Partial until every property has been supplied (D101).");
export type StateTotals = z.infer<typeof stateTotals>;

/** State channel `urgent` — its declared type (grammar 10.1). */
export const stateUrgent = z.boolean().default(false);
export type StateUrgent = z.infer<typeof stateUrgent>;

/** State channel `v4` — its declared type (grammar 10.1). */
export const stateV4 = z.ipv4();
export type StateV4 = z.infer<typeof stateV4>;

/** State channel `v6` — its declared type (grammar 10.1). */
export const stateV6 = z.ipv6();
export type StateV6 = z.infer<typeof stateV6>;

/** State channel `visits` — its declared type (grammar 10.1). */
export const stateVisits = z.array(z.object({
  page: z.string(),
  via: z.string().default("direct"),
}).strict()).max(4).refine(uniqueItems, { message: "expected unique items" });
export type StateVisits = z.infer<typeof stateVisits>;

/** State channel `where` — its declared type (grammar 10.1). */
export const stateWhere = z.string().regex(rfc3986Uri);
export type StateWhere = z.infer<typeof stateWhere>;

/** State channel `which` — its declared type (grammar 10.1). */
export const stateWhich = z.string().regex(rfc4122Uuid);
export type StateWhich = z.infer<typeof stateWhich>;

/** State channel `who` — its declared type (grammar 10.1). */
export const stateWho = z.string().refine(rfc5321Email, { message: "expected an email address" });
export type StateWho = z.infer<typeof stateWho>;

/** State channel `word` — its declared type (grammar 10.1). */
export const stateWord = z.string().regex(/\bcat\b/);
export type StateWord = z.infer<typeof stateWord>;
