// This file was generated by agent-compose 0.1.0 from `main.yml` (target `local`).
//
// It is a build artifact, not source: `agent-compose build` overwrites it,
// and `agent-compose build --check` fails when it has been edited. The spec
// is the single source of truth (PRD 5.12); to own this code instead, copy
// the whole directory out and stop regenerating it.
//
// The graph's state model (PRD 5.7 tier 2, grammar 10). Each declared `state:`
// channel is one LangGraph channel typed by its schema in `./schemas.ts`, with
// the reducer its `reduce:` policy names and the initial value its `default:`
// names. `messages` is the implicit conversation history of grammar 10.4, which
// a composition never declares and every graph has.

import { Annotation, MessagesAnnotation } from "@langchain/langgraph";

import * as runtime from "./runtime.ts";
import type { z } from "zod";

import {
  stateAnything,
  stateAt,
  stateAtTime,
  stateAuthor,
  stateAuthors,
  stateCadence,
  stateDigits,
  stateDraft,
  stateGlyph,
  stateHost,
  stateLasting,
  stateLatest,
  stateMark,
  stateMood,
  stateNotes,
  stateOnDay,
  stateOrigin,
  stateRatio,
  stateRound,
  stateSeen,
  stateSlug,
  stateStep,
  stateTags,
  stateTotals,
  stateUrgent,
  stateV4,
  stateV6,
  stateVisits,
  stateWhere,
  stateWhich,
  stateWho,
  stateWord,
} from "./schemas.ts";

/**
 * Every channel of the graph's state, keyed by the name a write targets
 * (grammar 10.3's name-based wiring).
 */
export const channels = {
  /**
   * Unreduced: single-writer, and a write supplies the whole value.
   * Starts **unset**: reading it before its first write fails the execution (Decision D78).
   */
  anything: Annotation<z.infer<typeof stateAnything>>,
  /**
   * Unreduced: single-writer, and a write supplies the whole value.
   * Starts **unset**: reading it before its first write fails the execution (Decision D78).
   */
  at: Annotation<z.infer<typeof stateAt>>,
  /**
   * Unreduced: single-writer, and a write supplies the whole value.
   * Starts **unset**: reading it before its first write fails the execution (Decision D78).
   */
  at_time: Annotation<z.infer<typeof stateAtTime>>,
  /**
   * Unreduced: single-writer, and a write supplies the whole value.
   * Starts **unset**: reading it before its first write fails the execution (Decision D78).
   */
  author: Annotation<z.infer<typeof stateAuthor>>,
  /**
   * Unreduced: single-writer, and a write supplies the whole value.
   * Starts **unset**: reading it before its first write fails the execution (Decision D78).
   */
  authors: Annotation<z.infer<typeof stateAuthors>>,
  /**
   * Unreduced: single-writer, and a write supplies the whole value.
   * Starts **unset**: reading it before its first write fails the execution (Decision D78).
   */
  cadence: Annotation<z.infer<typeof stateCadence>>,
  /**
   * Unreduced: single-writer, and a write supplies the whole value.
   * Starts **unset**: reading it before its first write fails the execution (Decision D78).
   */
  digits: Annotation<z.infer<typeof stateDigits>>,
  /**
   * Unreduced: single-writer, and a write supplies the whole value.
   * Starts **unset**: reading it before its first write fails the execution (Decision D78).
   */
  draft: Annotation<z.infer<typeof stateDraft>>,
  /**
   * Unreduced: single-writer, and a write supplies the whole value.
   * Starts **unset**: reading it before its first write fails the execution (Decision D78).
   */
  glyph: Annotation<z.infer<typeof stateGlyph>>,
  /**
   * Unreduced: single-writer, and a write supplies the whole value.
   * Starts **unset**: reading it before its first write fails the execution (Decision D78).
   */
  host: Annotation<z.infer<typeof stateHost>>,
  /**
   * Unreduced: single-writer, and a write supplies the whole value.
   * Starts **unset**: reading it before its first write fails the execution (Decision D78).
   */
  lasting: Annotation<z.infer<typeof stateLasting>>,
  /**
   * `reduce: last_wins`: concurrent overwrite, declared explicitly; a write supplies the whole value.
   * Starts at `""`.
   */
  latest: Annotation<z.infer<typeof stateLatest>>({
    reducer: (_left, right) => right,
    default: () => "",
  }),
  /**
   * Unreduced: single-writer, and a write supplies the whole value.
   * Starts **unset**: reading it before its first write fails the execution (Decision D78).
   */
  mark: Annotation<z.infer<typeof stateMark>>,
  /**
   * Unreduced: single-writer, and a write supplies the whole value.
   * Starts at `"calm"`.
   */
  mood: Annotation<z.infer<typeof stateMood>>({
    reducer: (_left, right) => right,
    default: () => "calm",
  }),
  /**
   * One element per write, in canonical write order.
   *
   * `reduce: append`: a write supplies **one element**, appended in canonical write order (grammar 7.6.4, Decision D58).
   * Starts at `[]`.
   */
  notes: Annotation<z.infer<typeof stateNotes>, z.infer<typeof stateNotes>[number]>({
    reducer: (left, right) => left.concat([right]),
    default: () => [],
  }),
  /**
   * Unreduced: single-writer, and a write supplies the whole value.
   * Starts **unset**: reading it before its first write fails the execution (Decision D78).
   */
  on_day: Annotation<z.infer<typeof stateOnDay>>,
  /**
   * Unreduced: single-writer, and a write supplies the whole value.
   * Starts **unset**: reading it before its first write fails the execution (Decision D78).
   */
  origin: Annotation<z.infer<typeof stateOrigin>>,
  /**
   * Unreduced: single-writer, and a write supplies the whole value.
   * Starts **unset**: reading it before its first write fails the execution (Decision D78).
   */
  ratio: Annotation<z.infer<typeof stateRatio>>,
  /**
   * Unreduced: single-writer, and a write supplies the whole value.
   * Starts at `1`.
   */
  round: Annotation<z.infer<typeof stateRound>>({
    reducer: (_left, right) => right,
    default: () => 1,
  }),
  /**
   * `reduce: merge`: a write supplies a subset of the properties, merged key-wise in canonical write order — so the value is `Partial` until every property has been supplied (grammar 10.1, Decision D101).
   * Starts at `{ "count": 0 }`.
   */
  seen: Annotation<Partial<z.infer<typeof stateSeen>>, Partial<z.infer<typeof stateSeen>>>({
    reducer: (left, right) => ({ ...left, ...right }),
    default: () => ({ "count": 0 }),
  }),
  /**
   * Unreduced: single-writer, and a write supplies the whole value.
   * Starts **unset**: reading it before its first write fails the execution (Decision D78).
   */
  slug: Annotation<z.infer<typeof stateSlug>>,
  /**
   * Unreduced: single-writer, and a write supplies the whole value.
   * Starts **unset**: reading it before its first write fails the execution (Decision D78).
   */
  step: Annotation<z.infer<typeof stateStep>>,
  /**
   * Unreduced: single-writer, and a write supplies the whole value.
   * Starts **unset**: reading it before its first write fails the execution (Decision D78).
   */
  tags: Annotation<z.infer<typeof stateTags>>,
  /**
   * Partial until every property has been supplied (D101).
   *
   * `reduce: merge`: a write supplies a subset of the properties, merged key-wise in canonical write order — so the value is `Partial` until every property has been supplied (grammar 10.1, Decision D101).
   * Starts at `{}`.
   */
  totals: Annotation<Partial<z.infer<typeof stateTotals>>, Partial<z.infer<typeof stateTotals>>>({
    reducer: (left, right) => ({ ...left, ...right }),
    default: () => ({}),
  }),
  /**
   * Unreduced: single-writer, and a write supplies the whole value.
   * Starts at `false`.
   */
  urgent: Annotation<z.infer<typeof stateUrgent>>({
    reducer: (_left, right) => right,
    default: () => false,
  }),
  /**
   * Unreduced: single-writer, and a write supplies the whole value.
   * Starts **unset**: reading it before its first write fails the execution (Decision D78).
   */
  v4: Annotation<z.infer<typeof stateV4>>,
  /**
   * Unreduced: single-writer, and a write supplies the whole value.
   * Starts **unset**: reading it before its first write fails the execution (Decision D78).
   */
  v6: Annotation<z.infer<typeof stateV6>>,
  /**
   * Unreduced: single-writer, and a write supplies the whole value.
   * Starts **unset**: reading it before its first write fails the execution (Decision D78).
   */
  visits: Annotation<z.infer<typeof stateVisits>>,
  /**
   * Unreduced: single-writer, and a write supplies the whole value.
   * Starts **unset**: reading it before its first write fails the execution (Decision D78).
   */
  where: Annotation<z.infer<typeof stateWhere>>,
  /**
   * Unreduced: single-writer, and a write supplies the whole value.
   * Starts **unset**: reading it before its first write fails the execution (Decision D78).
   */
  which: Annotation<z.infer<typeof stateWhich>>,
  /**
   * Unreduced: single-writer, and a write supplies the whole value.
   * Starts **unset**: reading it before its first write fails the execution (Decision D78).
   */
  who: Annotation<z.infer<typeof stateWho>>,
  /**
   * Unreduced: single-writer, and a write supplies the whole value.
   * Starts **unset**: reading it before its first write fails the execution (Decision D78).
   */
  word: Annotation<z.infer<typeof stateWord>>,
  /**
   * The implicit conversation history (grammar 10.4, PRD 5.7 tier 3): append-only,
   * never declared in `state:`, and isolated across flow boundaries by default.
   */
  messages: MessagesAnnotation.spec.messages,
  /**
   * The compiler's own channel: what the *runtime* needs beside the composition's
   * channels and cannot put anywhere else — the flow instance's input object and
   * execution identity (the `input` and `execution` roots of grammar 4.1), the
   * per-bounded-edge counters grammar 7.4 requires in graph state, the per-node
   * traversal ordinals of grammar 9.4, the step number of grammar 7.6, and the
   * routing trace PRD 5.3 asks for.
   *
   * Grammar 2.1's identifier cannot spell `$run`, so no composition collides with it.
   */
  $run: Annotation<runtime.RunChannel, Partial<runtime.RunChannel>>({
    reducer: runtime.mergeRun,
    default: runtime.emptyRun,
  }),
};

/** The state schema the graph is built from. */
export const State = Annotation.Root(channels);

/** What a node reads: every channel, at its declared type. */
export type GraphState = typeof State.State;

/** What a node writes: any subset of the channels, at their update types. */
export type GraphStateUpdate = typeof State.Update;
