//! `src/cli.ts`: the project's own command line.
//!
//! `agent-compose run` and `agent-compose serve` validate, build, check the
//! environment, and then **launch this** — `bun src/index.ts run flow.<name>
//! --input k=v`, the same launch surface the emitted `README.md` documents
//! first (PRD §9.18). Nothing about invoking a compiled graph lives in the Rust
//! binary, which is what keeps an ejected project runnable by hand: PRD 5.12's
//! eject path is copying the directory, and a directory whose only entry point
//! was a compiler would not be one.
//!
//! It is a **constant**, for the reasons [`super::runtime`] is one. What differs
//! between two projects is the flow registry it reads, which [`super::graph`]
//! emits.
//!
//! # `--input` is text and `inputs:` is typed
//!
//! Grammar 13.2 defers one check to run start — "an unknown argument name, a
//! missing REQUIRED field, or a value that does not fit the declared type fails
//! the run naming the field" — for the same reason env-ref presence is deferred:
//! the values do not exist until the command runs. All three are decided here,
//! and reported as one kind of failure because the sentence makes them one. The
//! argument *name* is checked against the flow's declared inputs; the *value* is
//! read as the field's declared kind before the schema sees it, so an integer
//! field handed `three` fails naming the field rather than failing about a
//! string the author never wrote; and the whole set is then parsed against the
//! flow's own `inputs:` — the same schema a declared trigger's bindings are
//! checked against at compile time — through `runtime.parseResult`, so a missing
//! required field or a value out of range is a sentence naming the field rather
//! than a schema library's dump (PRD G3).
//!
//! # `--session` and the remap a declared `manual` trigger may carry
//!
//! The other run-time argument is the manual payload's one member (grammar
//! 13.2). A declared `manual` trigger naming the flow may remap it through
//! `session_key:`, and [`super::trigger`] emits that expression into the table
//! this reads — which is what keeps the key from being one the compiler accepts
//! and nothing evaluates.

use crate::ir::Ir;

/// The command line's source, carried in the compiler and emitted verbatim.
const SOURCE: &str = include_str!("js/cli.ts");

/// `src/cli.ts`.
#[must_use]
pub fn module(ir: &Ir) -> super::GeneratedFile {
    let mut contents = super::header(ir, "// ");
    contents.push_str(SOURCE);
    super::GeneratedFile {
        path: "src/cli.ts".to_string(),
        contents,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::codegen::test_support::ir_of;

    #[test]
    fn the_module_is_emitted_verbatim_under_the_header() {
        let emitted = module(&ir_of("version: \"0.1\"\n")).contents;
        assert!(emitted.starts_with("// This file was generated by agent-compose"));
        assert!(emitted.contains("export async function main("));
        assert!(
            emitted.ends_with(SOURCE),
            "the command line is emitted verbatim"
        );
    }

    /// stdout carries the answer and stderr the report, which is what makes a
    /// run's outputs readable by a caller that parses one stream.
    #[test]
    fn a_run_prints_its_outputs_on_stdout() {
        assert!(
            SOURCE.contains(
                "process.stdout.write(`${JSON.stringify(produced.outputs, null, 2)}\\n`)"
            )
        );
    }
}
