//! `src/journal.ts`: the record that makes an execution survive its process.
//!
//! [`super::runtime`] emits what a node *does*; this module emits the log of
//! what it did. PRD resolved q26 settles the mechanism — "a journal + replay of
//! the record this runtime already keeps, not a LangGraph checkpointer" — and
//! resolved q27 settles where it lives: a deploy-target slot, exactly as
//! `storage_backends` are, with `--target local` binding a SQLite file beside
//! the project. Every target this compiler release can build is process-local,
//! so SQLite is what every project gets and the composition says nothing about
//! it (`docs/durability.md` §10).
//!
//! It is a **constant**, like [`super::runtime`], [`super::cel`] and
//! [`super::stores`]: byte-identical in every project this compiler release
//! builds, edited as TypeScript in the compiler's own tree
//! (`src/codegen/js/journal.ts`) rather than as a Rust string literal.
//!
//! # Why it is a module of its own
//!
//! Two reasons, and the second is the load-bearing one.
//!
//! It is the **leaf** of the emitted import graph. `src/stores.ts` imports
//! `src/runtime.ts` and `src/runtime.ts` imports this file, so a journal that
//! reached back for either would close a cycle; putting the project's data
//! directory here — re-exported by `src/stores.ts`, which is where an ejected
//! reader learned the name — is what keeps the graph acyclic.
//!
//! And the journal is not the trace. `docs/trace.md` §11 keeps model
//! completions, tool results and human answers *out* of the trace, and replay
//! needs exactly those; a reader who has to be told that two artifacts with one
//! keying discipline have different sensitivity is better served by two files
//! than by one file with a rule in the middle of it.

use crate::ir::Ir;

/// The journal's source, carried in the compiler and emitted verbatim.
const SOURCE: &str = include_str!("js/journal.ts");

/// `src/journal.ts`.
#[must_use]
pub fn module(ir: &Ir) -> super::GeneratedFile {
    let mut contents = super::header(ir, "// ");
    contents.push_str(SOURCE);
    super::GeneratedFile {
        path: "src/journal.ts".to_string(),
        contents,
    }
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeSet;

    use super::*;
    use crate::codegen::test_support::ir_of;

    #[test]
    fn the_module_is_emitted_verbatim_under_the_header() {
        let emitted = module(&ir_of("version: \"0.1\"\n")).contents;
        assert!(emitted.starts_with("// This file was generated by agent-compose"));
        assert!(emitted.ends_with(SOURCE), "the journal is emitted verbatim");
    }

    /// Every composition gets the same journal, like the runtime beside it.
    #[test]
    fn every_composition_gets_the_same_journal() {
        let empty = module(&ir_of("version: \"0.1\"\n")).contents;
        let full = module(&ir_of(crate::codegen::test_support::EVERY_FORM)).contents;
        assert_eq!(empty.replace("main.yml", ""), full.replace("main.yml", ""));
    }

    /// The driver is the one PRD §9.18 admits, and the two it refuses are named
    /// nowhere — the same bind `codegen::stores` puts on the store backends.
    ///
    /// The spec that opened this work asked for `bun:sqlite` on the grounds
    /// that generated artifacts run under Bun. They also run under Node, which
    /// PRD §9.18 makes a supported fallback with a static gate over the whole
    /// golden corpus behind it, and `node-sqlite3-wasm` is already pinned for
    /// the stores — so the same driver costs no new dependency *and* keeps the
    /// promise. This is the assertion that keeps the choice from drifting back.
    #[test]
    fn the_journal_names_no_runtime_specific_sqlite() {
        assert!(SOURCE.contains("await import(\"node-sqlite3-wasm\")"));
        assert!(
            !SOURCE.contains("\"bun:sqlite\"") && !SOURCE.contains("\"node:sqlite\""),
            "a generated module may not reach for an API one supported runtime lacks (PRD §9.18)"
        );
    }

    /// The version a resumed execution is held to is the one the document pins.
    #[test]
    fn the_journal_version_is_the_one_the_document_pins() {
        assert!(SOURCE.contains("export const JOURNAL_VERSION = 1;"));
        let document = include_str!("../../../../docs/durability.md");
        assert!(
            document.contains("**Journal version:** 1"),
            "`docs/durability.md` heads with the version this module emits"
        );
    }

    /// One effect is one statement, which is what makes a crash mid-write
    /// leave a row absent rather than half present (`docs/durability.md` §2).
    #[test]
    fn an_effect_is_appended_by_one_statement() {
        assert!(SOURCE.contains("INSERT INTO effects"));
        assert!(
            !SOURCE.contains("BEGIN IMMEDIATE"),
            "an append that opened a transaction of its own would have a window a crash could land in"
        );
    }

    /// **Every effect site is journaled, and there are no others.**
    ///
    /// `docs/durability.md` §3 makes completeness the invariant — "an effect
    /// that is not journaled is one a replay re-executes" — and tells a reader
    /// to verify it by finding the call sites. This is that reading, held
    /// mechanically, in both directions.
    ///
    /// The **first** direction is the one a new effect kind breaks: a surface
    /// added to `src/runtime.ts` that calls the world and does not reach the
    /// journal is a replay that re-issues it, and no other test in this
    /// repository would notice — the run would succeed, twice.
    ///
    /// The **second** is the one a documentation drift breaks: a site that is
    /// journaled and is not in the table above. Both are counted rather than
    /// merely searched for, because a search satisfied by any occurrence would
    /// be satisfied by the one this comment mentions.
    #[test]
    fn every_effect_site_reaches_the_journal_and_the_document_names_them_all() {
        let runtime = include_str!("js/runtime.ts");
        let stores = include_str!("js/stores.ts");
        let document = include_str!("../../../../docs/durability.md");

        // Each site, the module it lives in, and how it reaches the journal —
        // `journaled(…)` for a call whose whole answer is the record, and
        // `claim(…)` for the two whose record is assembled first (a model
        // call's ladder, a wait's settlement).
        for (site, source, module) in [
            ("callModel", runtime, "src/runtime.ts"),
            ("runExec", runtime, "src/runtime.ts"),
            ("runHttp", runtime, "src/runtime.ts"),
            ("callFunction", runtime, "src/runtime.ts"),
            ("runHuman", runtime, "src/runtime.ts"),
            ("runStoreOp", stores, "src/stores.ts"),
        ] {
            let body = function_body(source, site);
            assert!(
                body.contains("journaled(") || body.contains(".claim("),
                "`{site}` performs an effect and does not reach the journal, so a replay                  would issue it a second time (`docs/durability.md` §3)"
            );
            assert!(
                document.contains(&format!("`{site}`")) && document.contains(module),
                "`docs/durability.md` §3's inventory does not name `{site}` in `{module}`"
            );
        }

        // …and no seventh. The count is over both emitted modules, because the
        // document's table is.
        let reached = runtime.matches("journaled(").count()
            + runtime.matches(".claim(").count()
            + stores.matches("journaled(").count()
            + stores.matches(".claim(").count();
        assert_eq!(
            reached, 6,
            "`docs/durability.md` §3 says there are exactly six effect sites and this build              has {reached}: a new one belongs in that table, and a lost one is a replay that              re-issues an effect"
        );
    }

    /// The six journaled seams, by the name each is declared under.
    const SEAMS: [&str; 6] = [
        "callModel",
        "runExec",
        "runHttp",
        "callFunction",
        "runHuman",
        "runStoreOp",
    ];

    /// **Nothing calls the world except through one of the six.**
    ///
    /// The sibling above reads the inventory from the top down: the six
    /// functions `docs/durability.md` §3 names reach the journal, and no
    /// seventh does. That direction cannot see the failure its own docstring
    /// calls load-bearing — a *new* surface, `runGrpc` say, that spawns a
    /// process or opens a socket and never reaches the journal at all. It is
    /// not one of the six, so no per-site assertion applies to it; it contains
    /// no `journaled(` and no `.claim(`, so the count still answers six; the
    /// table is untouched, so the documentation assertions pass. `cargo test`
    /// is green and every replay past that node issues its call again.
    ///
    /// So this reads it from the bottom up instead, off the **primitives**
    /// rather than off the seams: every `fetch`, every `spawn`, every
    /// filesystem call and every SQLite statement in **every** emitted constant
    /// module has to sit somewhere the six can reach, or be named below as
    /// something that is not an effect the graph issues. `runGrpc` fails here on
    /// the first line of its body.
    ///
    /// Reachability is transitive because the seams are thin: `runExec` calls
    /// `runExecLive`, which calls `spawn`; `runStoreOp` calls `perform`, which
    /// calls `open`, `transact`, `tabular`, `blobOp` and — through
    /// `runtime.callEmbeddings` — `send`, which is where a `vector` store's
    /// network call lives. Following the calls is what keeps the rule honest
    /// without pinning the shape of the code beneath each seam.
    ///
    /// **Every module and every declaration form**, because a blind spot in
    /// either is a place an unjournaled call can sit while this test answers
    /// green. `src/serve.ts` really holds one — the completion webhook — and a
    /// reading that took only `src/runtime.ts` and `src/stores.ts` could not see
    /// it; a reading that took only top-level `function` declarations could not
    /// see a `class HttpPool { async send() { await fetch(…) } }` or a
    /// `const runGrpc = async () => …` in the two modules it did read. So the
    /// file is **partitioned** by its column-zero declarations, whatever their
    /// keyword, and every primitive is attributed to the declaration it sits
    /// under.
    #[test]
    fn nothing_in_the_emitted_runtime_calls_the_world_except_under_a_journaled_seam() {
        // The primitives. Each one *is* the effect — the moment a process
        // leaves itself — so a replay that reaches one has re-executed
        // something whatever the code around it is called.
        const PRIMITIVES: [&str; 13] = [
            "fetch(",
            "spawn(",
            "fs.writeFileSync",
            "fs.readFileSync",
            "fs.renameSync",
            "fs.rmSync",
            "fs.mkdirSync",
            "fs.existsSync",
            "fs.readdirSync",
            "database.run(",
            "database.get(",
            "database.all(",
            "database.exec(",
        ];

        // What calls the world and is **not** an effect the graph issues, so is
        // not one a replay may perform twice. Each is named with its module,
        // because the same name in another module would be a different decision:
        //
        //  * `releaseExecution` — grammar 11.1's `scope: execution` lifetime,
        //    run by `runFlow` when a run ends. It removes what the run owned;
        //    running it twice removes it twice.
        //  * `notify` — the completion webhook of an `async` `http` trigger
        //    (grammar 13.3). It reports an execution that has already ended, and
        //    a row is closed before it fires, so no replay ever reaches it: the
        //    process that finishes a run is the one that calls it, once
        //    (`docs/durability.md` §6.1).
        //  * `writeTrace` — the run's own trace document, written by the command
        //    after the run (`docs/trace.md`). A resumed generation writes a fresh
        //    whole one, which is §9's promise rather than a repeat.
        //  * the journal's **own** storage: `SqliteJournal`, the open path that
        //    creates and migrates the file, the lock a killed writer leaves
        //    behind (§2), and `journalExists`. These are the record itself. A
        //    replay that "re-executed" them would be a replay reading its own
        //    journal, which is what a replay *is*.
        const NOT_AN_EFFECT: [(&str, &str); 8] = [
            ("src/stores.ts", "releaseExecution"),
            ("src/serve.ts", "notify"),
            ("src/cli.ts", "writeTrace"),
            ("src/journal.ts", "SqliteJournal"),
            ("src/journal.ts", "openJournal"),
            ("src/journal.ts", "breakStaleLock"),
            ("src/journal.ts", "migrated"),
            ("src/journal.ts", "journalExists"),
        ];

        let modules = [
            ("src/runtime.ts", include_str!("js/runtime.ts")),
            ("src/stores.ts", include_str!("js/stores.ts")),
            ("src/journal.ts", include_str!("js/journal.ts")),
            ("src/serve.ts", include_str!("js/serve.ts")),
            ("src/cli.ts", include_str!("js/cli.ts")),
            ("src/cel.ts", include_str!("js/cel.ts")),
        ];
        let declared: Vec<(&str, String, String)> = modules
            .iter()
            .flat_map(|(module, source)| {
                declarations(source)
                    .into_iter()
                    .map(move |(name, body)| (*module, name, body))
            })
            .collect();

        for seam in SEAMS {
            assert!(
                declared.iter().any(|(_, name, _)| name == seam),
                "`{seam}` is declared in none of the emitted modules, so this test is reading \
                 an inventory that has moved"
            );
        }

        // Everything the six reach, followed until it stops growing.
        let mut reached: BTreeSet<&str> = SEAMS.into_iter().collect();
        loop {
            let mut grew = false;
            for (_, name, body) in &declared {
                if !reached.contains(name.as_str()) {
                    continue;
                }
                for (_, called, _) in &declared {
                    if reached.contains(called.as_str()) || !calls(body, called) {
                        continue;
                    }
                    reached.insert(called.as_str());
                    grew = true;
                }
            }
            if !grew {
                break;
            }
        }

        let mut exempted: BTreeSet<(&str, &str)> = BTreeSet::new();
        for (module, name, body) in &declared {
            for primitive in PRIMITIVES {
                if !body.contains(primitive) {
                    continue;
                }
                if NOT_AN_EFFECT.contains(&(module, name.as_str())) {
                    exempted.insert((module, name.as_str()));
                    continue;
                }
                assert!(
                    reached.contains(name.as_str()),
                    "`{name}` in `{module}` calls `{primitive}` and nothing journaled reaches \
                     it, so a replay past it issues that call a second time \
                     (`docs/durability.md` §3). Either route it through one of {SEAMS:?}, or — \
                     if it is not an effect the graph issues — say so in this test's \
                     `NOT_AN_EFFECT`."
                );
            }
        }
        assert_eq!(
            exempted,
            NOT_AN_EFFECT
                .into_iter()
                .collect::<BTreeSet<(&str, &str)>>(),
            "an exemption nothing uses is one nobody is checking: drop it"
        );
    }

    /// Whether `body` calls `name`, as a call rather than as a longer word.
    ///
    /// `runtime.` is looked through, because `src/stores.ts` reaches
    /// `src/runtime.ts` through a namespace import and `runtime.callEmbeddings`
    /// is one of the edges this walk depends on.
    fn calls(body: &str, name: &str) -> bool {
        let wanted = format!("{name}(");
        let mut rest = body;
        while let Some(at) = rest.find(&wanted) {
            let before = rest[..at].chars().next_back();
            let boundary = match before {
                None => true,
                Some('.') => rest[..at].ends_with("runtime."),
                Some(character) => {
                    !character.is_alphanumeric() && character != '_' && character != '$'
                }
            };
            if boundary {
                return true;
            }
            rest = &rest[at + wanted.len()..];
        }
        false
    }

    /// What the lines before an emitted module's first declaration are called.
    ///
    /// A primitive there is a module that calls the world **as it loads**, which
    /// no seam could reach and no exemption should quietly cover, so it is named
    /// rather than skipped.
    const MODULE_SCOPE: &str = "<module scope>";

    /// Every top-level declaration of an emitted module, by name and body.
    ///
    /// A **partition** rather than a brace match, and that is the point: each
    /// line at column zero that declares a name opens a region and the region
    /// runs to the next one, so a `class`, a `const … = async () =>` and a
    /// `function` are all read the same way and none of them can hide a call to
    /// the world by being the wrong shape. Matching a closing brace would have to
    /// know each form's, which is the reading that missed a class method.
    ///
    /// **Comment lines are dropped**, because both things this body is read for
    /// are about code: a primitive named in prose is not a call, and a function
    /// named in prose is not an edge in the reachability walk.
    fn declarations(source: &str) -> Vec<(String, String)> {
        let mut found: Vec<(String, String)> = Vec::new();
        let mut name = String::from(MODULE_SCOPE);
        let mut body = String::new();
        for line in source.lines() {
            if let Some(opened) = declared_name(line) {
                found.push((
                    std::mem::replace(&mut name, opened),
                    std::mem::take(&mut body),
                ));
            }
            if is_comment(line) {
                continue;
            }
            body.push_str(line);
            body.push('\n');
        }
        found.push((name, body));
        found
    }

    /// Whether this line is comment or documentation rather than code.
    fn is_comment(line: &str) -> bool {
        let trimmed = line.trim_start();
        trimmed.starts_with("//") || trimmed.starts_with('*') || trimmed.starts_with("/*")
    }

    /// The name a column-zero declaration line opens, if it is one.
    ///
    /// Every keyword an emitted module declares something callable under, which
    /// is what makes the partition above cover a `class` and an arrow-function
    /// `const` as well as a `function`. A `type`, an `interface` and an `import`
    /// declare nothing that can call the world, so they open no region and their
    /// lines stay with the declaration above them.
    fn declared_name(line: &str) -> Option<String> {
        let rest = line.strip_prefix("export ").unwrap_or(line);
        let rest = rest.strip_prefix("async ").unwrap_or(rest);
        let rest = ["function ", "class ", "const ", "let ", "var "]
            .into_iter()
            .find_map(|keyword| rest.strip_prefix(keyword))?;
        let name: String = rest
            .chars()
            .take_while(|character| {
                character.is_alphanumeric() || *character == '_' || *character == '$'
            })
            .collect();
        if name.is_empty() {
            return None;
        }
        Some(name)
    }

    /// The body of one exported function of an emitted module.
    ///
    /// The same reader `compose-core`'s `tests/trace_format_inventory.rs` uses,
    /// and for its reason: a rule about what one function does is only a rule if
    /// it is read off that function rather than off the file around it. Both
    /// emitted modules are formatted, so a top-level declaration opens at column
    /// zero and closes on a line that is exactly `}` — which is what makes a
    /// line scan enough, and a brace count wrong: a signature's own inline
    /// object type (`request: { … }`) opens a brace before the body does.
    fn function_body(source: &str, name: &str) -> String {
        let header = format!("export async function {name}(");
        let mut lines = source.lines().skip_while(|line| !line.starts_with(&header));
        let opened = lines
            .next()
            .unwrap_or_else(|| panic!("the emitted module declares `{header}…`"));
        let mut held = String::from(opened);
        for line in lines {
            held.push('\n');
            held.push_str(line);
            if line == "}" {
                return held;
            }
        }
        panic!("`{name}` has no closing brace in the first column")
    }
}
