//! `src/mesh.ts`: the hub half of the worker protocol (`docs/distributed.md`).
//!
//! The five routes of §3, the dispatch board behind them, and the seam a placed
//! node reaches the mesh through. What differs between two deployments is
//! [`super::deployment`] and [`super::artifact`]; the hub over them is a
//! **constant**, for the reasons [`super::runtime`] and [`super::serve`] are.
//!
//! # Why the routes are mounted from here rather than written into `serve.ts`
//!
//! §2 puts the worker routes "under the same server, the same process, and the
//! same auth story" as the triggers, which is a statement about the *server* and
//! not about the module. What sits behind them — a scheduler, a journaled board,
//! a liveness sweep — is a different subject from "what does an `http` trigger
//! do", and the app calls one function to mount it.
//!
//! # The cross-language pin
//!
//! [`PROTOCOL_VERSION`] is this compiler's copy of the number `src/mesh.ts`
//! declares, and `the_protocol_version_is_the_one_the_hub_speaks` reads the
//! constant back out of the emitted source. It is the same discipline the trace
//! format's version and the journal's already have: two numbers that have to
//! agree, in two languages, pinned by a test rather than by a convention.

use crate::ir::Ir;

/// The hub's source, carried in the compiler and emitted verbatim.
const SOURCE: &str = include_str!("js/mesh.ts");

/// The version of `docs/distributed.md` a compiled project speaks (§10).
///
/// Bumped only for a change that would make a peer of the previous version
/// behave **wrongly** rather than be refused (§10.3). The emitted hub declares
/// the same number and the test below is what keeps them one.
///
/// `2` since PRD resolved q46: a result may settle a dispatch **paused** (§3.4),
/// which a peer of version `1` would read as a node that answered with no
/// output. The handshake triple already refuses mixed releases, so the bump
/// costs nothing in practice — §10 says so where it records it.
pub const PROTOCOL_VERSION: u32 = 2;

/// The routes the hub mounts on a target that declares `placements:` (§3).
///
/// Not [`super::serve::RESERVED_ROUTES`]: those are mounted by every generated
/// app whatever the composition says, so a trigger claiming one is refused at
/// compile time. These are mounted only where the deploy layer has placements,
/// so a trigger claiming one collides at start on a mesh target exactly as two
/// colliding triggers do — which is `src/mesh.ts`'s own note, and the reason
/// this list is here for a reader rather than for a static check.
pub const WORKER_ROUTES: &[(&str, &str)] = &[
    ("POST", "/workers/join"),
    ("GET", "/workers/poll"),
    ("POST", "/workers/effects"),
    ("POST", "/workers/result"),
    ("GET", "/workers/artifact/:hash"),
];

/// `src/mesh.ts`.
#[must_use]
pub fn module(ir: &Ir) -> super::GeneratedFile {
    let mut contents = super::header(ir, "// ");
    contents.push_str(SOURCE);
    super::GeneratedFile {
        path: "src/mesh.ts".to_string(),
        contents,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::codegen::test_support::ir_of;

    #[test]
    fn the_module_is_emitted_verbatim_under_the_header() {
        let emitted = module(&ir_of("version: \"0.1\"\n")).contents;
        assert!(emitted.starts_with("// This file was generated by agent-compose"));
        assert!(emitted.ends_with(SOURCE), "the hub is emitted verbatim");
    }

    /// The two ends of the wire agree about which version of it they speak.
    ///
    /// A hub that declared one number and a compiler that shipped a worker
    /// speaking another would refuse every join with `409` — correctly, and
    /// permanently, for a mesh whose two halves came out of one release.
    #[test]
    fn the_protocol_version_is_the_one_the_hub_speaks() {
        let declared = SOURCE
            .lines()
            .find_map(|line| line.strip_prefix("export const PROTOCOL_VERSION = "))
            .and_then(|rest| rest.strip_suffix(';'))
            .expect("`src/mesh.ts` declares `PROTOCOL_VERSION`");
        assert_eq!(
            declared,
            PROTOCOL_VERSION.to_string(),
            "the hub speaks protocol {declared} and this compiler says {PROTOCOL_VERSION}"
        );
    }

    /// [`WORKER_ROUTES`] is what the hub really mounts.
    ///
    /// Read back out of the source it describes, for the reason
    /// `serve::RESERVED_ROUTES` is: a list that had moved on from the app would
    /// describe a wire the document fixes and the code no longer serves.
    #[test]
    fn the_worker_routes_are_the_ones_the_hub_mounts() {
        let mounted: Vec<(&str, &str)> = SOURCE
            .lines()
            .filter_map(|line| {
                let rest = line.trim_start().strip_prefix("app.")?;
                let (verb, rest) = rest.split_once("(\"")?;
                let (path, _) = rest.split_once('"')?;
                match verb {
                    "get" => Some(("GET", path)),
                    "post" => Some(("POST", path)),
                    "put" => Some(("PUT", path)),
                    _ => None,
                }
            })
            .collect();
        assert_eq!(mounted, WORKER_ROUTES);
    }

    /// The two routes a worker POSTs to take a body larger than the framework's
    /// default.
    ///
    /// §3.3 and §3.4 each close their route's table of statuses and §10.1 lets a
    /// peer rely on them, so a `413` raised underneath the handler is a status
    /// neither gives — and an effect record carries the canonical request and the
    /// whole outcome, so a megabyte is a size this protocol expects rather than a
    /// pathological one. The mount is read back out of the source for the reason
    /// [`WORKER_ROUTES`] is: a limit set in a comment is not a limit.
    #[test]
    fn the_routes_a_worker_posts_to_take_more_than_the_frameworks_default_body() {
        for path in ["/workers/effects", "/workers/result"] {
            let mount = SOURCE
                .lines()
                .find(|line| {
                    line.trim_start()
                        .starts_with(&format!("app.post(\"{path}\""))
                })
                .unwrap_or_else(|| panic!("`src/mesh.ts` mounts `{path}`"));
            assert!(
                mount.contains("bodyLimit: BODY_LIMIT"),
                "`{path}` is mounted at the framework's default body limit, so a record or a \
                 result over a megabyte is answered `413` — a status `docs/distributed.md` §3.3 \
                 and §3.4 do not give the route: {mount}"
            );
        }
        assert!(
            SOURCE.contains("const BODY_LIMIT = 256 * 1024 * 1024;"),
            "`src/mesh.ts`'s read ceiling is not the one \
             `crates/agent-compose/src/worker/wire.rs` reads an answer under, so the two \
             directions of this wire carry different limits"
        );
    }

    /// A dispatch claimed for a worker that had already hung up goes **back on
    /// the board** (§7).
    ///
    /// §7 makes dispatch at-least-once: "a hub that cannot tell whether a
    /// dispatch arrived re-issues it". The claim is not free of time — opening
    /// the journal and taking the row is an `await` — so the latch that says
    /// whether the worker is still there is read again after it, and a row
    /// claimed for a socket nothing was written to is handed back rather than
    /// left `dispatched`. What that would otherwise cost is not one liveness
    /// window but the node's whole `timeout:` chain (§6.5): the worker on the
    /// other end is alive and polling, so §6.3 never fires.
    #[test]
    fn a_dispatch_claimed_for_a_worker_that_hung_up_goes_back_on_the_board() {
        let poll = function_body("async function poll(");
        let claim = poll
            .find("await taken(session)")
            .expect("`poll` claims a dispatch");
        let release = poll
            .find("await released(")
            .unwrap_or_else(|| panic!("`poll` never hands a claim back: {poll}"));
        assert!(
            release > claim,
            "`poll` reads the hangup latch only before the claim, so a worker that went away \
             inside it leaves a row `dispatched` to a session that never received it: {poll}"
        );
        let released = function_body("async function released(");
        assert!(
            released.contains("journal.releaseDispatch(id, session)"),
            "a claim is handed back somewhere other than the journal, and \
             `docs/distributed.md` §8 rule 3 keeps dispatch state nowhere else: {released}"
        );
        assert!(
            released.contains("stirPolls()"),
            "a row put back on the board wakes no held poll, so the placement's next worker \
             waits out a whole hold for work that is ready: {released}"
        );
    }

    /// A paused result is held to the **dispatch's own instance path**, both of
    /// the identities it carries (§3.4, §8).
    ///
    /// §8's single writer, stated for the route that also plants a wait. The
    /// effects route already refuses a record whose `site` falls outside its
    /// dispatch, and a paused result carries two such identities: the effect
    /// record its answer will be journaled under, and the wait id the hub puts on
    /// its board. Neither may name a node this session was not dispatched — the
    /// first would let one session write an effect another node replays, and the
    /// second would put a question on the board under somebody else's identity,
    /// which the resume surface would then answer.
    ///
    /// **The effect `key` is a third identity and is held with them**, because it
    /// is the field the record is actually written under: a `site` inside this
    /// dispatch carrying a key outside it would land a `human` record in another
    /// node's slot, where that node's replay claims it and raises a divergence
    /// the offending session's execution can never absorb. Both readers of the
    /// wire are checked, since the effects route writes keys the same way.
    #[test]
    fn a_paused_result_may_not_name_a_node_its_dispatch_does_not_hold() {
        let read = function_body("function pauseOf(");
        assert!(
            read.contains("under(wait, row.site)") && read.contains("under(site, row.site)"),
            "a paused settlement is read without holding its wait and its effect record to the \
             dispatch's own instance path, so one session could plant a wait — and journal an \
             answer — under a node it was never dispatched (docs/distributed.md §8): {read}"
        );
        assert!(
            read.contains("key !== effectKey(site, \"human\", ordinal)"),
            "a paused settlement is read without holding its effect `key` to the site and ordinal \
             beside it, so a session could journal its answer under another node's key: {read}"
        );
        let batch = function_body("function recordOf(");
        assert!(
            batch.contains("key !== effectKey(site,"),
            "the effects route takes a record whose `key` is not the one its own `site`, `kind` \
             and `ordinal` derive, which is the same hole one ledger over: {batch}"
        );
        // …and the answer is journaled under the identity the **worker** derived
        // rather than one this side works out again: two derivations of one
        // effect key agree on the day they are written, and part as a
        // `ReplayDivergence` on the redispatch.
        let journaled = function_body("async function answered(");
        assert!(
            journaled.contains("key: pause.effect.key")
                && journaled.contains("request: pause.effect.request"),
            "the hub re-derives the pause's effect identity instead of carrying the worker's, \
             which the redispatch's replay would refuse: {journaled}"
        );
    }

    /// §13's first row, held to its conservative default in the code.
    ///
    /// "Session dispatch capacity is exactly one" is a question the PRD owes an
    /// answer to, and until it has one an implementation may not decide it — so
    /// the wire's OPTIONAL capacity field is neither sent nor read, and no knob
    /// for it exists. A grep is the honest test for an absence.
    #[test]
    fn the_hub_declares_no_dispatch_capacity_of_any_kind() {
        for spelled in ["capacity", "maxDispatches", "max_dispatches"] {
            assert!(
                !code().contains(spelled),
                "`src/mesh.ts` has code mentioning `{spelled}`, and a session's dispatch capacity \
                 is an open PRD question `docs/distributed.md` §13 forbids an implementation from \
                 deciding"
            );
        }
    }

    /// …and the positive half of the same row: a session carries exactly the
    /// fields §5 gives it.
    ///
    /// A denylist holds the spellings a capacity has arrived under before; this
    /// holds the one nobody has spelled yet. A `Session` that grew a `slots`, a
    /// `budget`, an `inFlight` or a second `dispatchable` would be a dispatch
    /// capacity whatever it was called, and §13's first row forbids this
    /// implementation from deciding that number — so the shape of the record the
    /// hub keeps per worker is pinned rather than scanned.
    #[test]
    fn a_session_carries_exactly_the_fields_the_document_gives_it() {
        assert_eq!(
            fields_of("interface Session {"),
            ["id", "claims", "dispatchable", "seen"],
            "`src/mesh.ts`'s `Session` is not the record `docs/distributed.md` §5 describes: a \
             field added to it is how a dispatch capacity would arrive without being called one, \
             and §13's first row is the PRD question that forbids"
        );
    }

    /// The field names one top-level interface of the hub declares, in order.
    fn fields_of(header: &str) -> Vec<String> {
        function_body(header)
            .lines()
            .skip(1)
            .filter_map(|line| {
                let trimmed = line.trim_start();
                // Prose, and the blank lines between it: a field is a line that
                // declares one.
                if trimmed.starts_with("//")
                    || trimmed.starts_with('*')
                    || trimmed.starts_with("/*")
                {
                    return None;
                }
                let declaration = trimmed.strip_suffix(';')?;
                let (name, _) = declaration.split_once(':')?;
                Some(
                    name.trim()
                        .trim_start_matches("readonly ")
                        .trim()
                        .to_string(),
                )
            })
            .collect()
    }

    /// …and §13's second, the same way: v1 ships no sandbox and no
    /// per-placement restriction, so nothing here names one.
    #[test]
    fn the_hub_declares_no_containment_surface() {
        for spelled in ["sandbox", "seccomp", "restrictions"] {
            assert!(
                !code().contains(spelled),
                "`src/mesh.ts` has code mentioning `{spelled}`, and containment beyond the process \
                 boundary is `docs/distributed.md` §13's other open question"
            );
        }
    }

    /// The hub's source with its prose taken out.
    ///
    /// The two rows above — §13's first two, the ones that name a **knob** —
    /// are about what the hub does, and both are explained at length in the
    /// comments, an absence a reader could take for an oversight being worse
    /// than one they are told about. So a scan over the whole file would be a
    /// scan that fails for saying why it passes.
    fn code() -> String {
        SOURCE
            .lines()
            .filter(|line| {
                let trimmed = line.trim_start();
                !trimmed.starts_with("//")
                    && !trimmed.starts_with('*')
                    && !trimmed.starts_with("/*")
            })
            .collect::<Vec<_>>()
            .join("\n")
    }

    /// The credential is compared in constant time, wherever it is compared.
    ///
    /// The same property `tests/trigger_auth_surface.rs` holds the trigger
    /// credential to, asked of the one that admits a worker to the whole mesh
    /// (§9.3): a byte-by-byte early return hands the join token to anybody who
    /// can time a refusal.
    #[test]
    fn the_join_token_is_compared_in_constant_time() {
        let equal = function_body("function equal(");
        assert!(equal.contains("timingSafeEqual("), "{equal}");
        assert!(
            !equal.contains("offered ===") && !equal.contains("=== offered"),
            "the credential a worker offered is compared directly somewhere in `equal`: {equal}"
        );
        assert!(SOURCE.contains("import { createHash, timingSafeEqual } from \"node:crypto\";"));
    }

    /// There is exactly one liveness signal, and it is the poll (§3.2).
    #[test]
    fn the_hub_mounts_no_second_liveness_route() {
        for spelled in ["/workers/heartbeat", "/workers/ping", "/workers/alive"] {
            assert!(
                !SOURCE.contains(spelled),
                "`src/mesh.ts` mounts `{spelled}`, and §3.2 says there MUST NOT be a second \
                 liveness route: a poll is the only request that answers `is this worker there`"
            );
        }
    }

    /// The body of one top-level declaration of the hub.
    ///
    /// The same reader `codegen::serve` uses, for the same reason: a rule about
    /// what one function does is only a rule if it is read off that function.
    fn function_body(header: &str) -> String {
        let mut lines = SOURCE.lines().skip_while(|line| !line.starts_with(header));
        let opened = lines
            .next()
            .unwrap_or_else(|| panic!("`src/mesh.ts` declares `{header}…`"));
        let mut held = String::from(opened);
        for line in lines {
            held.push('\n');
            held.push_str(line);
            if line == "}" {
                return held;
            }
        }
        panic!("`{header}…` has no closing brace in the first column")
    }
}
