//! `src/mesh.ts`: the hub half of the worker protocol (`docs/distributed.md`).
//!
//! The five routes of §3, the dispatch board behind them, and the seam a placed
//! node reaches the mesh through. What differs between two deployments is
//! [`super::deployment`] and [`super::artifact`]; the hub over them is a
//! **constant**, for the reasons [`super::runtime`] and [`super::serve`] are.
//!
//! # Why the routes are mounted from here rather than written into `serve.ts`
//!
//! §2 puts the worker routes "under the same server, the same process, and the
//! same auth story" as the triggers, which is a statement about the *server* and
//! not about the module. What sits behind them — a scheduler, a journaled board,
//! a liveness sweep — is a different subject from "what does an `http` trigger
//! do", and the app calls one function to mount it.
//!
//! # The cross-language pin
//!
//! [`PROTOCOL_VERSION`] is this compiler's copy of the number `src/mesh.ts`
//! declares, and `the_protocol_version_is_the_one_the_hub_speaks` reads the
//! constant back out of the emitted source. It is the same discipline the trace
//! format's version and the journal's already have: two numbers that have to
//! agree, in two languages, pinned by a test rather than by a convention.

use crate::ir::Ir;

/// The hub's source, carried in the compiler and emitted verbatim.
const SOURCE: &str = include_str!("js/mesh.ts");

/// The version of `docs/distributed.md` a compiled project speaks (§10).
///
/// Bumped only for a change that would make a peer of the previous version
/// behave **wrongly** rather than be refused (§10.3). The emitted hub declares
/// the same number and the test below is what keeps them one.
pub const PROTOCOL_VERSION: u32 = 1;

/// The routes the hub mounts on a target that declares `placements:` (§3).
///
/// Not [`super::serve::RESERVED_ROUTES`]: those are mounted by every generated
/// app whatever the composition says, so a trigger claiming one is refused at
/// compile time. These are mounted only where the deploy layer has placements,
/// so a trigger claiming one collides at start on a mesh target exactly as two
/// colliding triggers do — which is `src/mesh.ts`'s own note, and the reason
/// this list is here for a reader rather than for a static check.
pub const WORKER_ROUTES: &[(&str, &str)] = &[
    ("POST", "/workers/join"),
    ("GET", "/workers/poll"),
    ("POST", "/workers/effects"),
    ("POST", "/workers/result"),
    ("GET", "/workers/artifact/:hash"),
];

/// `src/mesh.ts`.
#[must_use]
pub fn module(ir: &Ir) -> super::GeneratedFile {
    let mut contents = super::header(ir, "// ");
    contents.push_str(SOURCE);
    super::GeneratedFile {
        path: "src/mesh.ts".to_string(),
        contents,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::codegen::test_support::ir_of;

    #[test]
    fn the_module_is_emitted_verbatim_under_the_header() {
        let emitted = module(&ir_of("version: \"0.1\"\n")).contents;
        assert!(emitted.starts_with("// This file was generated by agent-compose"));
        assert!(emitted.ends_with(SOURCE), "the hub is emitted verbatim");
    }

    /// The two ends of the wire agree about which version of it they speak.
    ///
    /// A hub that declared one number and a compiler that shipped a worker
    /// speaking another would refuse every join with `409` — correctly, and
    /// permanently, for a mesh whose two halves came out of one release.
    #[test]
    fn the_protocol_version_is_the_one_the_hub_speaks() {
        let declared = SOURCE
            .lines()
            .find_map(|line| line.strip_prefix("export const PROTOCOL_VERSION = "))
            .and_then(|rest| rest.strip_suffix(';'))
            .expect("`src/mesh.ts` declares `PROTOCOL_VERSION`");
        assert_eq!(
            declared,
            PROTOCOL_VERSION.to_string(),
            "the hub speaks protocol {declared} and this compiler says {PROTOCOL_VERSION}"
        );
    }

    /// [`WORKER_ROUTES`] is what the hub really mounts.
    ///
    /// Read back out of the source it describes, for the reason
    /// `serve::RESERVED_ROUTES` is: a list that had moved on from the app would
    /// describe a wire the document fixes and the code no longer serves.
    #[test]
    fn the_worker_routes_are_the_ones_the_hub_mounts() {
        let mounted: Vec<(&str, &str)> = SOURCE
            .lines()
            .filter_map(|line| {
                let rest = line.trim_start().strip_prefix("app.")?;
                let (verb, rest) = rest.split_once("(\"")?;
                let (path, _) = rest.split_once('"')?;
                match verb {
                    "get" => Some(("GET", path)),
                    "post" => Some(("POST", path)),
                    "put" => Some(("PUT", path)),
                    _ => None,
                }
            })
            .collect();
        assert_eq!(mounted, WORKER_ROUTES);
    }

    /// §13's first row, held to its conservative default in the code.
    ///
    /// "Session dispatch capacity is exactly one" is a question the PRD owes an
    /// answer to, and until it has one an implementation may not decide it — so
    /// the wire's OPTIONAL capacity field is neither sent nor read, and no knob
    /// for it exists. A grep is the honest test for an absence.
    #[test]
    fn the_hub_declares_no_dispatch_capacity_of_any_kind() {
        for spelled in ["capacity", "maxDispatches", "max_dispatches"] {
            assert!(
                !code().contains(spelled),
                "`src/mesh.ts` has code mentioning `{spelled}`, and a session's dispatch capacity \
                 is an open PRD question `docs/distributed.md` §13 forbids an implementation from \
                 deciding"
            );
        }
    }

    /// …and §13's second, the same way: v1 ships no sandbox and no
    /// per-placement restriction, so nothing here names one.
    #[test]
    fn the_hub_declares_no_containment_surface() {
        for spelled in ["sandbox", "seccomp", "restrictions"] {
            assert!(
                !code().contains(spelled),
                "`src/mesh.ts` has code mentioning `{spelled}`, and containment beyond the process \
                 boundary is `docs/distributed.md` §13's other open question"
            );
        }
    }

    /// The hub's source with its prose taken out.
    ///
    /// The two rows above — §13's first two, the ones that name a **knob** —
    /// are about what the hub does, and both are explained at length in the
    /// comments, an absence a reader could take for an oversight being worse
    /// than one they are told about. So a scan over the whole file would be a
    /// scan that fails for saying why it passes.
    fn code() -> String {
        SOURCE
            .lines()
            .filter(|line| {
                let trimmed = line.trim_start();
                !trimmed.starts_with("//")
                    && !trimmed.starts_with('*')
                    && !trimmed.starts_with("/*")
            })
            .collect::<Vec<_>>()
            .join("\n")
    }

    /// The credential is compared in constant time, wherever it is compared.
    ///
    /// The same property `tests/trigger_auth_surface.rs` holds the trigger
    /// credential to, asked of the one that admits a worker to the whole mesh
    /// (§9.3): a byte-by-byte early return hands the join token to anybody who
    /// can time a refusal.
    #[test]
    fn the_join_token_is_compared_in_constant_time() {
        let equal = function_body("function equal(");
        assert!(equal.contains("timingSafeEqual("), "{equal}");
        assert!(
            !equal.contains("offered ===") && !equal.contains("=== offered"),
            "the credential a worker offered is compared directly somewhere in `equal`: {equal}"
        );
        assert!(SOURCE.contains("import { createHash, timingSafeEqual } from \"node:crypto\";"));
    }

    /// There is exactly one liveness signal, and it is the poll (§3.2).
    #[test]
    fn the_hub_mounts_no_second_liveness_route() {
        for spelled in ["/workers/heartbeat", "/workers/ping", "/workers/alive"] {
            assert!(
                !SOURCE.contains(spelled),
                "`src/mesh.ts` mounts `{spelled}`, and §3.2 says there MUST NOT be a second \
                 liveness route: a poll is the only request that answers `is this worker there`"
            );
        }
    }

    /// The body of one top-level declaration of the hub.
    ///
    /// The same reader `codegen::serve` uses, for the same reason: a rule about
    /// what one function does is only a rule if it is read off that function.
    fn function_body(header: &str) -> String {
        let mut lines = SOURCE.lines().skip_while(|line| !line.starts_with(header));
        let opened = lines
            .next()
            .unwrap_or_else(|| panic!("`src/mesh.ts` declares `{header}…`"));
        let mut held = String::from(opened);
        for line in lines {
            held.push('\n');
            held.push_str(line);
            if line == "}" {
                return held;
            }
        }
        panic!("`{header}…` has no closing brace in the first column")
    }
}
