//! `src/runtime.ts`: what every compiled node does when it runs.
//!
//! [`super::graph`] emits the *composition* — one descriptor per node, the
//! guards, the budgets, the wiring — and this module emits everything those
//! descriptors share: the activity loop of grammar 9, the two provider
//! surfaces, the subprocess and HTTP wrappers, the intra-agent tool loop, and
//! the router of grammar 7.3.
//!
//! It is a **constant**: byte-identical in every project this compiler release
//! builds. Two things follow, and both are the reason it is a whole module
//! rather than text interleaved with the per-composition emission:
//!
//! * a golden diff is about the composition, not about the runtime beside it —
//!   the runtime moves only when the compiler version in the header does;
//! * the file is real TypeScript in the compiler's own tree
//!   (`src/codegen/js/runtime.ts`), so it is edited, read and reviewed as
//!   TypeScript rather than as a Rust string literal.
//!
//! The decisions it carries — why LangGraph's own `retryPolicy`/`timeout` are
//! not used, why the model is called with `fetch` rather than through an SDK,
//! and what an agent node contributes to the conversation channel — are argued
//! in the emitted file's own header, where a reader of a generated project
//! finds them.

use crate::ir::Ir;

/// The runtime's source, carried in the compiler and emitted verbatim.
const SOURCE: &str = include_str!("js/runtime.ts");

/// `src/runtime.ts`.
#[must_use]
pub fn module(ir: &Ir) -> super::GeneratedFile {
    let mut contents = super::header(ir, "// ");
    contents.push_str(SOURCE);
    super::GeneratedFile {
        path: "src/runtime.ts".to_string(),
        contents,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::codegen::test_support::ir_of;

    #[test]
    fn the_module_is_emitted_verbatim_under_the_header() {
        let emitted = module(&ir_of("version: \"0.1\"\n")).contents;
        assert!(emitted.starts_with("// This file was generated by agent-compose"));
        assert!(emitted.contains("export async function runNode("));
        assert!(emitted.ends_with(SOURCE), "the runtime is emitted verbatim");
    }

    /// The runtime is the same bytes for every composition: a project that
    /// declares nothing and one that declares everything differ in `graph.ts`,
    /// and this is what makes that true.
    #[test]
    fn every_composition_gets_the_same_runtime() {
        let empty = module(&ir_of("version: \"0.1\"\n")).contents;
        let full = module(&ir_of(crate::codegen::test_support::EVERY_FORM)).contents;
        assert_eq!(
            empty.replace("main.yml", ""),
            full.replace("main.yml", ""),
            "the runtime differs between two compositions"
        );
    }
}
