//! `src/runtime.ts`: what every compiled node does when it runs.
//!
//! [`super::graph`] emits the *composition* — one descriptor per node, the
//! guards, the budgets, the wiring — and this module emits everything those
//! descriptors share: the activity loop of grammar 9, the two provider
//! surfaces, the subprocess and HTTP wrappers, the intra-agent tool loop, and
//! the router of grammar 7.3.
//!
//! It is a **constant**: byte-identical in every project this compiler release
//! builds. Two things follow, and both are the reason it is a whole module
//! rather than text interleaved with the per-composition emission:
//!
//! * a golden diff is about the composition, not about the runtime beside it —
//!   the runtime moves only when the compiler version in the header does;
//! * the file is real TypeScript in the compiler's own tree
//!   (`src/codegen/js/runtime.ts`), so it is edited, read and reviewed as
//!   TypeScript rather than as a Rust string literal.
//!
//! The decisions it carries — why LangGraph's own `retryPolicy`/`timeout` are
//! not used, why the model is called with `fetch` rather than through an SDK,
//! and what an agent node contributes to the conversation channel — are argued
//! in the emitted file's own header, where a reader of a generated project
//! finds them.
//!
//! # The divergence ledger
//!
//! What the *wire* cannot be asked to do, in the ledger style [`super::cel`],
//! [`super::schema`] and [`super::graph`] use: a difference between what the
//! compiler promises and what a provider surface will accept, signed off on
//! rather than re-derived.
//!
//! | id | where | which way | why it is left |
//! |---|---|---|---|
//! | `strict-is-refused-by-an-optional-property` | an agent's `output:` on the Chat Completions surface, when any object in it declares `optional:` | the request carries `strict: false`, so the decoder is **not** constrained by the schema its answer is then parsed with | OpenAI's structured-output decoder closes a schema only when every object in it lists every property in `required` and sets `additionalProperties: false`, all the way down (`crates/mock-provider/WIRE-NOTES.md` (13), which is also what the mock enforces); `optional:` (grammar 3.4) is exactly the construct that breaks the first, and a result schema refuses `default:` (grammar 3.9) so `optional:` is the only way in. The three ways out are all worse. Sending `strict: true` anyway is a 400 — the composition would not run at all. Rewriting the property to the `["string", "null"]`-and-required shape OpenAI documents would make the schema the model is constrained by different from the schema its answer is parsed with, which is the one property PRD 9.16 says must hold and the whole reason `withStructuredOutput` was refused. Refusing the composition at `build` would make a legal grammar unbuildable on three of grammar 12.1's six kinds over a construct the Messages API has no trouble with — `tool_choice` pins the tool and the schema goes on the wire whole. So the parse stays the contract: the emitted node function answers `<agent>Output.parse(…)` over [`super::schema`]'s Zod, which is the same schema at either `strict`, and an unconstrained model that misses it is a node error rather than a bad write. `a_nested_optional_property_costs_the_strict_decoder_and_not_the_parse` pins both halves |
//!
//! The row is reachable from ordinary grammar, which is why it is pinned rather
//! than left to be discovered: `agent-openai`'s `flow.triage` is the shape, and
//! the acceptance test named above asserts the `strict: false` on the recorded
//! request *and* that the run still refuses an answer the schema does not admit.

use crate::ir::Ir;

/// The runtime's source, carried in the compiler and emitted verbatim.
const SOURCE: &str = include_str!("js/runtime.ts");

/// `src/runtime.ts`.
#[must_use]
pub fn module(ir: &Ir) -> super::GeneratedFile {
    let mut contents = super::header(ir, "// ");
    contents.push_str(SOURCE);
    super::GeneratedFile {
        path: "src/runtime.ts".to_string(),
        contents,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::codegen::test_support::ir_of;

    #[test]
    fn the_module_is_emitted_verbatim_under_the_header() {
        let emitted = module(&ir_of("version: \"0.1\"\n")).contents;
        assert!(emitted.starts_with("// This file was generated by agent-compose"));
        assert!(emitted.contains("export async function runNode("));
        assert!(emitted.ends_with(SOURCE), "the runtime is emitted verbatim");
    }

    /// The compiler's endpoint table and the runtime's fallback are one fact
    /// written twice, in two languages, and this is the seam between them.
    ///
    /// `ProviderKind::default_endpoint` is what makes the credential rule
    /// decidable — "no `base_url:`" means "reaching the vendor" — and the
    /// diagnostic quotes the host. If the emitted `baseUrl` ever fell back
    /// somewhere else, `validate` would be requiring a key for an endpoint the
    /// run does not reach, which is a rule about nothing. Held from the Rust
    /// side because that is the side with the table (grammar 12.1,
    /// Decision D120).
    #[test]
    fn the_default_endpoints_are_the_ones_the_emitted_runtime_falls_back_to() {
        for kind in crate::ast::definition::ProviderKind::ALL {
            let Some(endpoint) = kind.default_endpoint() else {
                continue;
            };
            assert!(
                SOURCE.contains(&format!(
                    "if (provider.kind === \"{}\") return \"{endpoint}\";",
                    kind.as_str()
                )),
                "the emitted runtime does not fall back to `{endpoint}` for `{}`",
                kind.as_str()
            );
        }
    }

    /// A key the composition never declared reaches the wire as no header, not
    /// as an empty one (grammar 12.1, Decision D120).
    ///
    /// Stated over the emitted source because the runtime is a constant this
    /// crate ships: the acceptance suite proves it on a live request, and this
    /// is what fails first if the `?? ""` spelling comes back on either wire.
    #[test]
    fn neither_wire_defaults_an_absent_key_to_an_empty_header() {
        assert!(
            !SOURCE.contains("apiKey ?? \"\""),
            "an absent `api_key:` is a dropped header, never an empty one"
        );
        assert_eq!(
            SOURCE.matches(".apiKey").count(),
            1,
            "every wire reads the key through `credential`, which is the one place that \
             decides whether a header is sent at all"
        );
        assert!(
            SOURCE.contains("...credential(model.provider, \"x-api-key\")"),
            "the Messages wire authenticates through `credential`"
        );
        assert!(
            SOURCE.contains("credential(provider, azure ? \"api-key\" : \"authorization\")"),
            "both OpenAI-shaped wires authenticate through `credential`"
        );
    }

    /// The runtime is the same bytes for every composition: a project that
    /// declares nothing and one that declares everything differ in `graph.ts`,
    /// and this is what makes that true.
    #[test]
    fn every_composition_gets_the_same_runtime() {
        let empty = module(&ir_of("version: \"0.1\"\n")).contents;
        let full = module(&ir_of(crate::codegen::test_support::EVERY_FORM)).contents;
        assert_eq!(
            empty.replace("main.yml", ""),
            full.replace("main.yml", ""),
            "the runtime differs between two compositions"
        );
    }
}
