//! `src/serve.ts`: the generated app for a project's `http` triggers.
//!
//! PRD 5.11's codegen note is the whole brief — "`http` → a generated Fastify
//! app wrapping the compiled graph (start / resume / status routes), reusing the
//! same generated Zod schemas for payload validation" — and this is the app.
//! What differs between two projects is the *table* it serves, which
//! [`super::trigger`] emits; the app over it is a **constant**, for the reasons
//! [`super::runtime`] is one.
//!
//! # Why Fastify is pinned exactly
//!
//! The same reason PRD 5.12 pins LangGraph exactly: what a framework does with a
//! body it cannot decode, and what status it answers with, is part of what a
//! compiled graph does — grammar 13.3 and Decision D117 both state behaviour a
//! caller observes at the route. A caret here would let a release move that with
//! no commit saying so.
//!
//! Which is also why the app does not simply *inherit* that behaviour: D117
//! states its rule over bodies rather than over media types, and the stock
//! parser set decides one of its two rows the other way — an empty body on a
//! body-bearing method is a `400` there and an execution here. The app installs
//! one parser of its own for every content type, so what a caller observes is
//! the grammar's rule rather than a framework default the pin merely freezes
//! (see `decodeBodies` in `js/serve.ts`).
//!
//! # What the app tracks, and what the journal does
//!
//! The **reports** are this process's: a status route answers `404` for an id
//! neither this process nor the journal knows, and nothing is evicted. The
//! *executions* are not — every one is journaled as it goes and every open one
//! is replayed at start (PRD resolved q26–q29), which is what makes a `resume`
//! prepared against a process that died answer in the one that replaced it.
//!
//! The app is also where three of grammar 13.3's guarantees are kept, because
//! all three are properties of a request rather than of a graph: a trigger's
//! `auth:` verifying its caller, the same guard covering the resume and status
//! routes of every execution that trigger started, and the lifecycle webhooks a
//! `callback:` subscribes to — signed, allowlisted, and journaled as
//! at-least-once deliveries (PRD resolved q32–q35, `docs/durability.md` §3.7).

use crate::ir::Ir;

/// The app's source, carried in the compiler and emitted verbatim.
const SOURCE: &str = include_str!("js/serve.ts");

/// The routes the app mounts for **itself**, whatever the composition declares
/// (grammar 13.3: "generated apps expose `start`, `resume`, and `status`
/// routes").
///
/// `start` is per trigger and is the one of the three a composition names. The
/// other two are the app's own, at fixed addresses, and they are mounted
/// unconditionally — so an `http` trigger that claims one of these pairs is a
/// second declaration of a route the app already has, and the app refuses to
/// start with `FST_ERR_DUPLICATED_ROUTE` exactly as two colliding triggers make
/// it refuse.
///
/// Named here, beside the source they are mounted from, so the check that
/// refuses such a trigger (`check::triggers::routes`) and the app cannot drift
/// apart: `the_reserved_routes_are_the_ones_the_app_mounts` below reads this
/// list back out of `SOURCE`.
pub const RESERVED_ROUTES: &[(&str, &str)] = &[
    ("GET", "/executions/:id"),
    ("POST", "/executions/:id/resume"),
];

/// `src/serve.ts`.
#[must_use]
pub fn module(ir: &Ir) -> super::GeneratedFile {
    let mut contents = super::header(ir, "// ");
    contents.push_str(SOURCE);
    super::GeneratedFile {
        path: "src/serve.ts".to_string(),
        contents,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::codegen::test_support::ir_of;

    #[test]
    fn the_module_is_emitted_verbatim_under_the_header() {
        let emitted = module(&ir_of("version: \"0.1\"\n")).contents;
        assert!(emitted.starts_with("// This file was generated by agent-compose"));
        assert!(emitted.contains("export async function serve("));
        assert!(emitted.ends_with(SOURCE), "the app is emitted verbatim");
    }

    /// The three verbs PRD 5.11 names are all routed.
    #[test]
    fn the_app_routes_start_status_and_resume() {
        assert!(SOURCE.contains("app.get(\"/executions/:id\""));
        assert!(SOURCE.contains("app.post(\"/executions/:id/resume\""));
        assert!(SOURCE.contains("url: trigger.path"));
    }

    /// [`RESERVED_ROUTES`] is what the app really mounts.
    ///
    /// The compiler refuses a trigger that claims one of these pairs, and a
    /// refusal keyed to a list the app had moved on from would refuse a legal
    /// composition — or, worse, stop refusing an illegal one. So the list is
    /// read back out of the source it describes: an app that renames or drops a
    /// route fails here, at the constant, rather than at a route collision
    /// nobody expected.
    #[test]
    fn the_reserved_routes_are_the_ones_the_app_mounts() {
        let mounted: Vec<(&str, &str)> = SOURCE
            .lines()
            .filter_map(|line| {
                let rest = line.trim_start().strip_prefix("app.")?;
                let (verb, rest) = rest.split_once("(\"")?;
                let (path, _) = rest.split_once('"')?;
                match verb {
                    "get" => Some(("GET", path)),
                    "post" => Some(("POST", path)),
                    "put" => Some(("PUT", path)),
                    _ => None,
                }
            })
            .collect();
        assert_eq!(
            mounted, RESERVED_ROUTES,
            "the app mounts these fixed routes; `RESERVED_ROUTES` says it mounts {RESERVED_ROUTES:?}"
        );
    }

    /// A delivery's body is the report taken **where the event was**, not where
    /// the delivery chain reached it.
    ///
    /// `deliver` chains onto a per-execution promise and the chain ahead of it
    /// can be long — a first delivery still opening the journal while a resume
    /// lands, runs on and finishes the execution. A body serialized inside that
    /// chain would announce a `parked` event over a report reading `completed`,
    /// with no `interrupts` for the receiver to answer, where PRD resolved q34
    /// promises it the report a poll at the moment of the event would have
    /// served. The bytes are fixed at the intent and every attempt resends
    /// them, so nothing later corrects it.
    ///
    /// Read off the source because the race wants a journal open slower than a
    /// person answering two pauses, which no acceptance test can stage
    /// deterministically. What is checkable is *where* the snapshot is taken.
    #[test]
    fn a_deliverys_body_is_the_report_taken_where_the_event_was() {
        let deliver = function_body("function deliver(");
        assert!(
            deliver.contains("const body = report(execution);"),
            "`deliver` no longer snapshots the report at the event: {deliver}"
        );
        let opening = function_body("async function opening(");
        assert!(
            !opening.contains("report(execution)"),
            "`opening` builds the report inside the delivery chain again, so a delivery can \
             carry a report of a run that has moved on since its event: {opening}"
        );
    }

    /// Both callback-URL gates ask **one** question (grammar 13.3, D127).
    ///
    /// A URL is held to its trigger in two places — before the first attempt,
    /// and again when a restart puts an owed row back on its schedule — and a
    /// rule one of them enforced alone would be a rule a crash suspends. So
    /// neither matches the allowlist itself: they ask `unroutable`, which is
    /// also where the authority is required to be the one the entry matched
    /// against (`credentialed`).
    #[test]
    fn both_callback_url_gates_ask_the_same_question() {
        let unroutable = function_body("function unroutable(");
        for asked in ["credentialed(url)", "admits(trigger.callbackAllow, url)"] {
            assert!(
                unroutable.contains(asked),
                "`unroutable` no longer asks `{asked}`, so a delivery is held to less than \
                 grammar 13.3 says: {unroutable}"
            );
        }
        for gate in ["async function opening(", "async function resumeDelivery("] {
            let body = function_body(gate);
            assert!(
                body.contains("unroutable("),
                "`{gate}…` no longer holds the callback URL to its trigger"
            );
            assert!(
                !body.contains("admits("),
                "`{gate}…` matches the allowlist on its own, and the two gates drift apart \
                 the moment one of them grows a rule the other has not"
            );
        }
    }

    /// The body of one top-level declaration of the app.
    ///
    /// `codegen::journal` and `tests/trigger_auth_surface.rs` read it the same
    /// way, and for the same reason: a rule about what one function does is
    /// only a rule if it is read off that function rather than off the file
    /// around it. The module is formatted, so a top-level declaration opens at
    /// column zero and closes on a line that is exactly `}`.
    fn function_body(header: &str) -> String {
        let mut lines = SOURCE.lines().skip_while(|line| !line.starts_with(header));
        let opened = lines
            .next()
            .unwrap_or_else(|| panic!("`src/serve.ts` declares `{header}…`"));
        let mut held = String::from(opened);
        for line in lines {
            held.push('\n');
            held.push_str(line);
            if line == "}" {
                return held;
            }
        }
        panic!("`{header}…` has no closing brace in the first column")
    }
}
