//! `src/serve.ts`: the generated app for a project's `http` triggers.
//!
//! PRD 5.11's codegen note is the whole brief — "`http` → a generated Fastify
//! app wrapping the compiled graph (start / resume / status routes), reusing the
//! same generated Zod schemas for payload validation" — and this is the app.
//! What differs between two projects is the *table* it serves, which
//! [`super::trigger`] emits; the app over it is a **constant**, for the reasons
//! [`super::runtime`] is one.
//!
//! # Why Fastify is pinned exactly
//!
//! The same reason PRD 5.12 pins LangGraph exactly: what a framework does with a
//! body it cannot decode, and what status it answers with, is part of what a
//! compiled graph does — grammar 13.3 and Decision D117 both state behaviour a
//! caller observes at the route. A caret here would let a release move that with
//! no commit saying so.
//!
//! Which is also why the app does not simply *inherit* that behaviour: D117
//! states its rule over bodies rather than over media types, and the stock
//! parser set decides one of its two rows the other way — an empty body on a
//! body-bearing method is a `400` there and an execution here. The app installs
//! one parser of its own for every content type, so what a caller observes is
//! the grammar's rule rather than a framework default the pin merely freezes
//! (see `decodeBodies` in `js/serve.ts`).
//!
//! # What the app tracks, and what the journal does
//!
//! The **reports** are this process's: a status route answers `404` for an id
//! neither this process nor the journal knows, and nothing is evicted. The
//! *executions* are not — every one is journaled as it goes and every open one
//! is replayed at start (PRD resolved q26–q29), which is what makes a `resume`
//! prepared against a process that died answer in the one that replaced it.
//!
//! The app is also where three of grammar 13.3's guarantees are kept, because
//! all three are properties of a request rather than of a graph: a trigger's
//! `auth:` verifying its caller, the same guard covering the resume and status
//! routes of every execution that trigger started, and the lifecycle webhooks a
//! `callback:` subscribes to — signed, allowlisted, and journaled as
//! at-least-once deliveries (PRD resolved q32–q35, `docs/durability.md` §3.7).

use crate::ir::Ir;

/// The app's source, carried in the compiler and emitted verbatim.
const SOURCE: &str = include_str!("js/serve.ts");

/// The routes the app mounts for **itself**, whatever the composition declares
/// (grammar 13.3: "generated apps expose `start`, `resume`, and `status`
/// routes").
///
/// `start` is per trigger and is the one of the three a composition names. The
/// other two are the app's own, at fixed addresses, and they are mounted
/// unconditionally — so an `http` trigger that claims one of these pairs is a
/// second declaration of a route the app already has, and the app refuses to
/// start with `FST_ERR_DUPLICATED_ROUTE` exactly as two colliding triggers make
/// it refuse.
///
/// Named here, beside the source they are mounted from, so the check that
/// refuses such a trigger (`check::triggers::routes`) and the app cannot drift
/// apart: `the_reserved_routes_are_the_ones_the_app_mounts` below reads this
/// list back out of `SOURCE`.
pub const RESERVED_ROUTES: &[(&str, &str)] = &[
    ("GET", "/executions/:id"),
    ("POST", "/executions/:id/resume"),
];

/// `src/serve.ts`.
#[must_use]
pub fn module(ir: &Ir) -> super::GeneratedFile {
    let mut contents = super::header(ir, "// ");
    contents.push_str(SOURCE);
    super::GeneratedFile {
        path: "src/serve.ts".to_string(),
        contents,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::codegen::test_support::ir_of;

    #[test]
    fn the_module_is_emitted_verbatim_under_the_header() {
        let emitted = module(&ir_of("version: \"0.1\"\n")).contents;
        assert!(emitted.starts_with("// This file was generated by agent-compose"));
        assert!(emitted.contains("export async function serve("));
        assert!(emitted.ends_with(SOURCE), "the app is emitted verbatim");
    }

    /// The three verbs PRD 5.11 names are all routed.
    #[test]
    fn the_app_routes_start_status_and_resume() {
        assert!(SOURCE.contains("app.get(\"/executions/:id\""));
        assert!(SOURCE.contains("app.post(\"/executions/:id/resume\""));
        assert!(SOURCE.contains("url: trigger.path"));
    }

    /// [`RESERVED_ROUTES`] is what the app really mounts.
    ///
    /// The compiler refuses a trigger that claims one of these pairs, and a
    /// refusal keyed to a list the app had moved on from would refuse a legal
    /// composition — or, worse, stop refusing an illegal one. So the list is
    /// read back out of the source it describes: an app that renames or drops a
    /// route fails here, at the constant, rather than at a route collision
    /// nobody expected.
    #[test]
    fn the_reserved_routes_are_the_ones_the_app_mounts() {
        let mounted: Vec<(&str, &str)> = SOURCE
            .lines()
            .filter_map(|line| {
                let rest = line.trim_start().strip_prefix("app.")?;
                let (verb, rest) = rest.split_once("(\"")?;
                let (path, _) = rest.split_once('"')?;
                match verb {
                    "get" => Some(("GET", path)),
                    "post" => Some(("POST", path)),
                    "put" => Some(("PUT", path)),
                    _ => None,
                }
            })
            .collect();
        assert_eq!(
            mounted, RESERVED_ROUTES,
            "the app mounts these fixed routes; `RESERVED_ROUTES` says it mounts {RESERVED_ROUTES:?}"
        );
    }
}
