//! `src/serve.ts`: the generated app for a project's `http` triggers.
//!
//! PRD 5.11's codegen note is the whole brief — "`http` → a generated Fastify
//! app wrapping the compiled graph (start / resume / status routes), reusing the
//! same generated Zod schemas for payload validation" — and this is the app.
//! What differs between two projects is the *table* it serves, which
//! [`super::trigger`] emits; the app over it is a **constant**, for the reasons
//! [`super::runtime`] is one.
//!
//! # Why Fastify is pinned exactly
//!
//! The same reason PRD 5.12 pins LangGraph exactly: what a framework does with a
//! body it cannot decode, and what status it answers with, is part of what a
//! compiled graph does — grammar 13.3 and Decision D117 both state behaviour a
//! caller observes at the route. A caret here would let a release move that with
//! no commit saying so.
//!
//! Which is also why the app does not simply *inherit* that behaviour: D117
//! states its rule over bodies rather than over media types, and the stock
//! parser set decides one of its two rows the other way — an empty body on a
//! body-bearing method is a `400` there and an execution here. The app installs
//! one parser of its own for every content type, so what a caller observes is
//! the grammar's rule rather than a framework default the pin merely freezes
//! (see `decodeBodies` in `js/serve.ts`).
//!
//! # What this milestone's app does not do
//!
//! Executions are tracked **in this process**: PRD §7 puts durable execution and
//! checkpointers in M3, so a status route answers `404` for an id this process
//! did not start, and the sync-timeout upgrade of grammar 13.3 continues the same
//! in-process execution rather than resuming a checkpointed one. `resume` is
//! routed, validates that the execution exists, and then reports the one thing it
//! cannot do — an interrupt is the only thing there is to resume from, and PRD
//! §9's resolved question 4 schedules the `human` node runtime for M2.

use crate::ir::Ir;

/// The app's source, carried in the compiler and emitted verbatim.
const SOURCE: &str = include_str!("js/serve.ts");

/// `src/serve.ts`.
#[must_use]
pub fn module(ir: &Ir) -> super::GeneratedFile {
    let mut contents = super::header(ir, "// ");
    contents.push_str(SOURCE);
    super::GeneratedFile {
        path: "src/serve.ts".to_string(),
        contents,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::codegen::test_support::ir_of;

    #[test]
    fn the_module_is_emitted_verbatim_under_the_header() {
        let emitted = module(&ir_of("version: \"0.1\"\n")).contents;
        assert!(emitted.starts_with("// This file was generated by agent-compose"));
        assert!(emitted.contains("export async function serve("));
        assert!(emitted.ends_with(SOURCE), "the app is emitted verbatim");
    }

    /// The three verbs PRD 5.11 names are all routed.
    #[test]
    fn the_app_routes_start_status_and_resume() {
        assert!(SOURCE.contains("app.get(\"/executions/:id\""));
        assert!(SOURCE.contains("app.post(\"/executions/:id/resume\""));
        assert!(SOURCE.contains("url: trigger.path"));
    }
}
