//! `src/stores.ts`: the local backends every `store.*` runs on.
//!
//! [`super::graph`] emits one `StoreBinding` per `store.*` — its kind, its
//! scope, whether it declares a `metadata_schema:`, its `embed:` connection and
//! the backend the active target resolved — and this module emits what those
//! bindings *do*: the SQLite tables `kv` and `vector` live in, the directory of
//! files a `blob` is, the scope partitions, the idempotency ledger, and the
//! synthesized-tool entry point of grammar 11.5.
//!
//! It is a **constant**, for the reasons [`super::runtime`] is one: a golden
//! diff stays about the composition, and the file is real TypeScript in the
//! compiler's own tree (`src/codegen/js/stores.ts`) rather than a Rust string
//! literal.
//!
//! # Why a WebAssembly SQLite
//!
//! PRD 5.8's zero-infra guarantee is that `--target local` substitutes
//! "SQLite/local disk for every store unconditionally", and PRD §9.18 says
//! generated code carries no runtime-specific API — no `bun:` specifier, which
//! rules out `bun:sqlite`, and gate 14 of `tests/generated_code_gates.rs`
//! enforces it over the whole golden corpus. `node:sqlite` is the other obvious
//! candidate and is not portable either: Bun does not implement it (Bun 1.3
//! answers `Could not resolve: "node:sqlite"`), so an emitted project would run
//! on the fallback runtime and fail on the default one.
//!
//! `node-sqlite3-wasm` is what is left and what is pinned: one dependency, no
//! dependencies of its own, no native build and no install script — a
//! WebAssembly build of SQLite over `node:fs`, which both supported runtimes
//! resolve identically. The trade it makes is written down rather than
//! discovered: a WebAssembly SQLite is slower than a native one and has **no
//! cross-process locking**, so the local backends are single-process. That is
//! the same boundary PRD 5.10 already draws for `--target local` — one process —
//! and production backends are M3's.

use crate::ir::Ir;

/// The module's source, carried in the compiler and emitted verbatim.
const SOURCE: &str = include_str!("js/stores.ts");

/// `src/stores.ts`.
#[must_use]
pub fn module(ir: &Ir) -> super::GeneratedFile {
    let mut contents = super::header(ir, "// ");
    contents.push_str(SOURCE);
    super::GeneratedFile {
        path: "src/stores.ts".to_string(),
        contents,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::codegen::test_support::ir_of;

    #[test]
    fn the_module_is_emitted_verbatim_under_the_header() {
        let emitted = module(&ir_of("version: \"0.1\"\n")).contents;
        assert!(emitted.starts_with("// This file was generated by agent-compose"));
        assert!(emitted.contains("export async function runStoreOp("));
        assert!(
            emitted.ends_with(SOURCE),
            "the backends are emitted verbatim"
        );
    }

    /// The backends are the same bytes for every composition, like the runtime.
    #[test]
    fn every_composition_gets_the_same_backends() {
        let empty = module(&ir_of("version: \"0.1\"\n")).contents;
        let full = module(&ir_of(crate::codegen::test_support::EVERY_FORM)).contents;
        assert_eq!(empty.replace("main.yml", ""), full.replace("main.yml", ""));
    }

    /// The driver is reached by the one specifier PRD §9.18 admits, and the two
    /// this project refuses are named nowhere in it.
    #[test]
    fn the_backends_name_no_runtime_specific_sqlite() {
        assert!(SOURCE.contains("await import(\"node-sqlite3-wasm\")"));
        assert!(
            !SOURCE.contains("\"bun:sqlite\"") && !SOURCE.contains("\"node:sqlite\""),
            "a generated module may not reach for an API one supported runtime lacks (PRD §9.18)"
        );
    }
}
