// This file was generated by agent-compose 0.0.0-dev from `main.yml` (target `local`).
//
// It is a build artifact, not source: `agent-compose build` overwrites it,
// and `agent-compose build --check` fails when it has been edited. The spec
// is the single source of truth (PRD 5.12); to own this code instead, copy
// the whole directory out and stop regenerating it.
//
// What this artifact's deploy layer declares: the placements a worker may claim,
// the environment partition of `docs/distributed.md` §9.1, and the hub's own two
// keys (grammar §14.1, §14.2).
//
// The partition is emitted here rather than derived at either end because §9.1
// requires one answer under one artifact hash: the hub checks a join's `env_ok`
// against the claimed placements' lists, and the worker reads the list it is
// reporting against out of the very tree the hub served it.
//
// `hubEnvironment` is what `readEnvironment()` checks at start (`./env.ts`), and
// it is narrower than the composition's whole environment exactly when a
// placement takes something off it — the least-privilege line PRD 5.10 draws and
// §9.1 computes: the hub cannot leak what it never held.

/** One placement, and the environment a worker claiming it has to satisfy. */
export interface PlacementManifest {
  /** The name a worker claims at join (`docs/distributed.md` §3.1). */
  readonly name: string;
  /** `members:`, in the order the deploy file writes them (grammar §14.1). */
  readonly members: readonly string[];
  /**
   * The variables of every component that can execute in this placement's
   * process, sorted by name — `docs/distributed.md` §9.1's partition.
   *
   * Names only. A manifest carries no value and no site: what a join reports is
   * a subset of this list (§9.2), and a report scoped to anything wider would be
   * telling the hub about credentials that are none of its business.
   */
  readonly environment: readonly string[];
}

export const placements: readonly PlacementManifest[] = [];

export const hubEnvironment: readonly string[] = [
  "ANTHROPIC_API_KEY",
  "DEPLOY_ENV",
  "LOCAL_LLM_KEY",
  "LOCAL_LLM_URL",
  "OPS_BIN",
  "QUEUE_HOST",
  "QUEUE_TOKEN",
  "REPO_ROOT",
  "RG_CONFIG_PATH",
  "TRIAGE_HOST",
  "TRIAGE_TOKEN",
];

export const joinTokenEnv: string | undefined = "MESH_JOIN_TOKEN";

export const publicUrl: string | undefined = undefined;
