// This file was generated by agent-compose 0.0.0-dev from `main.yml` (target `local`).
//
// It is a build artifact, not source: `agent-compose build` overwrites it,
// and `agent-compose build --check` fails when it has been edited. The spec
// is the single source of truth (PRD 5.12); to own this code instead, copy
// the whole directory out and stop regenerating it.
//
// The generated half of every `module:` binding (grammar 6.1, PRD resolved q48).
//
// One exported type per module-bound tool — its contract, written from the
// tool's own `input:` and `output:` — and one typed `const` beside it holding
// the authored implementation. `src/graph.ts` dispatches through those consts.
//
// This is the **only** generated module that imports authored code. The rule
// runs one way: authored files may import anything this project generates, and
// generated code reaches them here or nowhere.

// This composition binds no `module:` implementation, so there is nothing to
// import and nothing to expose. The file is still emitted, because the emitted
// file list is a constant of the compiler rather than of the composition.
export {};
