// This file was generated by agent-compose 0.1.0 from `main.yml` (target `local`).
//
// It is a build artifact, not source: `agent-compose build` overwrites it,
// and `agent-compose build --check` fails when it has been edited. The spec
// is the single source of truth (PRD 5.12); to own this code instead, copy
// the whole directory out and stop regenerating it.
//
// Every schema the composition declares, lowered per grammar 3.8. These are the
// runtime contract: an agent's output is parsed with the schema named for it
// before any edge is evaluated, a tool's arguments are parsed with its input
// schema, and a state channel's type is the schema its channel is built from.

import { z } from "zod";

/** `agent.fixer` — its declared input (grammar 5.3). */
export const agentFixerInput = z.object({
  file: z.string(),
  patch_hint: z.string(),
}).strict();
export type AgentFixerInput = z.infer<typeof agentFixerInput>;

/**
 * `agent.fixer` — the structured output the model is constrained to, and what routing reads (PRD 5.2, 5.3).
 */
export const agentFixerOutput = z.object({
  patch: z.string().describe("A unified diff."),
  explanation: z.string().describe("One sentence describing the change."),
}).strict();
export type AgentFixerOutput = z.infer<typeof agentFixerOutput>;

/** `agent.summarizer` — its declared input (grammar 5.3). */
export const agentSummarizerInput = z.object({
  report: z.string(),
  patches: z.array(z.string()),
}).strict();
export type AgentSummarizerInput = z.infer<typeof agentSummarizerInput>;

/**
 * `agent.summarizer` — the structured output the model is constrained to, and what routing reads (PRD 5.2, 5.3).
 */
export const agentSummarizerOutput = z.object({
  summary: z.string().min(1).describe("The run summary shown to the human reviewer."),
}).strict();
export type AgentSummarizerOutput = z.infer<typeof agentSummarizerOutput>;

/** `agent.triage` — its declared input (grammar 5.3). */
export const agentTriageInput = z.object({
  report: z.string().describe("The raw bug report."),
  matches: z.array(z.string()).describe("Grep hits from the repository, for grounding."),
}).strict();
export type AgentTriageInput = z.infer<typeof agentTriageInput>;

/**
 * `agent.triage` — the structured output the model is constrained to, and what routing reads (PRD 5.2, 5.3).
 */
export const agentTriageOutput = z.object({
  findings: z.array(z.discriminatedUnion("kind", [
    z.object({
      kind: z.literal("auto_fixable"),
      file: z.string(),
      patch_hint: z.string(),
    }).strict(),
    z.object({
      kind: z.literal("needs_human"),
      summary: z.string(),
      severity: z.enum(["low", "high", "critical"]),
    }).strict(),
    z.object({
      kind: z.literal("duplicate"),
      of: z.string(),
    }).strict(),
  ])).max(50).describe("Every distinct defect, tagged for routing."),
}).strict();
export type AgentTriageOutput = z.infer<typeof agentTriageOutput>;

/** `flow.enrich` — the module's parameters (grammar 7.5). */
export const flowEnrichInputs = z.object({
  report: z.string(),
}).strict();
export type FlowEnrichInputs = z.infer<typeof flowEnrichInputs>;

/**
 * `flow.enrich` — the module's result, materialized from the state channels of the same names at quiescence (grammar 7.5, 7.6.3).
 */
export const flowEnrichOutputs = z.object({
  report_normalized: z.string(),
}).strict();
export type FlowEnrichOutputs = z.infer<typeof flowEnrichOutputs>;

/** `flow.enrich` node `fetch` — what the response decodes to (grammar 8.3). */
export const flowEnrichNodeFetchOutput = z.object({
  report_normalized: z.string(),
}).strict();
export type FlowEnrichNodeFetchOutput = z.infer<typeof flowEnrichNodeFetchOutput>;

/** `flow.triage` — the module's parameters (grammar 7.5). */
export const flowTriageInputs = z.object({
  report: z.string().min(1).describe("The raw bug report."),
  pattern: z.string().describe("Repository search pattern used to ground the triage agent."),
}).strict();
export type FlowTriageInputs = z.infer<typeof flowTriageInputs>;

/**
 * `flow.triage` — the module's result, materialized from the state channels of the same names at quiescence (grammar 7.5, 7.6.3).
 */
export const flowTriageOutputs = z.object({
  summary: z.string(),
  patches: z.array(z.string()).max(200),
}).strict();
export type FlowTriageOutputs = z.infer<typeof flowTriageOutputs>;

/**
 * `flow.triage` node `announce` — what the response decodes to (grammar 8.3).
 */
export const flowTriageNodeAnnounceOutput = z.object({
  status: z.number().int(),
}).strict();
export type FlowTriageNodeAnnounceOutput = z.infer<typeof flowTriageNodeAnnounceOutput>;

/** `flow.triage` node `verify` — what the subprocess produces (grammar 8.2). */
export const flowTriageNodeVerifyOutput = z.object({
  exit_code: z.number().int(),
  stdout: z.string(),
}).strict();
export type FlowTriageNodeVerifyOutput = z.infer<typeof flowTriageNodeVerifyOutput>;

/** `flow.triage` node `approve` — what the human is shown (grammar 8.7). */
export const flowTriageNodeApproveInput = z.object({
  summary: z.string(),
  patch_count: z.number().int(),
}).strict();
export type FlowTriageNodeApproveInput = z.infer<typeof flowTriageNodeApproveInput>;

/**
 * `flow.triage` node `approve` — what the human returns, routable like any structured output (grammar 8.7).
 */
export const flowTriageNodeApproveOutput = z.object({
  decision: z.enum(["approve", "reject"]),
  note: z.string(),
}).strict();
export type FlowTriageNodeApproveOutput = z.infer<typeof flowTriageNodeApproveOutput>;

/**
 * `flow.triage` node `escalate` — what the response decodes to (grammar 8.3).
 */
export const flowTriageNodeEscalateOutput = z.object({
  status: z.number().int(),
}).strict();
export type FlowTriageNodeEscalateOutput = z.infer<typeof flowTriageNodeEscalateOutput>;

/** `store.docs` — the metadata a match carries (grammar 11.1). */
export const storeDocsMetadataSchema = z.object({
  source: z.string(),
  updated_at: z.iso.datetime({ offset: true }),
}).strict();
export type StoreDocsMetadataSchema = z.infer<typeof storeDocsMetadataSchema>;

/** `store.triage_memory` — the value it stores (grammar 11.1). */
export const storeTriageMemoryValueSchema = z.object({
  last_report: z.string().describe("The most recent report triaged in this session."),
  patch_count: z.number().int().min(0).describe("How many patches the last run produced."),
}).strict();
export type StoreTriageMemoryValueSchema = z.infer<typeof storeTriageMemoryValueSchema>;

/** `tool.dead_letter` — its parameters (grammar 6). */
export const toolDeadLetterInput = z.object({
  kind: z.string(),
  payload: z.string(),
}).strict();
export type ToolDeadLetterInput = z.infer<typeof toolDeadLetterInput>;

/** `tool.dead_letter` — its result (grammar 6). */
export const toolDeadLetterOutput = z.object({
  accepted: z.boolean(),
}).strict();
export type ToolDeadLetterOutput = z.infer<typeof toolDeadLetterOutput>;

/** `tool.repo_grep` — its parameters (grammar 6). */
export const toolRepoGrepInput = z.object({
  pattern: z.string().min(1).describe("An RE2 regular expression."),
  max_matches: z.number().int().min(1).max(200).default(50),
}).strict();
export type ToolRepoGrepInput = z.infer<typeof toolRepoGrepInput>;

/** `tool.repo_grep` — its result (grammar 6). */
export const toolRepoGrepOutput = z.object({
  matches: z.array(z.string()).max(200).describe("Matching lines, formatted as path:line:text."),
}).strict();
export type ToolRepoGrepOutput = z.infer<typeof toolRepoGrepOutput>;

/** `tool.review_queue` — its parameters (grammar 6). */
export const toolReviewQueueInput = z.object({
  summary: z.string(),
  severity: z.enum(["low", "high", "critical"]),
}).strict();
export type ToolReviewQueueInput = z.infer<typeof toolReviewQueueInput>;

/** `tool.review_queue` — its result (grammar 6). */
export const toolReviewQueueOutput = z.object({
  ticket_id: z.string(),
  queued: z.boolean(),
}).strict();
export type ToolReviewQueueOutput = z.infer<typeof toolReviewQueueOutput>;

/** State channel `human_decision` — its declared type (grammar 10.1). */
export const stateHumanDecision = z.enum(["approve", "reject"]).describe("What the reviewer decided about the run as a whole.").default("approve");
export type StateHumanDecision = z.infer<typeof stateHumanDecision>;

/** State channel `matches` — its declared type (grammar 10.1). */
export const stateMatches = z.array(z.string()).describe("Raw grep hits handed to the triage agent.");
export type StateMatches = z.infer<typeof stateMatches>;

/** State channel `patches` — its declared type (grammar 10.1). */
export const statePatches = z.array(z.string()).max(200).describe("Patches produced by the fixer instances.");
export type StatePatches = z.infer<typeof statePatches>;

/** State channel `report_normalized` — its declared type (grammar 10.1). */
export const stateReportNormalized = z.string().describe("The report after flow.enrich has normalized it.").default("");
export type StateReportNormalized = z.infer<typeof stateReportNormalized>;

/** State channel `summary` — its declared type (grammar 10.1). */
export const stateSummary = z.string().describe("Human-readable summary of the triage run.").default("");
export type StateSummary = z.infer<typeof stateSummary>;
