// This file was generated by agent-compose 0.1.0 from `main.yml` (target `local`).
//
// It is a build artifact, not source: `agent-compose build` overwrites it,
// and `agent-compose build --check` fails when it has been edited. The spec
// is the single source of truth (PRD 5.12); to own this code instead, copy
// the whole directory out and stop regenerating it.
//
// The graph's state model (PRD 5.7 tier 2, grammar 10). Each declared `state:`
// channel is one LangGraph channel typed by its schema in `./schemas.ts`, with
// the reducer its `reduce:` policy names and the initial value its `default:`
// names. `messages` is the implicit conversation history of grammar 10.4, which
// a composition never declares and every graph has.

import { Annotation, MessagesAnnotation } from "@langchain/langgraph";
import type { z } from "zod";

import {
  stateHumanDecision,
  stateMatches,
  statePatches,
  stateReportNormalized,
  stateSummary,
} from "./schemas.ts";

/**
 * Every channel of the graph's state, keyed by the name a write targets
 * (grammar 10.3's name-based wiring).
 */
export const channels = {
  /**
   * What the reviewer decided about the run as a whole.
   *
   * Unreduced: single-writer, and a write supplies the whole value.
   * Starts at `"approve"`.
   */
  human_decision: Annotation<z.infer<typeof stateHumanDecision>>({
    reducer: (_left, right) => right,
    default: () => "approve",
  }),
  /**
   * Raw grep hits handed to the triage agent.
   *
   * Unreduced: single-writer, and a write supplies the whole value.
   * Starts **unset**: reading it before its first write fails the execution (Decision D78).
   */
  matches: Annotation<z.infer<typeof stateMatches>>,
  /**
   * Patches produced by the fixer instances.
   *
   * `reduce: append`: a write supplies **one element**, appended in canonical write order (grammar 7.6.4, Decision D58).
   * Starts at `[]`.
   */
  patches: Annotation<z.infer<typeof statePatches>, z.infer<typeof statePatches>[number]>({
    reducer: (left, right) => left.concat([right]),
    default: () => [],
  }),
  /**
   * The report after flow.enrich has normalized it.
   *
   * Unreduced: single-writer, and a write supplies the whole value.
   * Starts at `""`.
   */
  report_normalized: Annotation<z.infer<typeof stateReportNormalized>>({
    reducer: (_left, right) => right,
    default: () => "",
  }),
  /**
   * Human-readable summary of the triage run.
   *
   * Unreduced: single-writer, and a write supplies the whole value.
   * Starts at `""`.
   */
  summary: Annotation<z.infer<typeof stateSummary>>({
    reducer: (_left, right) => right,
    default: () => "",
  }),
  /**
   * The implicit conversation history (grammar 10.4, PRD 5.7 tier 3): append-only,
   * never declared in `state:`, and isolated across flow boundaries by default.
   */
  messages: MessagesAnnotation.spec.messages,
};

/** The state schema the graph is built from. */
export const State = Annotation.Root(channels);

/** What a node reads: every channel, at its declared type. */
export type GraphState = typeof State.State;

/** What a node writes: any subset of the channels, at their update types. */
export type GraphStateUpdate = typeof State.Update;
