// This file was generated by agent-compose 0.0.0-dev from `main.yml` (target `mesh`).
//
// It is a build artifact, not source: `agent-compose build` overwrites it,
// and `agent-compose build --check` fails when it has been edited. The spec
// is the single source of truth (PRD 5.12); to own this code instead, copy
// the whole directory out and stop regenerating it.
//
// Every schema the composition declares, lowered per grammar 3.8. These are the
// runtime contract: an agent's output is parsed with the schema named for it
// before any edge is evaluated, a tool's arguments are parsed with its input
// schema, and a state channel's type is the schema its channel is built from.

import { z } from "zod";

/**
 * The length `min_length` and `max_length` bound (grammar 3.4).
 *
 * JSON Schema counts a string's length in Unicode **code points**, and
 * `String.prototype.length` — which `.min()` and `.max()` count — is UTF-16
 * **code units**. Every character outside the BMP is one of the first and two of
 * the second, so the two disagree in both directions on any string carrying one:
 * `"😀"` is one code point and two units. Spreading a string iterates it by code
 * point, which is the rule the schema this composition published states.
 */
const codePoints = (value: string): number => [...value].length;

/** `agent.signer` — its declared input (grammar 5.3). */
export const agentSignerInput = z.object({
  path: z.string(),
}).strict();
export type AgentSignerInput = z.infer<typeof agentSignerInput>;

/**
 * `agent.signer` — the structured output the model is constrained to, and what routing reads (PRD 5.2, 5.3).
 */
export const agentSignerOutput = z.object({
  signature: z.string().refine((value) => codePoints(value) >= 1, { message: "expected at least 1 character" }),
}).strict();
export type AgentSignerOutput = z.infer<typeof agentSignerOutput>;

/** `flow.batch` — the module's parameters (grammar 7.5). */
export const flowBatchInputs = z.object({
  paths: z.array(z.string()).max(4),
}).strict();
export type FlowBatchInputs = z.infer<typeof flowBatchInputs>;

/**
 * `flow.batch` — the module's result, materialized from the state channels of the same names at quiescence (grammar 7.5, 7.6.3).
 */
export const flowBatchOutputs = z.object({
  signatures: z.array(z.string()).max(8),
}).strict();
export type FlowBatchOutputs = z.infer<typeof flowBatchOutputs>;

/** `flow.direct` — the module's parameters (grammar 7.5). */
export const flowDirectInputs = z.object({
  path: z.string().refine((value) => codePoints(value) >= 1, { message: "expected at least 1 character" }),
}).strict();
export type FlowDirectInputs = z.infer<typeof flowDirectInputs>;

/**
 * `flow.direct` — the module's result, materialized from the state channels of the same names at quiescence (grammar 7.5, 7.6.3).
 */
export const flowDirectOutputs = z.object({
  signature: z.string(),
}).strict();
export type FlowDirectOutputs = z.infer<typeof flowDirectOutputs>;

/** `flow.release` — the module's parameters (grammar 7.5). */
export const flowReleaseInputs = z.object({
  path: z.string().refine((value) => codePoints(value) >= 1, { message: "expected at least 1 character" }),
}).strict();
export type FlowReleaseInputs = z.infer<typeof flowReleaseInputs>;

/**
 * `flow.release` — the module's result, materialized from the state channels of the same names at quiescence (grammar 7.5, 7.6.3).
 */
export const flowReleaseOutputs = z.object({
  signature: z.string(),
  ticket: z.string(),
}).strict();
export type FlowReleaseOutputs = z.infer<typeof flowReleaseOutputs>;

/** `flow.retried` — the module's parameters (grammar 7.5). */
export const flowRetriedInputs = z.object({
  path: z.string().refine((value) => codePoints(value) >= 1, { message: "expected at least 1 character" }),
}).strict();
export type FlowRetriedInputs = z.infer<typeof flowRetriedInputs>;

/**
 * `flow.retried` — the module's result, materialized from the state channels of the same names at quiescence (grammar 7.5, 7.6.3).
 */
export const flowRetriedOutputs = z.object({
  signature: z.string(),
}).strict();
export type FlowRetriedOutputs = z.infer<typeof flowRetriedOutputs>;

/** `tool.notarize` — its parameters (grammar 6). */
export const toolNotarizeInput = z.object({
  path: z.string(),
}).strict();
export type ToolNotarizeInput = z.infer<typeof toolNotarizeInput>;

/** `tool.notarize` — its result (grammar 6). */
export const toolNotarizeOutput = z.object({
  ticket: z.string(),
}).strict();
export type ToolNotarizeOutput = z.infer<typeof toolNotarizeOutput>;

/** `tool.sign` — its parameters (grammar 6). */
export const toolSignInput = z.object({
  path: z.string(),
}).strict();
export type ToolSignInput = z.infer<typeof toolSignInput>;

/** `tool.sign` — its result (grammar 6). */
export const toolSignOutput = z.object({
  signature: z.string(),
}).strict();
export type ToolSignOutput = z.infer<typeof toolSignOutput>;

/** State channel `signature` — its declared type (grammar 10.1). */
export const stateSignature = z.string().describe("What the worker signed, as it came back over the wire.").default("");
export type StateSignature = z.infer<typeof stateSignature>;

/** State channel `signatures` — its declared type (grammar 10.1). */
export const stateSignatures = z.array(z.string()).max(8).describe("One entry per dispatched item, in source-item order.");
export type StateSignatures = z.infer<typeof stateSignatures>;

/** State channel `ticket` — its declared type (grammar 10.1). */
export const stateTicket = z.string().describe("What the hub's own node produced, in the same execution.").default("");
export type StateTicket = z.infer<typeof stateTicket>;
