// This file was generated by agent-compose 0.0.0-dev from `main.yml` (target `local`).
//
// It is a build artifact, not source: `agent-compose build` overwrites it,
// and `agent-compose build --check` fails when it has been edited. The spec
// is the single source of truth (PRD 5.12); to own this code instead, copy
// the whole directory out and stop regenerating it.

import * as runtime from "./runtime.ts";
import { query } from "@anthropic-ai/claude-agent-sdk";
import type {
  Options,
  PermissionMode,
  SDKMessage,
} from "@anthropic-ai/claude-agent-sdk";
import { Codex } from "@openai/codex-sdk";
import type {
  SandboxMode,
  ThreadItem,
  ThreadOptions,
} from "@openai/codex-sdk";
//
// The driver seam (grammar 8.9, PRD resolved q57).
//
// `src/runtime.ts` holds the **adapter** — the config map, the journal, the
// stream tap and the output gate — and this file holds the other side of the
// seam it drives: one `runtime.HarnessDriver` per harness this composition
// binds, each a thin mapping over the vendor's own SDK, plus a scripted driver
// that maps over nothing at all.
//
// Three properties are the reason the seam exists, and each is enforced by this
// file being generated rather than shipped:
//
//  * **only what this composition uses.** A driver is emitted for a harness some
//    `coder:` node binds and for no other, so a project with no coder node
//    imports no SDK — and the pins in `package.json` follow the same rule
//    (`codegen::project`). `src/runtime.ts` is byte-identical in every project a
//    release builds, and an SDK import inside it would break that.
//  * **nothing but a mapping.** A driver journals nothing, parses nothing and
//    records nothing: it turns a `runtime.HarnessRun` into the SDK's own call,
//    and the SDK's own events into `runtime.HarnessEvent`s. Every rule about
//    effects, replay, containment and the trace lives one level up, so the
//    shipped drivers and the scripted one are held to the same rules by
//    construction rather than by three copies of them.
//  * **a test surface that runs.** A harness SDK speaks its own wire, so the
//    mock provider — deliberately — never sees it: there is nothing for a test
//    to point a compiled graph at. `scriptedDriver` is what a test drives
//    instead, and it is emitted into every project so that a golden's own
//    `src/harness.ts` is the file under test.
//
// # What a driver may read off an event, and what it may not
//
// The **top level only**. `HarnessEvent.tap` is what reaches the trace envelope,
// and PRD resolved q57 ruling a fixes its depth: a harness that runs subagents
// of its own yields their turns and their tool calls too, and those stay in
// `HarnessEvent.source` — the journal's private payload — where every other
// tool's answer already is. Each driver below says where it reads that boundary
// off its own SDK's events.

/**
 * A driver whose whole behaviour is a script (PRD resolved q57).
 *
 * The test surface, and it is emitted into every project rather than into the
 * ones a test happens to use: a runtime behaviour test drives a **golden's own**
 * `src/harness.ts`, so the scripted driver has to be in the file under test for
 * the thing under test to be the emitted adapter rather than a copy of it.
 *
 * It records every `runtime.HarnessRun` it is handed, which is how a test says
 * anything about the **config map** — that a workspace resolved its `${ENV}`,
 * that an environment was scrubbed, that the schema was projected through this
 * harness's lowering table — none of which is visible from the answer.
 */
export interface ScriptedHarness {
  /** The driver to hand `runtime.runCoder`. */
  readonly driver: runtime.HarnessDriver;
  /** Every run it was handed, in the order it was handed them. */
  readonly runs: runtime.HarnessRun[];
}

/**
 * Build one.
 *
 * `script` is the events one run yields, or a function of the run — the second
 * form for a test whose answer depends on what it was asked, which is the shape
 * a `retry:` test needs: the first attempt's events and the second's differ.
 */
export function scriptedDriver(
  harness: runtime.HarnessName,
  script:
    | readonly runtime.HarnessEvent[]
    | ((run: runtime.HarnessRun, attempt: number) => readonly runtime.HarnessEvent[]),
): ScriptedHarness {
  const runs: runtime.HarnessRun[] = [];
  const driver: runtime.HarnessDriver = {
    sdk: `agent-compose:scripted/${harness}`,
    version: "0",
    // A scripted driver claims the enforcement of the harness it stands in for,
    // so a test reading `enforcesTools` off it reads the real answer.
    enforcesTools: harness === "cc",
    run(run: runtime.HarnessRun): AsyncIterable<runtime.HarnessEvent> {
      runs.push(run);
      const attempt = runs.length;
      const events = typeof script === "function" ? script(run, attempt) : script;
      return (async function* yielded(): AsyncGenerator<runtime.HarnessEvent> {
        for (const event of events) {
          // The node's deadline still ends a scripted run, which is what makes
          // a `timeout:` test possible at all (grammar 9.2).
          run.signal.throwIfAborted();
          yield event;
        }
      })();
    },
  };
  return { driver, runs };
}

/**
 * The harness config one run sends, with the two tiers merged in the order
 * Decision D140 fixes.
 *
 * The **unverified keys travel unchanged**, which is q30's treadmill posture
 * applied one construct along: a harness option the vendor ships tomorrow is
 * usable the day it ships, and `validate` says out loud that it could not verify
 * it. The keys this compiler *does* know are mapped by name in each driver
 * below, over the top, so a curated key and an unknown one spelling the same SDK
 * option cannot disagree about which wins.
 */
function passthrough(
  run: runtime.HarnessRun,
  curated: readonly string[],
): Record<string, unknown> {
  const held: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(run.settings)) {
    if (curated.includes(key)) continue;
    held[key] = value;
  }
  return held;
}

/** One `AbortController` that follows a run's signal, for an SDK that takes one. */
function controllerFor(signal: AbortSignal): AbortController {
  const controller = new AbortController();
  if (signal.aborted) controller.abort(signal.reason);
  else signal.addEventListener("abort", () => controller.abort(signal.reason), { once: true });
  return controller;
}

/** A number a settings value holds, or `undefined` where it holds something else. */
function settingNumber(value: unknown): number | undefined {
  return typeof value === "number" && Number.isFinite(value) ? value : undefined;
}

/** …a string, under the same rule. */
function settingText(value: unknown): string | undefined {
  return typeof value === "string" && value !== "" ? value : undefined;
}

/** …a boolean. */
function settingFlag(value: unknown): boolean | undefined {
  return typeof value === "boolean" ? value : undefined;
}

/** …and a list of strings. */
function settingList(value: unknown): string[] | undefined {
  if (!Array.isArray(value)) return undefined;
  const held = value.filter((entry): entry is string => typeof entry === "string");
  return held.length === value.length ? held : undefined;
}

/**
 * The `cc` SDK version this compiler release pins — the number `package.json` declares and the number a `HarnessRecord` reports.
 */
const CC_SDK_VERSION: string = "0.3.272";

/**
 * The keys of a `cc` node's `settings:` this compiler release maps by name
 * (Decision D140's first tier).
 *
 * Everything else travels to `query`'s options unchanged, under the warning
 * `validate` printed for it. Both halves are deliberate: a gating table is the
 * treadmill PRD resolved q30 refused, and a key with a *meaning* — a turn bound,
 * a budget — is worth checking before a run rather than after a 400.
 */
const CC_SETTINGS: readonly string[] = [
  "max_turns",
  "max_budget_usd",
  "forward_subagent_text",
  "disallowed_tools",
];

/**
 * How `access:` reaches the Agent SDK (grammar 8.9, Decision D138).
 *
 * The SDK's containment primitive is a permission *mode* plus a working
 * directory, so the preset selects the mode and `cwd` carries the root:
 *
 *  * `read_only` → `plan`, which the SDK documents as planning mode with no
 *    execution of tools — the strongest read-only statement its own surface
 *    makes;
 *  * `workspace_write` → `acceptEdits`, which auto-accepts edits under the
 *    working directory and still asks about everything else;
 *  * `full_access` → `bypassPermissions`, with the flag the SDK requires beside
 *    it, which is the preset that asks for no containment at all.
 */
const CC_PERMISSION: Readonly<Record<runtime.WorkspaceAccess, PermissionMode>> = {
  read_only: "plan",
  workspace_write: "acceptEdits",
  full_access: "bypassPermissions",
};

/**
 * The `cc` driver: a thin mapping over the Claude Agent SDK.
 *
 * # Where the top level is
 *
 * `parent_tool_use_id === null`. Every message the SDK yields carries it, and a
 * message produced *inside* a subagent carries that subagent's tool-use id — so
 * the one predicate is the whole of PRD resolved q57 ruling a's depth rule: a
 * subagent's turns and tool calls are yielded with no `tap` and reach the
 * journal payload only.
 *
 * # What enforces the allowlist
 *
 * `canUseTool`, per call, inside the loop. `allowedTools` is set beside it
 * because it is what the SDK offers the model in the first place, and the
 * callback is what makes the list a **bound** rather than an offer: a call
 * outside it is denied with a message the model reads, and the denial is taped
 * as a `"refused"` tool event so the trace says the bound bit.
 *
 * # What is asked for, and what is parsed
 *
 * `outputFormat: { type: "json_schema" }` carrying the schema the adapter
 * already projected through this harness's lowering table, and the answer
 * arrives as the result message's `structured_output`. The adapter parses it
 * against the **full** declared schema, which is where PRD resolved q55's
 * amendment to q16 lives.
 */
const CC_DRIVER: runtime.HarnessDriver = {
  sdk: "@anthropic-ai/claude-agent-sdk",
  version: CC_SDK_VERSION,
  enforcesTools: true,
  run(run: runtime.HarnessRun): AsyncIterable<runtime.HarnessEvent> {
    return (async function* driven(): AsyncGenerator<runtime.HarnessEvent> {
      const controller = controllerFor(run.signal);
      // What the permission callback refused, drained into the stream between
      // messages: `canUseTool` answers the SDK rather than this generator, so a
      // queue is how a denial becomes a tool event in the order it happened.
      const refusals: runtime.HarnessEvent[] = [];
      // The name each top-level `tool_use` went out under, so the `tool_result`
      // that answers it can be taped under the same name.
      const calls = new Map<string, string>();

      const options: Options = {
        cwd: run.workspace,
        systemPrompt: run.instructions,
        model: run.model,
        permissionMode: CC_PERMISSION[run.access],
        abortController: controller,
        env: { ...run.env },
        outputFormat: { type: "json_schema", schema: { ...run.schema } },
        ...passthrough(run, CC_SETTINGS),
      };
      if (run.access === "full_access") options.allowDangerouslySkipPermissions = true;
      // The one `model.*` setting this harness has a place for: the `anthropic`
      // plugin's `thinking: { budget_tokens: … }` is the SDK's
      // `maxThinkingTokens` (Decision D141).
      const thinking = run.modelSettings["thinking"];
      const budgetTokens =
        typeof thinking === "object" && thinking !== null
          ? settingNumber((thinking as Record<string, unknown>)["budget_tokens"])
          : undefined;
      if (budgetTokens !== undefined) options.maxThinkingTokens = budgetTokens;
      const maxTurns = settingNumber(run.settings["max_turns"]);
      if (maxTurns !== undefined) options.maxTurns = maxTurns;
      const budget = settingNumber(run.settings["max_budget_usd"]);
      if (budget !== undefined) options.maxBudgetUsd = budget;
      const forward = settingFlag(run.settings["forward_subagent_text"]);
      if (forward !== undefined) options.forwardSubagentText = forward;
      const disallowed = settingList(run.settings["disallowed_tools"]);
      if (disallowed !== undefined) options.disallowedTools = disallowed;
      const allowed = run.allowTools;
      if (allowed !== undefined) {
        options.allowedTools = [...allowed];
        options.canUseTool = (name: string) => {
          if (allowed.includes(name)) return Promise.resolve({ behavior: "allow" as const });
          const message = `\`${run.node}\` allows ${allowed.map((tool) => `\`${tool}\``).join(", ")}, and \`${name}\` is not one of them`;
          refusals.push({
            source: { type: "agent-compose.permission_denied", tool: name, message },
            tap: { kind: "tool", name, outcome: "refused", error: message },
          });
          return Promise.resolve({ behavior: "deny" as const, message });
        };
      }

      for await (const message of query({ prompt: run.input, options })) {
        while (refusals.length > 0) yield refusals.shift() as runtime.HarnessEvent;
        yield* ccEvents(message, calls);
      }
      while (refusals.length > 0) yield refusals.shift() as runtime.HarnessEvent;
    })();
  },
};

/** One SDK message, as the events the tap reads (see [`CC_DRIVER`]). */
function* ccEvents(
  message: SDKMessage,
  calls: Map<string, string>,
): Generator<runtime.HarnessEvent> {
  // A message from inside a subagent is payload and nothing else — the depth
  // rule PRD resolved q57 ruling a fixes, read off the one field that carries
  // it.
  const nested =
    "parent_tool_use_id" in message && (message as { parent_tool_use_id: unknown }).parent_tool_use_id !== null;
  if (nested) {
    yield { source: message };
    return;
  }
  if (message.type === "assistant") {
    const blocks = Array.isArray(message.message.content) ? message.message.content : [];
    for (const block of blocks) {
      if (block.type === "tool_use") calls.set(block.id, block.name);
    }
    yield { source: message, tap: { kind: "turn" } };
    return;
  }
  if (message.type === "user") {
    const blocks = Array.isArray(message.message.content) ? message.message.content : [];
    yield { source: message };
    for (const block of blocks) {
      if (block.type !== "tool_result") continue;
      const name = calls.get(block.tool_use_id);
      if (name === undefined) continue;
      const failed = block.is_error === true;
      yield {
        source: { type: "agent-compose.tool_result", tool: name, is_error: failed },
        tap: {
          kind: "tool",
          name,
          outcome: failed ? "failed" : "completed",
          ...(failed ? { error: `the tool result came back as an error` } : {}),
        },
      };
    }
    return;
  }
  if (message.type === "result") {
    const usage = message.usage as { input_tokens?: number; output_tokens?: number };
    yield {
      source: message,
      tap: {
        kind: "settled",
        cost: {
          ...(typeof usage.input_tokens === "number" ? { inputTokens: usage.input_tokens } : {}),
          ...(typeof usage.output_tokens === "number" ? { outputTokens: usage.output_tokens } : {}),
          ...(typeof message.total_cost_usd === "number" ? { usd: message.total_cost_usd } : {}),
        },
        // The two facts `codex` has no shape for: which of the SDK's result
        // subtypes this was, and the stop reason underneath it.
        extra: { subtype: message.subtype, stopReason: message.stop_reason },
      },
    };
    if (message.subtype !== "success") {
      yield {
        source: { type: "agent-compose.result_error", subtype: message.subtype },
        tap: { kind: "error", message: `the run ended \`${message.subtype}\`` },
      };
      return;
    }
    if (message.structured_output !== undefined) {
      yield {
        source: { type: "agent-compose.structured_output" },
        tap: { kind: "output", value: message.structured_output },
      };
    }
    return;
  }
  yield { source: message };
}

/**
 * The `codex` SDK version this compiler release pins — the number `package.json` declares and the number a `HarnessRecord` reports.
 */
const CODEX_SDK_VERSION: string = "0.154.0";

/**
 * The keys of a `codex` node's `settings:` this compiler release maps by name
 * (Decision D140's first tier).
 *
 * Everything else travels to the thread's options unchanged, under the warning
 * `validate` printed for it — PRD resolved q30's terms, one construct along.
 */
const CODEX_SETTINGS: readonly string[] = [
  "network_access",
  "web_search",
  "skip_git_repo_check",
  "additional_directories",
];

/**
 * How `access:` reaches the Codex SDK (grammar 8.9, Decision D138).
 *
 * One-to-one with its own sandbox presets, which is why this grammar's three
 * names are the three they are: `codex` is the harness whose containment
 * primitive is named, and a vocabulary that did not line up with it would be a
 * translation nobody could check.
 */
const CODEX_SANDBOX: Readonly<Record<runtime.WorkspaceAccess, SandboxMode>> = {
  read_only: "read-only",
  workspace_write: "workspace-write",
  full_access: "danger-full-access",
};

/**
 * The `codex` driver: a thin mapping over the Codex SDK.
 *
 * # Where the top level is
 *
 * Everywhere. `runStreamed` yields one thread's events, and a Codex thread has
 * no nesting for PRD resolved q57 ruling a's depth rule to cut at: what its
 * `mcp_tool_call` items reach is another process's, not a subagent of this run.
 * So every turn and every tool item this stream carries is a top-level one, and
 * the ruling's boundary is satisfied by there being nothing below it.
 *
 * # What bounds a run, and what does not
 *
 * The **sandbox**, and nothing else. `allowTools` is carried into the run and is
 * not enforced here: the Codex SDK's per-call approval tier is their app
 * server's, which this release does not adopt, so `enforcesTools` is `false` and
 * `docs/grammar.md` 8.9 states the asymmetry where an author writes the list.
 * The `codex` half of PRD resolved q57 ruling c is this constant.
 *
 * # What is asked for, and what is parsed
 *
 * `outputSchema`, carrying the schema the adapter already projected through this
 * harness's lowering table; the answer arrives as the last `agent_message`
 * item's text, which the SDK documents as JSON when a schema was asked for. The
 * adapter parses it against the **full** declared schema (PRD resolved q55).
 */
const CODEX_DRIVER: runtime.HarnessDriver = {
  sdk: "@openai/codex-sdk",
  version: CODEX_SDK_VERSION,
  enforcesTools: false,
  run(run: runtime.HarnessRun): AsyncIterable<runtime.HarnessEvent> {
    return (async function* driven(): AsyncGenerator<runtime.HarnessEvent> {
      // The environment is handed to the SDK rather than inherited by it: the
      // Codex SDK documents that a provided `env` replaces `process.env` for the
      // CLI it spawns, which is exactly the scrubbed child PRD resolved q54
      // ruling b asks for (Decision D139).
      const codex = new Codex({ env: { ...run.env } });
      const options: ThreadOptions = {
        model: run.model,
        workingDirectory: run.workspace,
        sandboxMode: CODEX_SANDBOX[run.access],
        ...passthrough(run, CODEX_SETTINGS),
      };
      const effort = settingText(run.modelSettings["reasoning_effort"]);
      if (effort !== undefined) {
        options.modelReasoningEffort = effort as ThreadOptions["modelReasoningEffort"];
      }
      const network = settingFlag(run.settings["network_access"]);
      if (network !== undefined) options.networkAccessEnabled = network;
      const search = settingText(run.settings["web_search"]);
      if (search !== undefined) options.webSearchMode = search as ThreadOptions["webSearchMode"];
      const skipGit = settingFlag(run.settings["skip_git_repo_check"]);
      if (skipGit !== undefined) options.skipGitRepoCheck = skipGit;
      const directories = settingList(run.settings["additional_directories"]);
      if (directories !== undefined) options.additionalDirectories = directories;

      const thread = codex.startThread(options);
      const streamed = await thread.runStreamed(`${run.instructions}\n\n${run.input}`, {
        outputSchema: { ...run.schema },
        signal: run.signal,
      });

      // The totals, accumulated: `codex` reports usage per turn and no money at
      // all, so the rollup is a sum of what the turns said rather than a number
      // the SDK hands over (PRD resolved q57 ruling a).
      let inputTokens = 0;
      let outputTokens = 0;
      let cached = 0;
      let cacheWrites = 0;
      let answer: string | undefined;

      for await (const event of streamed.events) {
        switch (event.type) {
          case "turn.completed": {
            const usage = event.usage;
            inputTokens += usage.input_tokens;
            outputTokens += usage.output_tokens;
            cached += usage.cached_input_tokens;
            cacheWrites += usage.cache_write_input_tokens;
            yield {
              source: event,
              tap: {
                kind: "turn",
                usage: {
                  inputTokens: usage.input_tokens,
                  cachedInputTokens: usage.cached_input_tokens,
                  outputTokens: usage.output_tokens,
                  reasoningTokens: usage.reasoning_output_tokens,
                },
              },
            };
            break;
          }
          case "turn.failed":
            yield { source: event, tap: { kind: "error", message: event.error.message } };
            break;
          case "error":
            yield { source: event, tap: { kind: "error", message: event.message } };
            break;
          case "item.completed": {
            const tap = codexToolTap(event.item);
            if (event.item.type === "agent_message") answer = event.item.text;
            yield tap === undefined ? { source: event } : { source: event, tap };
            break;
          }
          default:
            yield { source: event };
            break;
        }
      }

      yield {
        source: { type: "agent-compose.settled" },
        tap: {
          kind: "settled",
          cost: { inputTokens, outputTokens },
          // The two counters `cc` has no shape for.
          extra: { cachedInputTokens: cached, cacheWriteInputTokens: cacheWrites },
        },
      };
      if (answer !== undefined) {
        yield {
          source: { type: "agent-compose.agent_message" },
          tap: { kind: "output", value: codexAnswer(answer) },
        };
      }
    })();
  },
};

/**
 * One completed thread item, as a tool event — or `undefined` where the item is
 * not a tool at all.
 *
 * Four of the SDK's eight item types are tool events; the other four are the
 * agent's own message, its reasoning, its to-do list and a non-fatal error,
 * none of which is a call to anything. Their events still reach the payload:
 * this decides what the **trace** carries, not what the journal holds.
 */
function codexToolTap(item: ThreadItem): runtime.HarnessTap | undefined {
  switch (item.type) {
    case "command_execution":
      return {
        kind: "tool",
        name: "command_execution",
        outcome: item.status === "failed" ? "failed" : "completed",
        ...(item.status === "failed"
          ? { error: `the command exited ${item.exit_code ?? "without a status"}` }
          : {}),
      };
    case "file_change":
      return {
        kind: "tool",
        name: "file_change",
        outcome: item.status === "failed" ? "failed" : "completed",
        ...(item.status === "failed" ? { error: "the patch did not apply" } : {}),
      };
    case "mcp_tool_call":
      return {
        kind: "tool",
        name: `${item.server}/${item.tool}`,
        outcome: item.status === "failed" ? "failed" : "completed",
        ...(item.error === undefined ? {} : { error: item.error.message }),
      };
    case "web_search":
      return { kind: "tool", name: "web_search", outcome: "completed" };
    default:
      return undefined;
  }
}

/**
 * The agent's last message, as the value the gate is handed.
 *
 * The SDK documents an `agent_message`'s `text` as JSON when `outputSchema` was
 * asked for, so the text is decoded here. A text that is **not** JSON is handed
 * on as the string it is rather than being refused here: what an answer has to
 * be is the node's `output:` schema, and the gate is the one place that decides
 * it — a driver that refused first would report a decoding failure where the
 * composition's own contract has a message to give (PRD resolved q55 ruling c).
 */
function codexAnswer(text: string): unknown {
  try {
    return JSON.parse(text) as unknown;
  } catch {
    return text;
  }
}

/**
 * The drivers this composition uses, by harness — what `runtime.runCoder` resolves a `coder:` node's harness against.
 *
 * A harness with no driver here is one no node binds, and a run that reached one would be `runtime.HarnessUnavailable`: the adapter refuses at the call rather than dispatching into nothing.
 */
export const DRIVERS: runtime.HarnessDrivers = {
  cc: CC_DRIVER,
  codex: CODEX_DRIVER,
};
