// This file was generated by agent-compose 0.0.0-dev from `main.yml` (target `local`).
//
// It is a build artifact, not source: `agent-compose build` overwrites it,
// and `agent-compose build --check` fails when it has been edited. The spec
// is the single source of truth (PRD 5.12); to own this code instead, copy
// the whole directory out and stop regenerating it.

import * as runtime from "./runtime.ts";
import { query } from "@anthropic-ai/claude-agent-sdk";
import type {
  Options,
  PermissionMode,
  SDKMessage,
} from "@anthropic-ai/claude-agent-sdk";
import { Codex } from "@openai/codex-sdk";
import type {
  CodexOptions,
  SandboxMode,
  ThreadItem,
  ThreadOptions,
} from "@openai/codex-sdk";
//
// The driver seam (grammar 8.9, PRD resolved q57).
//
// `src/runtime.ts` holds the **adapter** — the config map, the journal, the
// stream tap and the output gate — and this file holds the other side of the
// seam it drives: one `runtime.HarnessDriver` per harness this composition
// binds, each a thin mapping over the vendor's own SDK, plus a scripted driver
// that maps over nothing at all.
//
// Three properties are the reason the seam exists, and each is enforced by this
// file being generated rather than shipped:
//
//  * **only what this composition uses.** A driver is emitted for a harness some
//    `coder:` node binds and for no other, so a project with no coder node
//    imports no SDK — and the pins in `package.json` follow the same rule
//    (`codegen::project`). `src/runtime.ts` is byte-identical in every project a
//    release builds, and an SDK import inside it would break that.
//  * **nothing but a mapping.** A driver journals nothing, parses nothing and
//    records nothing: it turns a `runtime.HarnessRun` into the SDK's own call,
//    and the SDK's own events into `runtime.HarnessEvent`s. Every rule about
//    effects, replay, containment and the trace lives one level up, so the
//    shipped drivers and the scripted one are held to the same rules by
//    construction rather than by three copies of them.
//  * **a test surface that runs.** A harness SDK speaks its own wire, so the
//    mock provider — deliberately — never sees it: there is nothing for a test
//    to point a compiled graph at. `scriptedDriver` is what a test drives
//    instead, and it is emitted into every project so that a golden's own
//    `src/harness.ts` is the file under test.
//
// # What a driver may read off an event, and what it may not
//
// The **top level only**. `HarnessEvent.tap` is what reaches the trace envelope,
// and PRD resolved q57 ruling a fixes its depth: a harness that runs subagents
// of its own yields their turns and their tool calls too, and those stay in
// `HarnessEvent.source` — the journal's private payload — where every other
// tool's answer already is. Each driver below says where it reads that boundary
// off its own SDK's events.

/**
 * A driver whose whole behaviour is a script (PRD resolved q57).
 *
 * The test surface, and it is emitted into every project rather than into the
 * ones a test happens to use: a runtime behaviour test drives a **golden's own**
 * `src/harness.ts`, so the scripted driver has to be in the file under test for
 * the thing under test to be the emitted adapter rather than a copy of it.
 *
 * It records every `runtime.HarnessRun` it is handed, which is how a test says
 * anything about the **config map** — that a workspace resolved its `${ENV}`,
 * that an environment was scrubbed, that the schema was projected through this
 * harness's lowering table — none of which is visible from the answer.
 */
export interface ScriptedHarness {
  /** The driver to hand `runtime.runCoder`. */
  readonly driver: runtime.HarnessDriver;
  /** Every run it was handed, in the order it was handed them. */
  readonly runs: runtime.HarnessRun[];
}

/**
 * Build one.
 *
 * `script` is the events one run yields, or a function of the run — the second
 * form for a test whose answer depends on what it was asked, which is the shape
 * a `retry:` test needs: the first attempt's events and the second's differ.
 */
export function scriptedDriver(
  harness: runtime.HarnessName,
  script:
    | readonly runtime.HarnessEvent[]
    | ((run: runtime.HarnessRun, attempt: number) => readonly runtime.HarnessEvent[]),
): ScriptedHarness {
  const runs: runtime.HarnessRun[] = [];
  const driver: runtime.HarnessDriver = {
    sdk: `agent-compose:scripted/${harness}`,
    version: "0",
    // A scripted driver claims the enforcement of the harness it stands in for,
    // so a test reading `enforcesTools` off it reads the real answer.
    enforcesTools: harness === "cc",
    run(run: runtime.HarnessRun): AsyncIterable<runtime.HarnessEvent> {
      runs.push(run);
      const attempt = runs.length;
      const events = typeof script === "function" ? script(run, attempt) : script;
      return (async function* yielded(): AsyncGenerator<runtime.HarnessEvent> {
        for (const event of events) {
          // The node's deadline still ends a scripted run, which is what makes
          // a `timeout:` test possible at all (grammar 9.2).
          run.signal.throwIfAborted();
          yield event;
        }
      })();
    },
  };
  return { driver, runs };
}

/**
 * The harness config one run sends, with the two tiers merged in the order
 * Decision D140 fixes.
 *
 * The **unverified keys travel unchanged**, which is q30's treadmill posture
 * applied one construct along: a harness option the vendor ships tomorrow is
 * usable the day it ships, and `validate` says out loud that it could not verify
 * it. The keys this compiler *does* know are mapped by name in each driver
 * below, over the top, so a curated key and an unknown one spelling the same SDK
 * option cannot disagree about which wins.
 *
 * **`reserved` is the containment bound, and it is not a curated-table
 * question.** A settings key spelling an option the *adapter* owns — the
 * working directory, the permission mode or sandbox preset, the environment,
 * the schema, the abort signal — would be a composition reaching around
 * `workspace:`, `access:` and `env:` through the one surface this grammar
 * deliberately leaves open (grammar 8.9, Decision D140). Those keys are dropped
 * rather than passed, because "unchecked" was never meant to mean
 * "unbounded": what `settings:` buys is the vendor's *other* options, and the
 * bounds are the node's.
 */
function passthrough(
  run: runtime.HarnessRun,
  curated: readonly string[],
  reserved: readonly string[],
): Record<string, unknown> {
  const held: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(run.settings)) {
    if (curated.includes(key) || reserved.includes(key)) continue;
    held[key] = value;
  }
  return held;
}

/** One `AbortController` that follows a run's signal, for an SDK that takes one. */
function controllerFor(signal: AbortSignal): AbortController {
  const controller = new AbortController();
  if (signal.aborted) controller.abort(signal.reason);
  else signal.addEventListener("abort", () => controller.abort(signal.reason), { once: true });
  return controller;
}

/** A number a settings value holds, or `undefined` where it holds something else. */
function settingNumber(value: unknown): number | undefined {
  return typeof value === "number" && Number.isFinite(value) ? value : undefined;
}

/** …a string, under the same rule. */
function settingText(value: unknown): string | undefined {
  return typeof value === "string" && value !== "" ? value : undefined;
}

/** …a boolean. */
function settingFlag(value: unknown): boolean | undefined {
  return typeof value === "boolean" ? value : undefined;
}

/** …and a list of strings. */
function settingList(value: unknown): string[] | undefined {
  if (!Array.isArray(value)) return undefined;
  const held = value.filter((entry): entry is string => typeof entry === "string");
  return held.length === value.length ? held : undefined;
}

/**
 * The `cc` SDK version this compiler release pins — the number `package.json` declares and the number a `HarnessRecord` reports.
 */
const CC_SDK_VERSION: string = "0.3.272";

/**
 * The keys of a `cc` node's `settings:` this compiler release maps by name
 * (Decision D140's first tier).
 *
 * Everything else travels to `query`'s options unchanged, under the warning
 * `validate` printed for it. Both halves are deliberate: a gating table is the
 * treadmill PRD resolved q30 refused, and a key with a *meaning* — a turn bound,
 * a budget — is worth checking before a run rather than after a 400.
 */
const CC_SETTINGS: readonly string[] = [
  "max_turns",
  "max_budget_usd",
  "forward_subagent_text",
  "disallowed_tools",
];

/**
 * The keys of `query`'s options the **adapter** owns, and which a `settings:`
 * key therefore never reaches (see [`passthrough`]).
 *
 * A composition that spelled one of these would be reaching around the
 * construct that states it, through the surface this grammar deliberately
 * leaves open — so they are dropped rather than passed. Two kinds of name are
 * on the list, and the second kind — with one name of the first — is why it is
 * a list rather than a reading of what the driver below assigns:
 *
 *  * an option that **spells** a bound another key states. `workspace:` is
 *    `cwd`; `permission_mode:` is `permissionMode`, the plan-mode body beside it
 *    and the flag `bypassPermissions` requires, with `access:` the key that
 *    derives that mode where the node states none (Decision D146); `env:` is
 *    `env` — which is also where
 *    the model's **connection** lands, because this SDK's endpoint, credential
 *    and custom headers are variables of the process it spawns (Decision D143),
 *    so one reserved name holds both bounds — `output:` is
 *    `outputFormat`, `prompt:` is `systemPrompt`, `allow_tools:` is the
 *    available tool set and the callback over it, `timeout:` is the abort
 *    controller, and `model:` is the model and the one thinking budget
 *    Decision D141 maps into it (`thinking` is here for that last reason: the
 *    SDK documents it as taking precedence over the `maxThinkingTokens` D141
 *    writes). `allowedTools` spells `allow_tools:` too, and it is the one name
 *    of this kind the driver below **never** writes: a bare entry there
 *    approves a whole tool before `canUseTool` is consulted, which the pinned
 *    SDK flags as a shadowed callback (see [`CC_DRIVER`]) — so a key spelling
 *    it would put back the very pairing the driver leaves out;
 *  * an option that **contains** one without spelling it, which a driver never
 *    assigns and a list keyed off the driver could therefore never hold.
 *    `extraArgs` is an arbitrary CLI flag — `dangerously-skip-permissions` and
 *    `add-dir` among them — so it is every bound at once. `settings`,
 *    `managedSettings` and `settingSources` carry permission rules;
 *    `additionalDirectories` carries roots beside `workspace:`; `sandbox`
 *    carries containment; `mcpServers`, `agents`, `agent`, `skills` and
 *    `toolAliases` each put a tool or a whole loop outside `allow_tools:`
 *    within reach — `agent` also carrying its own model and prompt, and
 *    `skills` being the SDK's own single switch for turning skills on, which
 *    its documentation says needs no `'Skill'` entry in `allowedTools` beside
 *    it — and `plugins` carries hooks, agents and skills together; `hooks`,
 *    `permissionPrompts` and
 *    `permissionPromptToolName` each move or silence the decision `canUseTool`
 *    makes; and `fallbackModel` is the failover ladder D141 stops at the
 *    boundary. The **process-spawn family** — `pathToClaudeCodeExecutable`,
 *    `executable`, `executableArgs` and `spawnClaudeCodeProcess` — contains
 *    *every* bound at once and for the worst reason: those four choose which
 *    program runs and what the runtime loads before it, so a key among them
 *    replaces or re-arms the very
 *    harness that is supposed to be enforcing `tools`, `canUseTool` and
 *    `permissionMode`. An adapter never assigns them — it wants the SDK's own
 *    executable — which is exactly why a list read off the driver could not
 *    hold them. The `resume` family — `resume`, `continue`, `forkSession`,
 *    `sessionId`, `resumeSessionAt`, `resumeDropsTurn` — is dropped for PRD
 *    resolved q57 ruling b's reason rather than for containment: harness-native
 *    resume is a **named exclusion**, because a machine-local session store is
 *    not the journal.
 *
 * The list is audited against the option surface of the pinned SDK, which is
 * what `a_reserved_list_is_audited_against_the_pinned_option_surface`
 * (`codegen/harness.rs`) holds it to: a version bump is where a new
 * reach-around arrives, so the pin is what re-opens the audit.
 */
const CC_RESERVED: readonly string[] = [
  // Options that spell a bound another key states.
  "abortController",
  "allowDangerouslySkipPermissions",
  "allowedTools",
  "canUseTool",
  "cwd",
  "env",
  "maxThinkingTokens",
  "model",
  "outputFormat",
  "permissionMode",
  "planModeInstructions",
  "systemPrompt",
  "thinking",
  "tools",
  // …and options that contain one without spelling it.
  "additionalDirectories",
  "agent",
  "agents",
  "continue",
  "executable",
  "executableArgs",
  "extraArgs",
  "fallbackModel",
  "forkSession",
  "hooks",
  "managedSettings",
  "mcpServers",
  "pathToClaudeCodeExecutable",
  "permissionPromptToolName",
  "permissionPrompts",
  "plugins",
  "resume",
  "resumeDropsTurn",
  "resumeSessionAt",
  "sandbox",
  "sessionId",
  "settingSources",
  "settings",
  "skills",
  "spawnClaudeCodeProcess",
  "toolAliases",
];

/**
 * How `access:` reaches the Agent SDK (grammar 8.9, Decisions D138, D146).
 *
 * The SDK's containment primitive is a permission *mode* plus a working
 * directory, so the preset selects the mode and `cwd` carries the root. Which
 * primitive a preset lands on is **stated per harness and never implied
 * equivalent** (PRD resolved q57 ruling c): what `access:` means is the same
 * sentence under both harnesses, and what enforces it is each harness's own:
 *
 *  * `read_only` → `plan`, the mode whose system reminder the CLI wraps in its
 *    **read-only enforcement** preamble: the tree is readable and nothing under
 *    it is written. It is the one containment statement the SDK's own surface
 *    makes without a tool taxonomy this adapter would have had to invent, and
 *    the node's own instructions replace the mode's default
 *    code-implementation workflow body (`planModeInstructions`) so the run is
 *    asked for what the node asked for rather than for a plan to implement
 *    something;
 *  * `workspace_write` → `acceptEdits`, which auto-accepts edits under the
 *    working directory and still asks about everything else;
 *  * `full_access` → `bypassPermissions`, with the flag the SDK requires beside
 *    it, which is the preset that asks for no containment at all.
 *
 * This is the **derived** mode: what a node that states no `permission_mode:`
 * runs under, which is every node written before that key existed (Decision
 * D146). A node that states one supersedes the map here and nowhere else — the
 * compiler has already refused any mode the level does not admit, so the value
 * arriving at [`ccPermissionMode`] is never wider than this one.
 */
const CC_PERMISSION: Readonly<Record<runtime.WorkspaceAccess, PermissionMode>> = {
  read_only: "plan",
  workspace_write: "acceptEdits",
  full_access: "bypassPermissions",
};

/**
 * The mode one run works under: the one the node stated, or the one its
 * `access:` level derives (grammar 8.9, Decision D146, PRD resolved q60 ruling
 * a).
 *
 * **One function, because three options answer to this value** and a second
 * reading of it would be a second answer. `permissionMode` is the mode itself;
 * `allowDangerouslySkipPermissions` is the flag the SDK *requires* beside
 * `bypassPermissions` and beside nothing else; and `planModeInstructions` is
 * plan mode's body, which exists only when the mode is `plan`. Keying those two
 * off `run.access` instead — which is what this driver did while `access:` was
 * the only axis — would arm the skip flag on a `full_access` node that asked for
 * `plan`, and leave a `full_access` node that asked for `plan` running the
 * vendor's default code-implementation body instead of the node's own prompt.
 * Reading the resolved mode is the same answer in every case the two used to
 * agree on, which is every node that states no mode at all.
 */
function ccPermissionMode(run: runtime.HarnessRun): PermissionMode {
  return run.permissionMode ?? CC_PERMISSION[run.access];
}

/**
 * Whether one resolved header value would forge a second header field.
 *
 * The compiler asks this of the text a composition **wrote** (`validate`
 * refuses it there, `invalid-value`); this asks it of what a `${ENV}` resolved
 * to, which is text no build ever saw and precisely the shape a gateway
 * deployment produces — an operator sets the variable, not the author.
 *
 * Every control character **but a tab**, not only the two that split a line:
 * `\r` on its own is a byte no header value carries either, `\r\n` splits on the
 * newline and leaves the carriage return glued to the line before it, and `\0`
 * truncates the environment variable this encoding writes. A tab passes because
 * RFC 9110 5.5's `field-content` admits `SP` and `HTAB` between visible
 * characters, so a tab is content a header value really carries and no split
 * this variable performs — on newlines, then on each line's first colon —
 * notices one.
 *
 * The set is the parser's set, character for character (grammar Decision D144,
 * `parse::binding::header_value_shape`), including the C1 range Rust's
 * `char::is_control` covers: the two halves of one rule ask the same question of
 * written text and of resolved text, and a value this refuses at run time is one
 * `validate` would have refused had the composition written it out.
 */
function forgesAHeaderField(value: string): boolean {
  for (let index = 0; index < value.length; index += 1) {
    const code = value.charCodeAt(index);
    if (code === 0x09) continue;
    if (code < 0x20 || (code >= 0x7f && code <= 0x9f)) return true;
  }
  return false;
}

/**
 * How a provider connection reaches this harness (grammar 8.9, Decision D143,
 * PRD resolved q58 ruling a).
 *
 * The SDK's own `Options` carry no endpoint and no credential — what they carry
 * is `env`, documented as **replacing** the subprocess environment outright —
 * and the Claude Code runtime that subprocess runs reads its connection out of
 * that environment. So all three facts are variables, merged into the `env` the
 * adapter already built from the node's own `env:`:
 *
 *  * `ANTHROPIC_BASE_URL` — the endpoint the bundled client is constructed with;
 *  * `ANTHROPIC_API_KEY` — the credential, read the same way. The **key** rather
 *    than the auth-token variable beside it, because what grammar 12.1 spells
 *    `api_key:` is a vendor API key; a gateway wanting a bearer token of its own
 *    writes it into `headers:`, which is resolved q25's own answer and arrives
 *    through the variable below;
 *  * `ANTHROPIC_CUSTOM_HEADERS` — one `Name: value` per line, which is how that
 *    runtime parses it.
 *
 * Three variables written, and **more than three owned** — which is
 * [`CC_CONNECTION_VARIABLES`], and why the merge that uses this function is
 * [`ccEnvironment`] rather than a spread. That runtime reads a whole endpoint
 * table and a whole credential list — `ANTHROPIC_AUTH_TOKEN` is sent as a bearer
 * header beside the `X-Api-Key` the second variable sets, and
 * `CLAUDE_CODE_USE_BEDROCK` with its `ANTHROPIC_BEDROCK_BASE_URL` companion
 * chooses an endpoint instead of the first — so `validate` refuses a node `env:`
 * entry naming any of them for a fact this connection declares, not only the
 * three below (grammar Decision D143, PRD resolved q58 rulings a and c). The
 * node's own `env:` therefore needs no filtering here; the **inherited** half
 * does, and that is what [`ccEnvironment`] removes before this map goes over the
 * top.
 *
 * **An absent fact sets no variable**, which is the half a one-token slip would
 * turn into the opposite of q25's ruling: a keyless gateway connection must
 * leave the credential variable *unset*, not set to the empty string, or the
 * harness would authenticate as nobody instead of letting the gateway do it.
 * `validate` has already refused a node whose provider declares a fact this
 * harness has no slot for, so there is nothing here to drop.
 *
 * **The header encoding is the one slot that can be handed a value it cannot
 * carry**, and this is where that is caught. `ANTHROPIC_CUSTOM_HEADERS` is
 * newline-delimited and each line is split on its first colon, so a value
 * carrying a line break would declare one header and send two — the second one
 * spelled by the value, which is `x-api-key` as easily as anything else.
 * `validate` refuses such a value where the composition *wrote* it, but a
 * `${ENV}` is text this build never saw and a gateway deployment is exactly
 * where operators set those variables (PRD resolved q58 ruling a). So the
 * resolved value is asked the same question here, and a run is failed rather
 * than quietly sent with a header nobody declared. The message names the node
 * and the header and **never the value**, which is `docs/trace.md` §11.1's rule
 * about every artifact this project writes: a connection header is where a
 * gateway credential lives.
 */
function ccConnection(run: runtime.HarnessRun): Record<string, string> {
  const held: Record<string, string> = {};
  const connection = run.connection;
  if (connection.baseUrl !== undefined) held["ANTHROPIC_BASE_URL"] = connection.baseUrl;
  if (connection.credential !== undefined) held["ANTHROPIC_API_KEY"] = connection.credential;
  const headers = Object.entries(connection.headers ?? {});
  if (headers.length > 0) {
    for (const [name, value] of headers) {
      if (forgesAHeaderField(value)) {
        throw new Error(
          `\`${run.node}\`'s connection header \`${name}\` resolves to a value carrying a control character: ` +
            "`ANTHROPIC_CUSTOM_HEADERS` is one `Name: value` per line, so the run would send a header the composition never declared",
        );
      }
    }
    held["ANTHROPIC_CUSTOM_HEADERS"] = headers.map(([name, value]) => `${name}: ${value}`).join("\n");
  }
  return held;
}

/**
 * Every variable the pinned runtime reads for one connection fact — the slot
 * [`ccConnection`] writes **and** every other name that decides the same thing
 * (grammar 8.9, Decision D143, PRD resolved q58 rulings a and c).
 *
 * This is the compiler's own `cc` connection row, declared again for the
 * runtime, exactly as [`CC_SETTINGS`] is the curated settings table declared
 * again for [`passthrough`] — and held to it by
 * `the_cc_connection_variable_table_is_one_table` in `src/harness.rs`, because
 * two hand-maintained copies of one document drift in silence.
 *
 * It exists because a slot is not the only name that answers its question.
 * `ANTHROPIC_AUTH_TOKEN` is sent as `Authorization: Bearer …` *beside* the
 * `X-Api-Key` the credential slot sets; the `CLAUDE_CODE_USE_*` selectors each
 * choose an endpoint instead of `ANTHROPIC_BASE_URL`, and the
 * `*_FILE_DESCRIPTOR` names hand a credential over on a file descriptor rather
 * than in a value. Guarding only the three the map writes leaves every one of
 * those free to decide the fact the composition already decided.
 */
const CC_CONNECTION_VARIABLES: Readonly<Record<keyof runtime.HarnessConnection, readonly string[]>> =
  {
    baseUrl: [
      "ANTHROPIC_BASE_URL",
      "_CLAUDE_CODE_ASSUME_FIRST_PARTY_BASE_URL",
      "ANTHROPIC_BEDROCK_BASE_URL",
      "CLAUDE_CODE_USE_BEDROCK",
      "ANTHROPIC_VERTEX_BASE_URL",
      "CLAUDE_CODE_USE_VERTEX",
      "ANTHROPIC_FOUNDRY_BASE_URL",
      "CLAUDE_CODE_USE_FOUNDRY",
      "ANTHROPIC_AWS_BASE_URL",
      "CLAUDE_CODE_USE_ANTHROPIC_AWS",
      "ANTHROPIC_GOOGLE_CLOUD_BASE_URL",
      "CLAUDE_CODE_USE_ANTHROPIC_GOOGLE_CLOUD",
      "ANTHROPIC_BEDROCK_MANTLE_BASE_URL",
      "CLAUDE_CODE_USE_MANTLE",
      "CLAUDE_CODE_USE_GATEWAY",
    ],
    credential: [
      "ANTHROPIC_API_KEY",
      "ANTHROPIC_AUTH_TOKEN",
      "CLAUDE_CODE_OAUTH_TOKEN",
      "AWS_BEARER_TOKEN_BEDROCK",
      "ANTHROPIC_FOUNDRY_API_KEY",
      "ANTHROPIC_FOUNDRY_AUTH_TOKEN",
      "ANTHROPIC_AWS_API_KEY",
      "CLAUDE_CODE_SKIP_BEDROCK_AUTH",
      "CLAUDE_CODE_SKIP_VERTEX_AUTH",
      "CLAUDE_CODE_SKIP_FOUNDRY_AUTH",
      "CLAUDE_CODE_SKIP_ANTHROPIC_AWS_AUTH",
      "CLAUDE_CODE_SKIP_ANTHROPIC_GOOGLE_CLOUD_AUTH",
      "CLAUDE_CODE_SKIP_MANTLE_AUTH",
      "CLAUDE_CODE_OAUTH_TOKEN_FILE_DESCRIPTOR",
      "CLAUDE_CODE_GATEWAY_TOKEN_FILE_DESCRIPTOR",
      "CLAUDE_CODE_API_KEY_FILE_DESCRIPTOR",
      "CLAUDE_CODE_WEBSOCKET_AUTH_FILE_DESCRIPTOR",
    ],
    headers: ["ANTHROPIC_CUSTOM_HEADERS"],
  };

/**
 * Whether the connection **declares** one fact, which is the same question
 * [`ccConnection`] asks before it writes that fact's slot.
 *
 * `headers:` is the one that is not a bare `!== undefined`: an empty header map
 * writes no variable, so it claims no name either — the two answers are one
 * answer, and the compiler's `declared` reads it the same way.
 */
function ccDeclares(
  connection: runtime.HarnessConnection,
  fact: keyof runtime.HarnessConnection,
): boolean {
  if (fact === "headers") return Object.keys(connection.headers ?? {}).length > 0;
  return connection[fact] !== undefined;
}

/**
 * The environment one `cc` run is handed: the node's own, **minus every name
 * this runtime reads for a fact the connection declares**, plus the connection
 * itself (PRD resolved q58 rulings a and c, q54 ruling b).
 *
 * The subtraction is the whole of this function, and `inherit_env: true` is why
 * it is not redundant. `validate` refuses a node `env:` entry spelling any name
 * [`CC_CONNECTION_VARIABLES`] claims for a declared fact, so the *declared* half
 * of the environment is already clean when it arrives. The **inherited** half
 * never passed through `validate` at all: it is whatever shell started this
 * process, and a machine that runs `claude` interactively is exactly the machine
 * that has `CLAUDE_CODE_USE_BEDROCK` and an `ANTHROPIC_AUTH_TOKEN` set. Merging
 * the map over the top only overwrites the three names it writes, so without
 * this a gateway-bound coder run would inherit a selector that repoints it, or a
 * bearer token sent beside the composition's own key — while `validate` stayed
 * clean and the graph document and the journal's `connection` both went on
 * reporting `ANTHROPIC_BASE_URL`. That is the failure the sibling list exists to
 * refuse, arriving through the one door ruling c cannot reach.
 *
 * **An undeclared fact claims nothing**, which is q25's keyless posture read
 * here rather than one surface along: a provider with no `api_key:` leaves the
 * whole credential family alone, so a node that inherits a shell holding
 * `ANTHROPIC_AUTH_TOKEN` keeps it — the connection says nothing about how this
 * run authenticates, and the compiler's own `variables_read` is computed from
 * the declared facts for the same reason.
 */
function ccEnvironment(run: runtime.HarnessRun): Record<string, string> {
  const held: Record<string, string> = { ...run.env };
  for (const [fact, names] of Object.entries(CC_CONNECTION_VARIABLES) as [
    keyof runtime.HarnessConnection,
    readonly string[],
  ][]) {
    if (!ccDeclares(run.connection, fact)) continue;
    for (const name of names) delete held[name];
  }
  return { ...held, ...ccConnection(run) };
}

/**
 * The `cc` driver: a thin mapping over the Claude Agent SDK.
 *
 * # Where the top level is
 *
 * `parent_tool_use_id === null`. Every message the SDK yields carries it, and a
 * message produced *inside* a subagent carries that subagent's tool-use id — so
 * the one predicate is the whole of PRD resolved q57 ruling a's depth rule: a
 * subagent's turns and tool calls are yielded with no `tap` and reach the
 * journal payload only.
 *
 * # What enforces the allowlist
 *
 * **Two options, because one of them has a hole.** `tools` is the SDK's own
 * "base set of available built-in tools", so a list written there is a tool set
 * the model is never offered — the availability bound, which holds whatever the
 * permission mode is. `canUseTool` is the per-call gate over it, consulted
 * where a call would otherwise stop to ask: it answers `allow` for a name
 * inside the list, so a bounded run is not also a prompting one, and it denies
 * anything outside the list that reached the loop anyway, taping the denial as
 * a `"refused"` tool event so the trace says the bound bit.
 *
 * The hole is `access: full_access`, and it is why `tools` carries the bound
 * rather than the callback: that preset is `permissionMode: "bypassPermissions"`,
 * which the SDK documents as bypassing **all** permission checks — so
 * `canUseTool` does not run, and a node whose `enforcesTools` says its list is
 * enforced would be asserting a bound nothing held (grammar 8.9, PRD resolved
 * q57 ruling c). Narrowing the available set is the answer the SDK's own
 * documentation gives for `allowedTools`: "to restrict which tools are
 * available, use the `tools` option instead".
 *
 * **And not three: there is no `allowedTools`**, though it reads like the way
 * to keep a bounded run from prompting. A bare name there approves the whole
 * tool *before* the callback is consulted, so beside `canUseTool` it shadows
 * the callback — and the pinned SDK does not leave that silent: `query()`
 * reports the pairing as a shadowed callback under
 * `CLAUDE_SDK_CAN_USE_TOOL_SHADOWED`, naming every bare entry the callback
 * will never be asked about. The callback already answers `allow` for exactly
 * those names, so the list's whole decision is made in one place — the place a
 * refusal is taped — rather than half of it ahead of the callback, where the
 * trace cannot see it. `allowedTools` stays on [`CC_RESERVED`] for the same
 * reason: a `settings:` key spelling it would put the shadow back.
 *
 * One shadow is accepted, and it is the hole above: under `bypassPermissions`
 * the SDK reports the callback as shadowed under the same code, because that
 * mode approves every call before any callback runs. The callback is kept there
 * all the same — it is one options object for every mode, and under that mode
 * the bound was never the callback's to hold: `tools` holds it.
 *
 * # Whose system prompt a run has
 *
 * The harness's, with the node's `prompt:` **appended** to it
 * (`{ type: "preset", preset: "claude_code", append }`). A bare string there is
 * the SDK's custom-prompt form and *replaces* the preset — and the preset is
 * the vendor's own agent instructions, which is half of what PRD resolved q57
 * makes this a kind for: the loop, the tool shapes and the prompt the model was
 * post-trained against are the thing that cannot be reassembled from parts. So
 * the node's prompt is what it reads like in the grammar — instructions *for*
 * the harness — rather than a replacement of the harness.
 *
 * # What is asked for, and what is parsed
 *
 * `outputFormat: { type: "json_schema" }` carrying the schema the adapter
 * already projected through this harness's lowering table, and the answer
 * arrives as the result message's `structured_output`. The adapter parses it
 * against the **full** declared schema, which is where PRD resolved q55's
 * amendment to q16 lives.
 */
const CC_DRIVER: runtime.HarnessDriver = {
  sdk: "@anthropic-ai/claude-agent-sdk",
  version: CC_SDK_VERSION,
  enforcesTools: true,
  run(run: runtime.HarnessRun): AsyncIterable<runtime.HarnessEvent> {
    return (async function* driven(): AsyncGenerator<runtime.HarnessEvent> {
      // What the permission callback refused, drained into the stream between
      // messages: `canUseTool` answers the SDK rather than this generator, so a
      // queue is how a denial becomes a tool event in the order it happened.
      const refusals: runtime.HarnessEvent[] = [];
      // The name each top-level `tool_use` went out under, so the `tool_result`
      // that answers it can be taped under the same name.
      const calls = new Map<string, string>();
      // The `tool_use` ids the callback below denied. A denial is taped once,
      // from the callback; the `tool_result` the SDK then hands the model is
      // that same denial travelling back, and taping it again would claim two
      // tool events where the run made one (`docs/trace.md` 7.6.3, whose
      // `completed` and `failed` describe a call that executed).
      const refused = new Set<string>();

      const config = ccOptions(run, refusals, refused);

      for await (const message of query({ prompt: run.input, options: config })) {
        while (refusals.length > 0) yield refusals.shift() as runtime.HarnessEvent;
        yield* ccEvents(message, calls, refused);
      }
      while (refusals.length > 0) yield refusals.shift() as runtime.HarnessEvent;
    })();
  },
};

/**
 * The `Options` one `cc` run is made of — the config map of grammar 8.9, as one
 * value (see [`CC_DRIVER`]).
 *
 * **Exported for the reason [`scriptedDriver`] is**: what this object holds is
 * the whole of the node's containment, and none of it is visible from a run's
 * answer or from the events a driver yields. A test that could only drive the
 * seam could say nothing about the bound at all — and the bound that matters
 * most, the [`CC_RESERVED`] drop, is a *subtraction*: it is what a settings key
 * did **not** put here. So the options are built by a function a test can call
 * and then read, against a `run` whose `settings` spell every bound this node
 * states, rather than assembled inline where only the vendor's SDK ever sees
 * them.
 *
 * `refusals` and `refused` are the driver's own two queues, handed in because
 * the permission callback below writes to both: a denial is an event the
 * generator drains between messages, and an id the `tool_result` that answers
 * it is told apart by.
 */
export function ccOptions(
  run: runtime.HarnessRun,
  refusals: runtime.HarnessEvent[],
  refused: Set<string>,
): Options {
  // The node's approval mode, resolved once: the three options below that
  // answer to it read this value rather than `run.access`, so a stated mode and
  // the flags its SDK requires can never disagree (see [`ccPermissionMode`]).
  const mode = ccPermissionMode(run);
  const options: Options = {
    cwd: run.workspace,
    systemPrompt: { type: "preset", preset: "claude_code", append: run.instructions },
    model: run.model,
    permissionMode: mode,
    abortController: controllerFor(run.signal),
    // The node's environment with the model's connection mapped over the top —
    // and, first, with every other name this runtime reads for a declared fact
    // taken out of it. `validate` refuses an `env:` entry spelling one of those,
    // so the *declared* half needs no filtering; `inherit_env: true` is the half
    // no compile step ever saw, and a merge order alone could not have fixed it
    // (see [`ccEnvironment`], PRD resolved q58 ruling c).
    env: ccEnvironment(run),
    outputFormat: { type: "json_schema", schema: { ...run.schema } },
    ...passthrough(run, CC_SETTINGS, CC_RESERVED),
  };
  // The flag the SDK documents `bypassPermissions` as requiring, and nothing
  // else does — so it is armed by the mode rather than by the preset that
  // usually derives it (see [`ccPermissionMode`]).
  if (mode === "bypassPermissions") options.allowDangerouslySkipPermissions = true;
  // Plan mode's body, replaced by what this node asked for: the mode's
  // default body is a code-implementation workflow, and a node under `plan`
  // is a run that reads and reports (see [`CC_PERMISSION`]).
  if (mode === "plan") options.planModeInstructions = run.instructions;
  // The one `model.*` setting this harness has a place for: the `anthropic`
  // plugin's `thinking: { budget_tokens: … }` is the SDK's
  // `maxThinkingTokens` (Decision D141).
  const thinking = run.modelSettings["thinking"];
  const budgetTokens =
    typeof thinking === "object" && thinking !== null
      ? settingNumber((thinking as Record<string, unknown>)["budget_tokens"])
      : undefined;
  if (budgetTokens !== undefined) options.maxThinkingTokens = budgetTokens;
  const maxTurns = settingNumber(run.settings["max_turns"]);
  if (maxTurns !== undefined) options.maxTurns = maxTurns;
  const budget = settingNumber(run.settings["max_budget_usd"]);
  if (budget !== undefined) options.maxBudgetUsd = budget;
  const forward = settingFlag(run.settings["forward_subagent_text"]);
  if (forward !== undefined) options.forwardSubagentText = forward;
  const disallowed = settingList(run.settings["disallowed_tools"]);
  if (disallowed !== undefined) options.disallowedTools = disallowed;
  const allowed = run.allowTools;
  if (allowed !== undefined) {
    // The bound itself: a tool outside the list is not in the set the loop
    // can reach, which is true under every one of the three `access:`
    // presets — `bypassPermissions` included.
    options.tools = [...allowed];
    // …and the per-call gate over it, which is also what keeps a bounded run
    // from prompting: an in-list call is answered `allow` here. Nothing
    // approves the list ahead of this callback — a bare `allowedTools` would,
    // and the pinned SDK flags that pairing as a shadowed callback (see
    // [`CC_DRIVER`]).
    options.canUseTool = (name, _input, ask) => {
      if (allowed.includes(name)) return Promise.resolve({ behavior: "allow" as const });
      const message = `\`${run.node}\` allows ${allowed.map((tool) => `\`${tool}\``).join(", ")}, and \`${name}\` is not one of them`;
      // The call this denial answers, remembered by its id: the SDK hands
      // the model the denial as the `tool_result` for that `tool_use`, and
      // one call is one tool event.
      refused.add(ask.toolUseID);
      refusals.push({
        source: { type: "agent-compose.permission_denied", tool: name, message },
        // A denial inside a **subagent** is that subagent's, and the
        // envelope carries the top level only — the same depth rule
        // [`ccEvents`] reads off `parent_tool_use_id`, read here off the
        // sub-agent id the SDK passes the callback (PRD resolved q57
        // ruling a).
        ...(ask.agentID === undefined
          ? { tap: { kind: "tool" as const, name, outcome: "refused" as const, error: message } }
          : {}),
      });
      return Promise.resolve({ behavior: "deny" as const, message });
    };
  }
  return options;
}

/** One SDK message, as the events the tap reads (see [`CC_DRIVER`]). */
function* ccEvents(
  message: SDKMessage,
  calls: Map<string, string>,
  refused: Set<string>,
): Generator<runtime.HarnessEvent> {
  // A message from inside a subagent is payload and nothing else — the depth
  // rule PRD resolved q57 ruling a fixes, read off the one field that carries
  // it.
  const nested =
    "parent_tool_use_id" in message && (message as { parent_tool_use_id: unknown }).parent_tool_use_id !== null;
  if (nested) {
    yield { source: message };
    return;
  }
  if (message.type === "assistant") {
    const blocks = Array.isArray(message.message.content) ? message.message.content : [];
    for (const block of blocks) {
      if (block.type === "tool_use") calls.set(block.id, block.name);
    }
    yield { source: message, tap: { kind: "turn" } };
    return;
  }
  if (message.type === "user") {
    const blocks = Array.isArray(message.message.content) ? message.message.content : [];
    yield { source: message };
    for (const block of blocks) {
      if (block.type !== "tool_result") continue;
      const name = calls.get(block.tool_use_id);
      if (name === undefined) continue;
      // A call the permission callback denied was taped `refused` there, and
      // this result is that denial on its way to the model rather than a second
      // event: the call never executed, so neither `completed` nor `failed`
      // describes it (`docs/trace.md` 7.6.3). The message still reaches the
      // journal's payload above, untapped, like every other result.
      if (refused.delete(block.tool_use_id)) {
        calls.delete(block.tool_use_id);
        continue;
      }
      const failed = block.is_error === true;
      yield {
        source: { type: "agent-compose.tool_result", tool: name, is_error: failed },
        tap: {
          kind: "tool",
          name,
          outcome: failed ? "failed" : "completed",
          ...(failed ? { error: `the tool result came back as an error` } : {}),
        },
      };
    }
    return;
  }
  if (message.type === "result") {
    const usage = message.usage as { input_tokens?: number; output_tokens?: number };
    yield {
      source: message,
      tap: {
        kind: "settled",
        cost: {
          ...(typeof usage.input_tokens === "number" ? { inputTokens: usage.input_tokens } : {}),
          ...(typeof usage.output_tokens === "number" ? { outputTokens: usage.output_tokens } : {}),
          ...(typeof message.total_cost_usd === "number" ? { usd: message.total_cost_usd } : {}),
        },
        // The two facts `codex` has no shape for: which of the SDK's result
        // subtypes this was, and the stop reason underneath it.
        extra: { subtype: message.subtype, stopReason: message.stop_reason },
      },
    };
    if (message.subtype !== "success") {
      yield {
        source: { type: "agent-compose.result_error", subtype: message.subtype },
        tap: { kind: "error", message: `the run ended \`${message.subtype}\`` },
      };
      return;
    }
    if (message.structured_output !== undefined) {
      yield {
        source: { type: "agent-compose.structured_output" },
        tap: { kind: "output", value: message.structured_output },
      };
    }
    return;
  }
  yield { source: message };
}

/**
 * The `codex` SDK version this compiler release pins — the number `package.json` declares and the number a `HarnessRecord` reports.
 */
const CODEX_SDK_VERSION: string = "0.154.0";

/**
 * The keys of a `codex` node's `settings:` this compiler release maps by name
 * (Decision D140's first tier).
 *
 * Everything else travels to the thread's options unchanged, under the warning
 * `validate` printed for it — PRD resolved q30's terms, one construct along.
 */
const CODEX_SETTINGS: readonly string[] = [
  "network_access",
  "web_search",
  "skip_git_repo_check",
];

/**
 * The keys of a thread's options the **adapter** owns, and which a `settings:`
 * key therefore never reaches (see [`passthrough`]).
 *
 * Two kinds of name are on the list, exactly as on `cc`'s:
 *
 *  * an option that **spells** a bound some other part of the node states:
 *    `workspace:` is `workingDirectory`, `access:` is `sandboxMode` and the
 *    approval policy beside it, and `model:` is the model and the one reasoning
 *    setting Decision D141 maps into it. A composition that spelled one of them
 *    here would be reaching around the construct that states it, through the
 *    surface this grammar deliberately leaves open — so these are dropped
 *    rather than passed. The environment is not on the list because it is not a
 *    thread option at all, and neither is the model's **connection**: both are
 *    the *client's*, built by [`codexClient`] from a literal that no
 *    `settings:` key reaches;
 *  * an option that **contains** one without spelling it, which is the wider
 *    half of the dropped set grammar 8.9 states: `additionalDirectories` is
 *    additional sandbox roots beside `workspace:`, so a run under it is written
 *    where the node's own workspace never reached. It is the same option `cc`
 *    drops by the same name, and the two harnesses answer that key the same way
 *    or `access:` means one thing under one harness and another under the
 *    other.
 *
 * `approvalPolicy` is the one that is neither: it is the **per-call approval
 * tier** PRD resolved q57 ruling c says this release does not adopt, and a run
 * that escalated out of its sandbox to an approver nothing answers for would be
 * `access:` saying one thing and the run doing another. The thread's other
 * options are the vendor's own vocabulary and travel unchanged, which is
 * Decision D140's whole point.
 *
 * The list is audited against the pinned SDK's own `ThreadOptions`, which is
 * what `a_reserved_list_is_audited_against_the_pinned_option_surface`
 * (`codegen/harness.rs`) holds it to.
 */
const CODEX_RESERVED: readonly string[] = [
  // Options that spell a bound another key states.
  "approvalPolicy",
  "model",
  "modelReasoningEffort",
  "sandboxMode",
  "workingDirectory",
  // …and the option that contains one without spelling it.
  "additionalDirectories",
];

/**
 * How `access:` reaches the Codex SDK (grammar 8.9, Decision D138).
 *
 * One-to-one with its own sandbox presets, which is why this grammar's three
 * names are the three they are: `codex` is the harness whose containment
 * primitive is named, and a vocabulary that did not line up with it would be a
 * translation nobody could check.
 */
const CODEX_SANDBOX: Readonly<Record<runtime.WorkspaceAccess, SandboxMode>> = {
  read_only: "read-only",
  workspace_write: "workspace-write",
  full_access: "danger-full-access",
};

/**
 * The `codex` driver: a thin mapping over the Codex SDK.
 *
 * # Where the top level is
 *
 * Everywhere. `runStreamed` yields one thread's events, and a Codex thread has
 * no nesting for PRD resolved q57 ruling a's depth rule to cut at: what its
 * `mcp_tool_call` items reach is another process's, not a subagent of this run.
 * So every turn and every tool item this stream carries is a top-level one, and
 * the ruling's boundary is satisfied by there being nothing below it.
 *
 * # What bounds a run, and what does not
 *
 * The **sandbox**, and nothing else. The Codex SDK's per-call approval tier is
 * their app server's, which this release does not adopt, so `enforcesTools` is
 * `false` and `docs/grammar.md` 8.9 states the asymmetry where an author writes
 * the list. The `codex` half of PRD resolved q57 ruling c is this constant.
 *
 * `allow_tools:` is therefore what the harness is **offered**, and offering it
 * is something a driver has to do rather than something that happens: a thread
 * has no tool-set option to put it in, so the list reaches the run the one way
 * anything reaches it — as a line of the instructions the turn carries
 * ([`codexTurn`]). A list that reached nothing at all would make grammar 8.9's
 * `offered` a word for a key with no effect.
 *
 * # What is asked for, and what is parsed
 *
 * `outputSchema`, carrying the schema the adapter already projected through this
 * harness's lowering table; the answer arrives as the last `agent_message`
 * item's text, which the SDK documents as JSON when a schema was asked for. The
 * adapter parses it against the **full** declared schema (PRD resolved q55).
 */
const CODEX_DRIVER: runtime.HarnessDriver = {
  sdk: "@openai/codex-sdk",
  version: CODEX_SDK_VERSION,
  enforcesTools: false,
  run(run: runtime.HarnessRun): AsyncIterable<runtime.HarnessEvent> {
    return (async function* driven(): AsyncGenerator<runtime.HarnessEvent> {
      const codex = new Codex(codexClient(run));
      const thread = codex.startThread(codexOptions(run));
      const streamed = await thread.runStreamed(codexTurn(run), {
        outputSchema: { ...run.schema },
        signal: run.signal,
      });

      // The totals, accumulated: `codex` reports usage per turn and no money at
      // all, so the rollup is a sum of what the turns said rather than a number
      // the SDK hands over (PRD resolved q57 ruling a).
      let inputTokens = 0;
      let outputTokens = 0;
      let cached = 0;
      let cacheWrites = 0;
      let answer: string | undefined;

      for await (const event of streamed.events) {
        switch (event.type) {
          case "turn.completed": {
            const usage = event.usage;
            inputTokens += usage.input_tokens;
            outputTokens += usage.output_tokens;
            cached += usage.cached_input_tokens;
            cacheWrites += usage.cache_write_input_tokens;
            yield {
              source: event,
              tap: {
                kind: "turn",
                usage: {
                  inputTokens: usage.input_tokens,
                  cachedInputTokens: usage.cached_input_tokens,
                  outputTokens: usage.output_tokens,
                  reasoningTokens: usage.reasoning_output_tokens,
                },
              },
            };
            break;
          }
          case "turn.failed":
            yield { source: event, tap: { kind: "error", message: event.error.message } };
            break;
          case "error":
            yield { source: event, tap: { kind: "error", message: event.message } };
            break;
          case "item.completed": {
            const tap = codexToolTap(event.item);
            if (event.item.type === "agent_message") answer = event.item.text;
            yield tap === undefined ? { source: event } : { source: event, tap };
            break;
          }
          default:
            yield { source: event };
            break;
        }
      }

      yield {
        source: { type: "agent-compose.settled" },
        tap: {
          kind: "settled",
          cost: { inputTokens, outputTokens },
          // The two counters `cc` has no shape for.
          extra: { cachedInputTokens: cached, cacheWriteInputTokens: cacheWrites },
        },
      };
      if (answer !== undefined) {
        yield {
          source: { type: "agent-compose.agent_message" },
          tap: { kind: "output", value: codexAnswer(answer) },
        };
      }
    })();
  },
};

/**
 * Every variable the pinned Codex CLI reads for one connection fact — the name
 * the SDK injects from the client option **and** every other name that decides
 * the same thing (grammar 8.9, Decision D143, PRD resolved q58 rulings a and c).
 *
 * This is the compiler's own `codex` connection row, declared again for the
 * runtime, exactly as [`CC_CONNECTION_VARIABLES`] is under the other harness —
 * and held to it by `the_connection_variable_tables_are_one_table` in
 * `src/harness.rs`, because two hand-maintained copies of one document drift in
 * silence.
 *
 * It exists because this harness's surface does not stop at `CodexOptions`. The
 * SDK sets `CODEX_API_KEY` from `apiKey` on top of the environment it is handed,
 * and the program that reads it is the CLI the SDK spawns — pinned by the SDK's
 * own dependency (`"@openai/codex": "0.154.0"`), so as audited as the `.d.ts`
 * above it. That CLI supports **three** auth variables, not one: its own string
 * table names `OPENAI_API_KEY`, `CODEX_API_KEY` and `CODEX_ACCESS_TOKEN`
 * together beside "Run codex login or provide an API key through a supported
 * auth env var." and "auth is configured, but multiple auth env vars are
 * present". An inherited `OPENAI_API_KEY` would authenticate a gateway-bound run
 * as whoever the host shell is while the graph document and the journal's
 * request identity both went on reporting the mapped key.
 *
 * `baseUrl` claims nothing: the SDK turns it into a `--config
 * openai_base_url=…` override rather than a variable, and the pinned binary's
 * provider table carries no endpoint variable beside its built-in endpoint.
 * `headers:` has no slot at all on this harness — `validate` refuses a provider
 * declaring one for a `codex` node — so it has nothing to be a second spelling
 * of.
 */
const CODEX_CONNECTION_VARIABLES: Readonly<
  Record<keyof runtime.HarnessConnection, readonly string[]>
> = {
  baseUrl: [],
  credential: ["CODEX_API_KEY", "OPENAI_API_KEY", "CODEX_ACCESS_TOKEN"],
  headers: [],
};

/**
 * The environment one `codex` run is handed: the node's own, **minus every name
 * the spawned CLI reads for a fact the connection declares** (PRD resolved q58
 * rulings a and c, q54 ruling b).
 *
 * [`ccEnvironment`]'s subtraction, on this harness, and `inherit_env: true` is
 * why it is not redundant here either. `validate` refuses a node `env:` entry
 * spelling any name [`CODEX_CONNECTION_VARIABLES`] claims for a declared fact,
 * so the *declared* half of the environment arrives clean. The **inherited**
 * half never passed through `validate` at all: it is whatever shell started this
 * process, and a machine that runs `codex` interactively is exactly the machine
 * that has an `OPENAI_API_KEY` exported. The SDK writes only `CODEX_API_KEY` on
 * top, so without this a gateway-bound run would carry the host's key into a
 * CLI that treats two auth variables as an ambiguity — while `validate` stayed
 * clean and the journal's `connection` went on reporting the mapped one.
 *
 * **An undeclared fact claims nothing**, which is q25's keyless posture read
 * here rather than one surface along: a provider with no `api_key:` leaves the
 * whole auth family alone, so a node that inherits a shell holding
 * `OPENAI_API_KEY` keeps it — the connection says nothing about how this run
 * authenticates.
 *
 * The walk asks about a fact's **names first** and about the connection second,
 * which is the order Decision D143's honest narrowness reads in: a fact this row
 * claims nothing for scrubs nothing whatever the connection says, and `headers:`
 * on this harness is a fact `validate` refuses a composition over — so a driver
 * that went and read it would be carrying a fact the table says it cannot
 * (`a_driver_maps_exactly_the_connection_facts_its_row_names`). The
 * declared-ness test is written over the value rather than over the field for
 * the same reason, and it reads an empty map as declaring nothing exactly as the
 * compiler's own `declared` does.
 */
function codexEnvironment(run: runtime.HarnessRun): Record<string, string> {
  const held: Record<string, string> = { ...run.env };
  for (const [fact, names] of Object.entries(CODEX_CONNECTION_VARIABLES) as [
    keyof runtime.HarnessConnection,
    readonly string[],
  ][]) {
    if (names.length === 0) continue;
    const declared = run.connection[fact];
    if (declared === undefined) continue;
    if (typeof declared === "object" && Object.keys(declared).length === 0) continue;
    for (const name of names) delete held[name];
  }
  return held;
}

/**
 * The `CodexOptions` this run's client is built from: the scrubbed environment,
 * and the model's connection (grammar 8.9, Decisions D139, D143).
 *
 * **The environment** is handed to the SDK rather than inherited by it: the
 * Codex SDK documents that a provided `env` replaces `process.env` for the CLI
 * it spawns, which is exactly the scrubbed child PRD resolved q54 ruling b asks
 * for — and it is [`codexEnvironment`] rather than a spread, because the
 * inherited half of an `inherit_env: true` run can spell this harness's
 * credential under a name the SDK does not overwrite.
 *
 * **The connection** is this harness's own surface, and it is the *client's*
 * rather than a thread's: `baseUrl`, which the SDK passes to the CLI as
 * `--config openai_base_url=…`, and `apiKey`, which it sets as `CODEX_API_KEY`
 * in that same environment on its way past. There is **no header slot** on
 * either object, which is why a provider declaring `headers:` is refused at
 * `validate` for a node bound to this harness rather than quietly dropped here
 * (PRD resolved q58 ruling b) — a faked one would have meant composing a
 * `model_providers.*` config table the composition never wrote.
 *
 * An absent fact sets no key at all, resolved q25's posture: a keyless gateway
 * connection leaves `apiKey` undefined, and the SDK then sets no `CODEX_API_KEY`
 * for the CLI to authenticate with.
 *
 * **Exported for the reason [`codexOptions`] is**, and for one more: what this
 * object holds is the whole of where the run's traffic goes, and none of it is
 * visible from a run's answer or from the events the driver yields.
 *
 * It is built from a literal, from `run.connection`, and from the environment
 * [`codexEnvironment`] assembles out of `run.env` and that same connection.
 * Nothing on either path reads `run.settings`, because [`passthrough`] feeds the
 * **thread** and a key that could reach this object would be choosing the client
 * — `codexPathOverride` is on it, and so is the `config` escape hatch — which is
 * what `what_program_a_harness_run_is_cannot_be_chosen_by_a_settings_key` holds,
 * on this function and on the one it calls.
 */
export function codexClient(run: runtime.HarnessRun): CodexOptions {
  const connection = run.connection;
  return {
    env: codexEnvironment(run),
    ...(connection.baseUrl === undefined ? {} : { baseUrl: connection.baseUrl }),
    ...(connection.credential === undefined ? {} : { apiKey: connection.credential }),
  };
}

/**
 * The `ThreadOptions` one `codex` run is made of — the config map of grammar
 * 8.9, as one value (see [`CODEX_DRIVER`]).
 *
 * **Exported for the reason [`scriptedDriver`] is**, and the same reason
 * [`ccOptions`] is under the other harness: this object is where `workspace:`
 * and `access:` become this harness's own containment primitive, and none of it
 * is visible from a run's answer or from the events the driver yields. The
 * bound worth a test most of all is the [`CODEX_RESERVED`] drop, which is a
 * *subtraction* — what a `settings:` key did **not** put here — and a
 * subtraction can only be read off the object itself.
 */
export function codexOptions(run: runtime.HarnessRun): ThreadOptions {
  const options: ThreadOptions = {
    model: run.model,
    workingDirectory: run.workspace,
    sandboxMode: CODEX_SANDBOX[run.access],
    ...passthrough(run, CODEX_SETTINGS, CODEX_RESERVED),
  };
  const effort = settingText(run.modelSettings["reasoning_effort"]);
  if (effort !== undefined) {
    options.modelReasoningEffort = effort as ThreadOptions["modelReasoningEffort"];
  }
  const network = settingFlag(run.settings["network_access"]);
  if (network !== undefined) options.networkAccessEnabled = network;
  const search = settingText(run.settings["web_search"]);
  if (search !== undefined) options.webSearchMode = search as ThreadOptions["webSearchMode"];
  const skipGit = settingFlag(run.settings["skip_git_repo_check"]);
  if (skipGit !== undefined) options.skipGitRepoCheck = skipGit;
  return options;
}

/**
 * The turn one run sends: the node's instructions, the list it offers the
 * harness where it wrote one, and the bound input (see [`CODEX_DRIVER`]).
 *
 * The instructions lead, the way they do under the other harness, and the
 * vendor's own base instructions are untouched beneath them — a thread keeps
 * the agent loop it was post-trained with, which is why this is a kind at all
 * (PRD resolved q57).
 *
 * The offered list is stated as what it is: this harness bounds at the sandbox,
 * so the sentence is an instruction the model reads and not a bound. `cc` puts
 * the same list somewhere that holds; `docs/grammar.md` 8.9 and the graph
 * document's `tools_enforced` are where the asymmetry is written down.
 */
function codexTurn(run: runtime.HarnessRun): string {
  const offered =
    run.allowTools === undefined
      ? ""
      : `\n\nThe tools this run is offered: ${run.allowTools.join(", ")}. Use no others.`;
  return `${run.instructions}${offered}\n\n${run.input}`;
}

/**
 * One completed thread item, as a tool event — or `undefined` where the item is
 * not a tool at all.
 *
 * Four of the SDK's eight item types are tool events; the other four are the
 * agent's own message, its reasoning, its to-do list and a non-fatal error,
 * none of which is a call to anything. Their events still reach the payload:
 * this decides what the **trace** carries, not what the journal holds.
 */
function codexToolTap(item: ThreadItem): runtime.HarnessTap | undefined {
  switch (item.type) {
    case "command_execution":
      return {
        kind: "tool",
        name: "command_execution",
        outcome: item.status === "failed" ? "failed" : "completed",
        ...(item.status === "failed"
          ? { error: `the command exited ${item.exit_code ?? "without a status"}` }
          : {}),
      };
    case "file_change":
      return {
        kind: "tool",
        name: "file_change",
        outcome: item.status === "failed" ? "failed" : "completed",
        ...(item.status === "failed" ? { error: "the patch did not apply" } : {}),
      };
    case "mcp_tool_call":
      return {
        kind: "tool",
        name: `${item.server}/${item.tool}`,
        outcome: item.status === "failed" ? "failed" : "completed",
        ...(item.error === undefined ? {} : { error: item.error.message }),
      };
    case "web_search":
      return { kind: "tool", name: "web_search", outcome: "completed" };
    default:
      return undefined;
  }
}

/**
 * The agent's last message, as the value the gate is handed.
 *
 * The SDK documents an `agent_message`'s `text` as JSON when `outputSchema` was
 * asked for, so the text is decoded here. A text that is **not** JSON is handed
 * on as the string it is rather than being refused here: what an answer has to
 * be is the node's `output:` schema, and the gate is the one place that decides
 * it — a driver that refused first would report a decoding failure where the
 * composition's own contract has a message to give (PRD resolved q55 ruling c).
 */
function codexAnswer(text: string): unknown {
  try {
    return JSON.parse(text) as unknown;
  } catch {
    return text;
  }
}

/**
 * The drivers this composition uses, by harness — what `runtime.runCoder` resolves a `coder:` node's harness against.
 *
 * A harness with no driver here is one no node binds, and a run that reached one would be `runtime.HarnessUnavailable`: the adapter refuses at the call rather than dispatching into nothing.
 */
export const DRIVERS: runtime.HarnessDrivers = {
  cc: CC_DRIVER,
  codex: CODEX_DRIVER,
};
