// This file was generated by agent-compose 0.0.0-dev from `main.yml` (target `local`).
//
// It is a build artifact, not source: `agent-compose build` overwrites it,
// and `agent-compose build --check` fails when it has been edited. The spec
// is the single source of truth (PRD 5.12); to own this code instead, copy
// the whole directory out and stop regenerating it.
//
// Every schema the composition declares, lowered per grammar 3.8. These are the
// runtime contract: an agent's output is parsed with the schema named for it
// before any edge is evaluated, a tool's arguments are parsed with its input
// schema, and a state channel's type is the schema its channel is built from.

import { z } from "zod";

/**
 * The length `min_length` and `max_length` bound (grammar 3.4).
 *
 * JSON Schema counts a string's length in Unicode **code points**, and
 * `String.prototype.length` — which `.min()` and `.max()` count — is UTF-16
 * **code units**. Every character outside the BMP is one of the first and two of
 * the second, so the two disagree in both directions on any string carrying one:
 * `"😀"` is one code point and two units. Spreading a string iterates it by code
 * point, which is the rule the schema this composition published states.
 */
const codePoints = (value: string): number => [...value].length;

/** `flow.patch` — the module's parameters (grammar 7.5). */
export const flowPatchInputs = z.object({
  goal: z.string().refine((value) => codePoints(value) >= 1, { message: "expected at least 1 character" }).describe("What the change has to accomplish."),
}).strict();
export type FlowPatchInputs = z.infer<typeof flowPatchInputs>;

/**
 * `flow.patch` — the module's result, materialized from the state channels of the same names at quiescence (grammar 7.5, 7.6.3).
 */
export const flowPatchOutputs = z.object({
  summary: z.string().describe("What the last implementing run says it changed."),
}).strict();
export type FlowPatchOutputs = z.infer<typeof flowPatchOutputs>;

/**
 * `flow.patch` node `implement` — what the harness run is handed (grammar 8.9).
 */
export const flowPatchNodeImplementInput = z.object({
  goal: z.string(),
  feedback: z.string(),
}).strict();
export type FlowPatchNodeImplementInput = z.infer<typeof flowPatchNodeImplementInput>;

/**
 * `flow.patch` node `implement` — what the harness answers with, parsed in full by the output gate (grammar 8.9).
 */
export const flowPatchNodeImplementOutput = z.object({
  summary: z.string(),
  touched: z.array(z.string()).max(50),
}).strict();
export type FlowPatchNodeImplementOutput = z.infer<typeof flowPatchNodeImplementOutput>;

/** `flow.patch` node `review` — what the harness run is handed (grammar 8.9). */
export const flowPatchNodeReviewInput = z.object({
  goal: z.string(),
  summary: z.string(),
}).strict();
export type FlowPatchNodeReviewInput = z.infer<typeof flowPatchNodeReviewInput>;

/**
 * `flow.patch` node `review` — what the harness answers with, parsed in full by the output gate (grammar 8.9).
 */
export const flowPatchNodeReviewOutput = z.object({
  verdict: z.enum(["approve", "revise"]),
  feedback: z.string(),
}).strict();
export type FlowPatchNodeReviewOutput = z.infer<typeof flowPatchNodeReviewOutput>;

/** State channel `feedback` — its declared type (grammar 10.1). */
export const stateFeedback = z.string().describe("The reviewing run's most recent notes, fed back into the next pass.").default("");
export type StateFeedback = z.infer<typeof stateFeedback>;

/** State channel `summary` — its declared type (grammar 10.1). */
export const stateSummary = z.string().describe("What the implementing run says it changed.").default("");
export type StateSummary = z.infer<typeof stateSummary>;
