// This file was generated by agent-compose 0.0.0-dev from `main.yml` (target `local`).
//
// It is a build artifact, not source: `agent-compose build` overwrites it,
// and `agent-compose build --check` fails when it has been edited. The spec
// is the single source of truth (PRD 5.12); to own this code instead, copy
// the whole directory out and stop regenerating it.
//
// The composition's declared triggers (grammar 13, PRD 5.11).
//
// `./serve.ts` is the app; `httpTriggers` is the table it serves. Beside it,
// `manualTriggers` is what `./cli.ts` reads: a `manual` trigger declares no
// route — invocation from the CLI is universal and needs no trigger (Decision
// D64) — but it may declare the `session_key:` that remaps `--session` into the
// session identity a `scope: session` store partitions by (grammar 13.2, 11.3).
//
// `schedule` and `event` are reserved grammar that executes as a no-op in v0
// (grammar 15), and neither appears in either table.

import * as runtime from "./runtime.ts";

/**
 * The payload shape grammar 13.3 fixes, as the emitted evaluator reads it.
 *
 * The same declaration the validator typed every trigger expression against, so
 * an expression it accepted binds here through the same types.
 */
const httpPayload: runtime.Shape = {
  properties: {
    body: { properties: {}, rest: "any" },
    query: { properties: {}, rest: "string" },
    headers: { properties: {}, rest: "string" },
    path: "string",
    method: "string",
  },
};

/** One declared `http` trigger (grammar 13.3). */
export interface HttpTrigger {
  /** The trigger's own name, which is what a diagnostic and a report call it. */
  readonly name: string;
  /** `flow:` — the execution's entry module. */
  readonly flow: string;
  /** `path:` — the route, defaulting to `/triggers/<name>`. */
  readonly path: string;
  /** `method:` — defaulting to `POST`. */
  readonly method: "GET" | "POST" | "PUT";
  /** `respond:` — defaulting to `async`. */
  readonly respond: "sync" | "async";
  /** `timeout:` — the sync response budget, in milliseconds (`sync` only). */
  readonly timeoutMs?: number;
  /**
   * Whether the app decodes a body for this route.
   *
   * `false` on a `GET`, which has none: `payload.body` is then `{}` — present
   * and readable, so `has(payload.body.goal)` answers `false` instead of
   * erroring (Decision D117).
   */
  readonly readsBody: boolean;
  /** `input:` — the flow inputs this trigger binds from one payload. */
  input(payload: unknown): Record<string, unknown>;
  /** `session_key:` — the session identity for session-scoped stores (grammar 11.3). */
  sessionKey?(payload: unknown): string;
  /** `callback:` — the completion webhook, on an `async` trigger. */
  callback?(payload: unknown): string;
  /**
   * `auth:` — how a caller of this trigger is verified, and with it the resume
   * and status routes of every execution it starts (grammar 13.3, PRD resolved
   * q32).
   *
   * Absent leaves all three routes open.
   */
  readonly auth?: InboundAuth;
  /** `callback_auth:` — how a delivery identifies itself (grammar 13.3). */
  readonly callbackAuth?: CallbackAuth;
  /**
   * `callback_allow:` — where a callback may point.
   *
   * Absent is the documented test posture: the trigger signs nothing and may
   * POST anywhere. Present, it is matched when the URL is *read* — at the
   * delivery, not at the start — because the URL comes out of the request
   * payload and is attacker-controlled by construction (Decision D110, D127).
   */
  readonly callbackAllow?: readonly string[];
}

/**
 * The inbound scheme a trigger enforces, with every grammar 13.3 default
 * already applied.
 *
 * Resolved rather than recorded-as-written, unlike `path:` and `method:`: every
 * parameter that decides whether a credential verifies carries the value the
 * trigger enforces, because a verifier that re-derived a default and got it
 * wrong would not fail a build — it would accept the wrong request.
 */
export type InboundAuth =
  | {
      readonly scheme: "bearer";
      /** Matched case-insensitively; HTTP/2 lowercases every name (grammar 13.3). */
      readonly header: string;
      readonly prefix: string;
      /** The **variable name** holding the expected token; never the token. */
      readonly tokenEnv: string;
    }
  | {
      readonly scheme: "hmac";
      readonly header: string;
      readonly algorithm: "sha1" | "sha256" | "sha512";
      readonly encoding: "hex" | "base64";
      readonly prefix: string;
      /** The **variable name** holding the signing key; never the key. */
      readonly secretEnv: string;
    };

/**
 * The outbound identity a delivery carries (grammar 13.3, PRD resolved q33).
 *
 * At least one half is present, and both together are legal: a receiver that
 * checks a token and a receiver that verifies a signature are two receivers.
 * Outbound signing takes no parameters — HMAC-SHA256 in hex under
 * `X-AgentCompose-Signature` — so one receiver-side recipe verifies every
 * agent-compose deployment.
 */
export interface CallbackAuth {
  readonly bearer?: {
    readonly header: string;
    readonly prefix: string;
    readonly tokenEnv: string;
  };
  readonly hmac?: { readonly secretEnv: string };
}

/**
 * The payload shape grammar 13.2 fixes for a `manual` trigger: one member.
 *
 * "The manual payload has exactly one member — `payload.session`, the CLI's
 * `--session <key>`", which is also what the validator types a manual trigger's
 * `session_key:` against.
 */
const manualPayload: runtime.Shape = { properties: { session: "string" } };

/** The roots an `http` trigger's expressions are evaluated against. */
function roots(payload: unknown): runtime.Roots {
  return { payload: runtime.bind(payload, httpPayload) };
}

/** The roots a `manual` trigger's `session_key:` is evaluated against. */
function manualRoots(session: string): runtime.Roots {
  return { payload: runtime.bind({ session }, manualPayload) };
}

/** One trigger expression whose declared result type is `string`. */
function text(source: string, bound: runtime.Roots, site: string): string {
  const answer = runtime.toJson(runtime.evaluate(source, bound));
  if (typeof answer !== "string") {
    throw new runtime.CelError(`${site} answered ${JSON.stringify(answer)} rather than a string`);
  }
  return answer;
}

/**
 * One declared `manual` trigger (grammar 13.2).
 *
 * It contributes no route and gates nothing: `./cli.ts` runs any flow this
 * composition declares, named or not (Decision D64). The entry exists for the
 * one key that changes what a CLI run *does* — `session_key:`.
 */
export interface ManualTrigger {
  /** The trigger's own name, which is what a diagnostic and a report call it. */
  readonly name: string;
  /** `flow:` — the CLI entry this trigger describes. */
  readonly flow: string;
  /**
   * `session_key:` — the declared remap of `--session`, when there is one.
   *
   * Absent where the trigger declares none, which is the key's own
   * `"payload.session"` default: the argument *is* the identity, and evaluating
   * an expression to say so would answer what was passed in.
   */
  sessionKey?(session: string): string;
}

export const httpTriggers: readonly HttpTrigger[] = [
];

export const manualTriggers: readonly ManualTrigger[] = [
  {
    name: "cli",
    flow: "flow.patch",
  },
];
