// This file was generated by agent-compose 0.1.0 from `main.yml` (target `staging`).
//
// It is a build artifact, not source: `agent-compose build` overwrites it,
// and `agent-compose build --check` fails when it has been edited. The spec
// is the single source of truth (PRD 5.12); to own this code instead, copy
// the whole directory out and stop regenerating it.
//
// The project's own command line: what `agent-compose run` and
// `agent-compose serve` launch (PRD 5.11, grammar 13.2).
//
// The compiler builds this directory and then runs it — `bun src/index.ts run
// flow.review --input goal=…`, or `node src/index.ts` under the fallback — which
// is the same launch surface the emitted `README.md` documents. Nothing about
// invoking a compiled graph lives in the Rust binary: it validates, it builds,
// it checks the environment, and it starts this.
//
// ```text
// src/index.ts run <flow> [--input k=v]... [--session <key>] [--format human|json]
// src/index.ts serve [--host <host>] [--port <port>]
// ```
//
// # What `run` prints
//
// **stdout carries the answer, stderr carries the report.** A flow's `outputs:`
// is a declared schema, so the answer is one JSON object — the only shape that
// survives the schema's own types — and a caller can read it without parsing
// prose. Under `--format json` the answer grows into the whole record: the
// execution id, the outputs, and the routing trace of PRD 5.3, so a machine
// reading one document gets everything a human reads across two.
//
// The trace is also written to a file under the project's data directory and its
// path is named on stderr, because a run of any size produces more of it than a
// terminal is useful for. The file is a whole `runtime.TraceDocument` rather than
// a bare list of entries: it is the one surface that arrives without the record
// around it, so it carries its own `trace_version` (`docs/trace.md`), the flow,
// the execution id and how the run ended.
//
// Both machine surfaces carry that version — the JSON record beside its `trace`,
// the file at the head of its envelope — so a reader pins one number and knows
// which fields it may rely on. The **human** report is not one of them: it is a
// summary written for a terminal, and `docs/trace.md` says outright that nothing
// should be parsed out of it.
//
// # Why `--input` values are coerced
//
// A CLI argument is text and a flow's `inputs:` is typed (grammar 13.2: "a value
// that does not fit the declared type fails the run naming the field"). So each
// value is read as the field's declared kind — an integer field takes `3`, a
// boolean takes `true`, an object or array takes JSON — and a value that cannot
// be read that way fails the run naming the field rather than reaching Zod as a
// string and failing about a type the author never wrote.
//
// # A run that stops at a `human` node
//
// `run` cannot answer a pause: resume is an invocation and the generated app is
// what exposes it (PRD 5.11), so a run that reaches a `human` node reports what
// it reached and exits `3` — its own code, beside `1` for a run that produced no
// answer and `2` for a command that could not be run. The trace document is
// still written, with `status: "interrupted"`; the entry of the node it stopped
// at carries the pause, and `agent-compose serve` is where the question gets
// answered.
//
// Grammar 13.2 puts three failures in one sentence — "an unknown argument name,
// a missing REQUIRED field, or a value that does not fit the declared type fails
// the run naming the field" — so all three are one kind of failure here: the
// arguments are held to the flow's own schema **before** the run starts, and a
// set that does not fit is a command that could not run (exit `2`) rather than a
// run that produced no answer.
//
// # `--session` and the remap a `manual` trigger may declare
//
// `--session <key>` is the manual payload's one member (grammar 13.2). A
// declared `manual` trigger naming this flow may carry a `session_key:`, and
// that expression — over that one-member payload — is what turns the argument
// into the identity a `scope: session` store partitions by (grammar 11.3). Left
// undeclared it is `"payload.session"`, the argument itself.
//
// A flow that reaches a `scope: session` store cannot run without one, and
// grammar 11.3 says where that is decided: "supplying the value is a run-time
// requirement (`--session`), checked at run start like env-ref presence (§4.3)".
// So it is decided here, beside the arguments — an invocation missing it is a
// command that could not run (exit `2`), not a run that produced no answer.

import fs from "node:fs";
import path from "node:path";
import process from "node:process";

import { type CompiledFlow, type FlowRun, flows, runFlow, sessionRefusal } from "./graph.ts";
import { TRACE_VERSION, interruptOf } from "./runtime.ts";
import type * as runtime from "./runtime.ts";
import { dataRoot } from "./stores.ts";
import { httpTriggers, manualTriggers } from "./triggers.ts";

/** What a `--format` selects. */
type Format = "human" | "json";

/** A usage error: the command could not run, which is the caller's to fix. */
class UsageError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "UsageError";
  }
}

/**
 * Run the command line, flush what it wrote, and end the process.
 *
 * The exit is explicit rather than left to the event loop draining: a provider
 * connection `fetch` kept alive outlives the work that opened it, and a run that
 * had already printed its answer would sit there until the socket timed out. The
 * streams are flushed first, because `process.exit` truncates a pipe that is
 * still holding bytes — and stdout is a pipe whenever a caller is reading the
 * outputs, which is the case this exists for.
 *
 * `serve` never comes back through here: its app owns the process.
 */
export async function runMain(argv: readonly string[]): Promise<void> {
  const code = await main(argv);
  await flush();
  process.exit(code);
}

/** Wait for what has been written to leave the process. */
async function flush(): Promise<void> {
  for (const stream of [process.stdout, process.stderr]) {
    if (stream.writableLength === 0) continue;
    await new Promise<void>((resolve) => {
      stream.write("", () => resolve());
    });
  }
}

/**
 * Run the project's own command line, and answer with the exit code.
 *
 * `0` is a clean run, `1` is a run that produced no answer, `2` is a command
 * that could not run at all, and `3` is a run that stopped at a `human` pause —
 * the same four meanings `agent-compose` itself gives them, so a caller reads
 * one table rather than two.
 *
 * `3` is a code of its own rather than a shade of `1` because the three ask for
 * different things. `2` is an invocation to fix and `1` is a run to look into;
 * this is neither — the run did everything it was asked to and is holding a
 * question, and what closes it is a person answering through `serve`'s resume
 * route (grammar 8.7, PRD 5.11). A supervisor that retried `1` would re-run a
 * graph whose effects have already happened, and one that reported `2` would
 * send someone to look at the command line.
 */
export async function main(argv: readonly string[]): Promise<number> {
  const [verb, ...rest] = argv;
  try {
    if (verb === "run") return await run(rest);
    if (verb === "serve") return await serveVerb(rest);
    throw new UsageError(
      `\`${verb ?? ""}\` is not a verb of this project: it takes \`run\` or \`serve\` (see README.md)`,
    );
  } catch (error) {
    if (error instanceof UsageError) {
      process.stderr.write(`error: ${error.message}\n`);
      return 2;
    }
    throw error;
  }
}

/** `run <flow> [--input k=v]... [--session <key>] [--format human|json]`. */
async function run(argv: readonly string[]): Promise<number> {
  const [address, ...rest] = argv;
  if (address === undefined) {
    throw new UsageError("`run` takes a flow address: `run flow.<name> [--input k=v]...`");
  }
  const flow = flows[address];
  if (flow === undefined) {
    throw new UsageError(
      `\`${address}\` is not a flow of this composition: ${Object.keys(flows).join(", ")}`,
    );
  }

  const options = parse("run", rest, {
    input: "repeatable",
    session: "single",
    format: "single",
  });
  const inputs = bindInputs(flow, options.repeated["input"] ?? []);
  const session = sessionOf(flow, options.single["session"] ?? "");
  const format = formatOf(options.single["format"]);
  requireSession(address, flow, session);

  // Minted here rather than left to `runFlow`, because this command needs it on
  // both of its ways out: it is what makes the trace file's name unique (see
  // [`writeTrace`]), and a failed run has no `FlowRun` to read one back off.
  const execution = `exec_${globalThis.crypto.randomUUID()}`;

  let produced: FlowRun;
  try {
    produced = await runFlow(address, inputs, { executionId: execution, sessionKey: session });
  } catch (error) {
    const trace = (error as { trace?: readonly runtime.TraceEntry[] }).trace ?? [];
    // A run that stopped at a `human` pause is not a run that failed, and the
    // whole way out is written for that difference: its own document `status`,
    // its own exit code, and a message that says where the answer goes rather
    // than what went wrong (grammar 8.7, PRD 5.11). `runFlow` raises it as a
    // `FlowFailure` like any other — nothing else about a parked run is
    // different — so it is recognized by what is on the chain rather than by
    // what class arrived.
    const interrupt = interruptOf(error);
    const status = interrupt === undefined ? "failed" : "interrupted";
    const reason = interrupt === undefined ? describe(error) : describe(interrupt);
    const written = writeTrace(address, execution, status, trace, reason);
    if (format === "json") {
      // The same record the completed run answers with, `error` where its
      // `outputs` would be — the trace file's path included, because a run that
      // failed is the one a reader most wants the whole trace for.
      process.stdout.write(
        `${JSON.stringify(
          {
            flow: address,
            execution_id: execution,
            status,
            error: reason,
            trace_version: TRACE_VERSION,
            trace,
            ...(written === undefined ? {} : { trace_path: written }),
          },
          null,
          2,
        )}\n`,
      );
    } else {
      process.stderr.write(render(trace));
      process.stderr.write(`\n${reason}\n`);
      if (interrupt === undefined) {
        for (let cause: unknown = (error as { cause?: unknown }).cause; cause !== undefined; ) {
          process.stderr.write(`  cause: ${describe(cause)}\n`);
          cause = (cause as { cause?: unknown }).cause;
        }
      }
      if (written !== undefined) process.stderr.write(`\ntrace: ${written}\n`);
    }
    return interrupt === undefined ? 1 : 3;
  }

  const written = writeTrace(address, execution, "completed", produced.trace);
  if (format === "json") {
    process.stdout.write(
      `${JSON.stringify(
        {
          flow: address,
          execution_id: execution,
          status: "completed",
          outputs: produced.outputs,
          trace_version: TRACE_VERSION,
          trace: produced.trace,
          ...(written === undefined ? {} : { trace_path: written }),
        },
        null,
        2,
      )}\n`,
    );
    return 0;
  }
  process.stdout.write(`${JSON.stringify(produced.outputs, null, 2)}\n`);
  process.stderr.write(render(produced.trace));
  if (written !== undefined) process.stderr.write(`\ntrace: ${written}\n`);
  return 0;
}

/** `serve [--host <host>] [--port <port>]`. */
async function serveVerb(argv: readonly string[]): Promise<number> {
  const options = parse("serve", argv, { host: "single", port: "single" });
  const port = options.single["port"];
  if (port !== undefined && !/^[0-9]+$/.test(port)) {
    throw new UsageError(`\`--port ${port}\` is not a port number`);
  }
  // Loaded here rather than imported at the top, so a `run` never pays for the
  // HTTP framework and a project used as a library never loads it at all. Only
  // the app: `./triggers.ts` is the composition's own table and is imported
  // above, because `run` reads it too.
  const { serve } = await import("./serve.ts");
  if (httpTriggers.length === 0) {
    throw new UsageError(
      "this composition declares no `http` triggers, so the generated app exposes no routes: declare one in `triggers:` (grammar 13.3)",
    );
  }
  const host = options.single["host"] ?? "127.0.0.1";
  try {
    await serve({
      host,
      ...(port === undefined ? {} : { port: Number(port) }),
    });
  } catch (error) {
    // Everything that keeps the app from *starting* is the same kind of failure
    // as a bad flag: the address is taken, the port needs a privilege this
    // process does not have, the host does not resolve. Answering with a
    // framework stack trace and `1` would report "a run produced no answer",
    // which is the one thing that did not happen — nothing ran. So it is a `2`
    // with a sentence, like every other command that could not be run.
    //
    // One of them is not about the address at all, and saying it was would send
    // a reader to look at a port that is fine. Routes are registered when the
    // app is made ready, which `listen` does, so a **route collision** arrives
    // here too — and it is the composition's, not the machine's: two `http`
    // triggers whose paths the compiler could not tell apart (a parameter's
    // *name* differs, and grammar 13.3 has the router read parameters
    // unexamined), or one claiming a route the app mounts for itself. The
    // compiler refuses every collision it can decide; this is what the router
    // decides, reported as what it is.
    if ((error as { code?: unknown } | null)?.code === "FST_ERR_DUPLICATED_ROUTE") {
      throw new UsageError(
        `the app could not mount its routes: ${describe(error)}. Two routes of this composition are one route to the router — an \`http\` trigger's \`path:\` and \`method:\`, or one of the app's own \`GET /executions/:id\` and \`POST /executions/:id/resume\` — so give one of them a path the other cannot be read as (grammar 13.3)`,
      );
    }
    throw new UsageError(
      `the app could not listen on ${host}:${port ?? 0}: ${describe(error)}`,
    );
  }
  // The app owns the process from here: `serve` never returns on its own, and
  // the signal handlers it installed are what end it.
  await new Promise<void>(() => {});
  return 0;
}

/** The `--input k=v` arguments, read as the flow's declared field types. */
function bindInputs(flow: CompiledFlow, given: readonly string[]): Record<string, unknown> {
  const inputs: Record<string, unknown> = {};
  for (const argument of given) {
    const split = argument.indexOf("=");
    if (split <= 0) {
      throw new UsageError(`\`--input ${argument}\` is not \`field=value\``);
    }
    const field = argument.slice(0, split);
    const text = argument.slice(split + 1);
    if (!flow.inputs.includes(field)) {
      throw new UsageError(
        flow.inputs.length === 0
          ? `\`${flow.address}\` declares no \`inputs:\`, so it takes no \`--input ${field}=…\``
          : `\`${field}\` is not an input of \`${flow.address}\`: it declares ${flow.inputs.join(", ")}`,
      );
    }
    inputs[field] = coerce(flow, field, text);
  }
  // …and then the whole set against the flow's own `inputs:` schema, which is
  // what decides the other two failures grammar 13.2 names in the same sentence
  // as the unknown-argument one above: a REQUIRED field nobody passed, and a
  // value the field's declared type refuses past the kind it was read as (an
  // `enum` variant that is not one, a string below its `min_length`, a JSON
  // document whose properties are not the declared ones). `runFlow` parses with
  // the same schema and would refuse the same set — but as a *run* that produced
  // no answer, which is not what happened: nothing ran. Asked here, all three
  // are one usage error naming the field.
  try {
    flow.parse(inputs);
  } catch (error) {
    // `CompiledFlow.parse` reports through `runtime.parseResult`, whose message
    // is already the sentence this wants; the class name it would carry through
    // [`describe`] belongs to a stack trace rather than to a usage line.
    throw new UsageError(error instanceof Error ? error.message : String(error));
  }
  return inputs;
}

/**
 * The session identity this run addresses (grammar 13.2, 11.3).
 *
 * `--session <key>` is the whole manual payload — "the manual payload has
 * exactly one member — `payload.session`" — and a declared `manual` trigger
 * naming this flow may remap it through `session_key:`. Left undeclared, the key
 * is its own `"payload.session"` default and the argument is the identity, so
 * there is nothing to evaluate.
 *
 * **An argument that was not passed is not remapped.** `--session` is what
 * grammar 13.2 makes mandatory for a run whose flow reaches a session-scoped
 * store, and a remap of nothing would answer with something — `'tenant-' +
 * payload.session` is `"tenant-"` for the run nobody gave a session — which is a
 * partition named after an identity that does not exist. So the empty argument
 * passes through as itself and [`requireSession`] refuses the run naming the
 * store.
 *
 * Which remap applies is not a choice: two `manual` triggers naming one flow may
 * not declare different `session_key:` expressions, and the compiler refuses a
 * composition where they do.
 */
function sessionOf(flow: CompiledFlow, given: string): string {
  if (given === "") return "";
  for (const trigger of manualTriggers) {
    if (trigger.flow !== flow.address) continue;
    const remap = trigger.sessionKey;
    if (remap === undefined) continue;
    try {
      return remap(given);
    } catch (error) {
      throw new UsageError(
        `\`--session ${given}\` could not be read as this run's session identity: ${describe(error)}`,
      );
    }
  }
  return given;
}

/**
 * Refuse a `run` whose flow needs a session identity and was given none
 * (grammar 11.3, 13.2).
 *
 * A **usage** error, so the command exits `2` rather than `1`. The three
 * failures grammar 13.2 puts in one sentence — an unknown argument name, a
 * missing REQUIRED field, a value that does not fit — are already decided here
 * for that reason, and this is the fourth of the same kind: an argument the
 * caller has to add before anything can run. Grammar 11.3 says so itself,
 * likening the check to env-ref presence (§4.3) — which is a `2` in this
 * project's exit-code table, where `1` means a run produced no answer and `2`
 * means the command could not be run at all. Nothing ran here, and a supervisor
 * that retries `1` and reports `2` would otherwise retry an invocation that
 * cannot succeed however many times it is repeated.
 *
 * `runFlow` keeps the same guard for the callers this one cannot stand in for: a
 * `serve` request, whose session key is the request's rather than the command
 * line's, and an ejected caller invoking a compiled flow directly. There it
 * really is one run that failed.
 */
function requireSession(address: string, flow: CompiledFlow, session: string): void {
  if (session !== "" || flow.sessionStores.length === 0) return;
  throw new UsageError(sessionRefusal(address, flow.sessionStores));
}

/** One `--input` value, as the kind the field declares (grammar 13.2). */
function coerce(flow: CompiledFlow, field: string, text: string): unknown {
  const kind = flow.inputKinds[field] ?? "string";
  if (kind === "string") return text;
  if (kind === "boolean") {
    if (text === "true") return true;
    if (text === "false") return false;
    throw new UsageError(`\`--input ${field}=${text}\`: \`${field}\` is a boolean, so it takes \`true\` or \`false\``);
  }
  if (kind === "integer" || kind === "number") {
    const value = Number(text);
    if (!Number.isFinite(value) || (kind === "integer" && !Number.isInteger(value))) {
      throw new UsageError(`\`--input ${field}=${text}\`: \`${field}\` is ${kind === "integer" ? "an integer" : "a number"}`);
    }
    return value;
  }
  try {
    return JSON.parse(text) as unknown;
  } catch {
    throw new UsageError(
      `\`--input ${field}=${text}\`: \`${field}\` is a structured field, so its value is read as JSON`,
    );
  }
}

/** Whether an option may be given more than once. */
type Arity = "single" | "repeatable";

/**
 * The flags one verb takes: `--name value`, some repeatable.
 *
 * The verb declares **every** option it takes, and a `--name` outside that list
 * is a usage error rather than an entry nothing ever reads. That is D50's
 * posture — a typo is a diagnostic, never a silent no-op — applied to the one
 * surface the compiler does not stand in front of: `agent-compose run` is
 * shielded by its own argument parser, but an ejected project's command line is
 * this function, and `--fromat json` answering with human output and exit `0`
 * is a caller parsing the wrong document with nothing to tell it so.
 *
 * The options are declared in the order the README documents them, because that
 * order is what the refusal lists back.
 */
function parse(
  verb: string,
  argv: readonly string[],
  options: Readonly<Record<string, Arity>>,
): { single: Record<string, string>; repeated: Record<string, string[]> } {
  const single: Record<string, string> = {};
  const repeated: Record<string, string[]> = {};
  for (let index = 0; index < argv.length; index += 1) {
    const argument = argv[index]!;
    if (!argument.startsWith("--")) {
      throw new UsageError(`\`${argument}\` is not an option: every argument after the verb is \`--name value\``);
    }
    const name = argument.slice(2);
    // `Object.hasOwn` rather than a lookup: every object carries `constructor`
    // and `toString`, so `--constructor x` would read an inherited function as
    // this option's arity and be accepted as one — the same property-versus-key
    // confusion the compiler refuses a *channel* named `constructor` over.
    const arity = Object.hasOwn(options, name) ? options[name] : undefined;
    if (arity === undefined) {
      const taken = Object.keys(options).map((option) => `\`--${option}\``);
      throw new UsageError(
        `\`--${name}\` is not an option of \`${verb}\`: it takes ${taken.length === 0 ? "no options" : taken.join(", ")} (see README.md)`,
      );
    }
    const value = argv[index + 1];
    if (value === undefined) throw new UsageError(`\`--${name}\` takes a value`);
    index += 1;
    if (arity === "repeatable") {
      (repeated[name] ??= []).push(value);
    } else {
      single[name] = value;
    }
  }
  return { single, repeated };
}

function formatOf(given: string | undefined): Format {
  if (given === undefined || given === "human") return "human";
  if (given === "json") return "json";
  throw new UsageError(`\`--format ${given}\` is not one of \`human\`, \`json\``);
}

/**
 * Write the run's whole trace beside the project's data, and answer where.
 *
 * A trace is the routing record PRD 5.3 asks for and it grows with the run, so
 * the terminal gets a summary and the file gets everything.
 *
 * What lands is a `runtime.TraceDocument` — the **envelope** of `docs/trace.md`,
 * not a bare array of entries. A file is the one delivery surface that arrives
 * on its own: the JSON record `--format json` prints already names the flow, the
 * execution and the version around its `trace`, and a reader who opens the file
 * a month later has none of that unless the file carries it. `trace_version` is
 * the load-bearing half — a reader pins it and knows which fields it may rely on
 * — and `flow`, `execution_id` and `status` are what tie the document back to
 * the run without parsing the file's own name.
 *
 * The name is the flow's and the **execution id**, not a timestamp: two runs of
 * one flow started together — which is what a shell loop and a CI matrix both
 * do — land in the same millisecond often enough that a `Date.now()` name is a
 * run silently overwriting another's record while both print the same path. The
 * id is unique per execution by construction, and it is also the one thing that
 * ties the file to the run that wrote it.
 */
function writeTrace(
  address: string,
  execution: string,
  status: "completed" | "failed" | "interrupted",
  trace: readonly runtime.TraceEntry[],
  error?: string,
): string | undefined {
  // A run that failed before it started made no routing decisions, and an empty
  // file named as a trace would be a file a reader opens for nothing.
  if (trace.length === 0) return undefined;
  try {
    const directory = path.join(dataRoot(), "traces");
    fs.mkdirSync(directory, { recursive: true });
    const file = path.join(
      directory,
      `${address.replace(/[^A-Za-z0-9_.-]/g, "_")}-${execution.replace(/[^A-Za-z0-9_.-]/g, "_")}.json`,
    );
    const document: runtime.TraceDocument = {
      trace_version: TRACE_VERSION,
      flow: address,
      execution_id: execution,
      status,
      ...(error === undefined ? {} : { error }),
      entries: trace,
    };
    fs.writeFileSync(file, `${JSON.stringify(document, null, 1)}\n`);
    return file;
  } catch {
    // A data directory that cannot be written is not a reason to lose a run that
    // otherwise succeeded; stdout still carries the answer.
    return undefined;
  }
}

/** The human report: one line per node, plus what its model and stores did. */
function render(trace: readonly runtime.TraceEntry[]): string {
  let text = "";
  for (const entry of trace) {
    text += `step ${entry.step}  ${entry.flow} \`${entry.node}\`  ${entry.outcome} (${entry.attempts} attempt(s))\n`;
    for (const call of entry.models ?? []) {
      // PRD 5.9's own phrasing: failover is data a reader can see, not
      // behaviour they have to infer from a provider's own logs.
      const served =
        call.servedBy === undefined
          ? // Nothing answered it: the ladder ran out, and the member whose
            // refusal ended it is what stands in for "served by".
            `refused by ${call.refused?.model ?? "every member"}`
          : call.fallback === 0
            ? `served by ${call.servedBy}`
            : `served by ${call.servedBy}, fallback #${call.fallback}`;
      const after =
        call.failovers.length === 0
          ? ""
          : ` after ${call.failovers.map((one) => `${one.model}: ${one.condition}`).join(", ")}`;
      text += `    model ${call.model} — ${served}${after}\n`;
    }
    for (const store of entry.stores ?? []) {
      const key = store.key === undefined ? "" : ` key=${JSON.stringify(store.key)}`;
      const deduped = store.deduped === true ? " (deduped)" : "";
      text += `    store ${store.store} ${store.op}${key} [${store.effect}, ${store.via}]${deduped}\n`;
    }
    if (entry.human !== undefined) {
      const pause = entry.human;
      const until = pause.expiresAt === undefined ? "no deadline" : `until ${pause.expiresAt}`;
      const how =
        pause.settled === undefined
          ? "still waiting when the run ended"
          : `${pause.settled} at ${pause.settledAt}`;
      text += `    human — paused at ${pause.pausedAt} (${until}), ${how}\n`;
    }
    for (const decision of entry.routing?.edges ?? []) {
      const guard = decision.when === undefined ? (decision.else === true ? "else" : "always") : decision.when;
      text += `    edge → ${decision.to}  ${decision.taken ? "taken" : "untaken"}  ${guard}\n`;
    }
    if (entry.error !== undefined) text += `    error: ${entry.error}\n`;
  }
  return text;
}

function describe(error: unknown): string {
  return error instanceof Error ? `${error.name}: ${error.message}` : String(error);
}
