// This file was generated by agent-compose 0.0.0-dev from `main.yml` (target `staging`).
//
// It is a build artifact, not source: `agent-compose build` overwrites it,
// and `agent-compose build --check` fails when it has been edited. The spec
// is the single source of truth (PRD 5.12); to own this code instead, copy
// the whole directory out and stop regenerating it.
//
// Every `${ENV}` reference the composition makes, and `readEnvironment()`, the
// presence check over them (PRD 5.9, grammar 4.3). `./index.ts` is what calls
// it, at module scope, so loading this project is what checks its environment.
// No value is baked in here: the spec never contains a credential, and neither
// does this file — `agent-compose build` resolved nothing.

import process from "node:process";

/** One `${ENV}` reference, and the surfaces that wrote it. */
export interface EnvironmentReference {
  /** The variable name, between the braces. */
  readonly name: string;
  /** Where it is referenced, as spec addresses. */
  readonly sites: readonly string[];
}

/**
 * Every reference this composition makes, sorted by name.
 *
 * This is also the least-privilege list of PRD 5.9: a deployment of this graph
 * needs these variables and no others.
 */
export const environmentReferences: readonly EnvironmentReference[] = [
  {
    name: "ANTHROPIC_API_KEY",
    sites: [
      "provider.anthropic.api_key",
    ],
  },
  {
    name: "CHROMA_URL",
    sites: [
      "deploy.storage_backends.aliases.docs_db.url",
    ],
  },
  {
    name: "DEPLOY_ENV",
    sites: [
      "flow.triage.node.announce_failed.exec.args[1]",
    ],
  },
  {
    name: "JOURNAL_URL",
    sites: [
      "deploy.journal.url",
    ],
  },
  {
    name: "LOCAL_LLM_KEY",
    sites: [
      "provider.local.api_key",
    ],
  },
  {
    name: "LOCAL_LLM_URL",
    sites: [
      "provider.local.base_url",
    ],
  },
  {
    name: "MESH_JOIN_TOKEN",
    sites: [
      "deploy.hub.join_token",
    ],
  },
  {
    name: "NPM_CORP_TOKEN",
    sites: [
      "deploy.package_registry.scopes.@corp.token",
    ],
  },
  {
    name: "NPM_MIRROR_TOKEN",
    sites: [
      "deploy.package_registry.token",
    ],
  },
  {
    name: "OPS_BIN",
    sites: [
      "flow.triage.node.announce_failed.exec.command",
    ],
  },
  {
    name: "QUEUE_HOST",
    sites: [
      "flow.triage.node.announce.http.url",
      "flow.triage.node.escalate.http.url",
      "tool.dead_letter.http.url",
      "tool.review_queue.http.url",
    ],
  },
  {
    name: "QUEUE_TOKEN",
    sites: [
      "flow.triage.node.announce.http.headers.authorization",
      "flow.triage.node.escalate.http.headers.authorization",
      "tool.dead_letter.http.headers.authorization",
      "tool.review_queue.http.headers.authorization",
    ],
  },
  {
    name: "REDIS_URL",
    sites: [
      "deploy.event_sources.bug_reports.url",
    ],
  },
  {
    name: "REPO_ROOT",
    sites: [
      "flow.triage.node.verify.exec.cwd",
    ],
  },
  {
    name: "TRACE_SINK_TOKEN",
    sites: [
      "deploy.trace_sink.auth.bearer.token",
    ],
  },
  {
    name: "TRIAGE_HOST",
    sites: [
      "flow.enrich.node.fetch.http.url",
    ],
  },
  {
    name: "TRIAGE_MEMORY_URL",
    sites: [
      "deploy.storage_backends.defaults.kv.url",
    ],
  },
  {
    name: "TRIAGE_TOKEN",
    sites: [
      "flow.enrich.node.fetch.http.headers.authorization",
    ],
  },
];

/** Raised when the process starts without a variable the composition needs. */
export class MissingEnvironmentError extends Error {
  /** Every variable that was missing, sorted by name. */
  readonly missing: readonly EnvironmentReference[];

  constructor(missing: readonly EnvironmentReference[]) {
    const detail = missing
      .map((reference) => `${reference.name} (referenced by ${reference.sites.join(", ")})`)
      .join("; ");
    super(`missing environment ${missing.length === 1 ? "variable" : "variables"}: ${detail}`);
    this.name = "MissingEnvironmentError";
    this.missing = missing;
  }
}

/**
 * Resolve every reference at process start, or throw naming all of them.
 *
 * Presence is `!== undefined`: a variable set to the empty string is set. All
 * missing variables are reported at once, because a deployment that is short
 * three keys should learn that in one run rather than in three.
 */
export function readEnvironment(
  source: Record<string, string | undefined> = process.env,
): ReadonlyMap<string, string> {
  const resolved = new Map<string, string>();
  const missing: EnvironmentReference[] = [];
  for (const reference of environmentReferences) {
    const value = source[reference.name];
    if (value === undefined) {
      missing.push(reference);
    } else {
      resolved.set(reference.name, value);
    }
  }
  if (missing.length > 0) {
    throw new MissingEnvironmentError(missing);
  }
  return resolved;
}
