// This file was generated by agent-compose 0.1.0 from `main.yml` (target `staging`).
//
// It is a build artifact, not source: `agent-compose build` overwrites it,
// and `agent-compose build --check` fails when it has been edited. The spec
// is the single source of truth (PRD 5.12); to own this code instead, copy
// the whole directory out and stop regenerating it.
//
// The compiled graph (PRD 5.3, 5.4, grammar 7, 8, 9).
//
// One LangGraph node per flow node, driven by the descriptor beside it: how its
// input is built (grammar 8.0), the activity it runs (grammar 8), where its
// output goes (grammar 10.3), and its outgoing edges in declaration order
// (grammar 7.3). Every node answers a `Command`, so the branch it takes and the
// state it writes — including the counter a bounded edge spends (grammar 7.4) —
// land in one write. `./runtime.ts` is what the descriptors drive.

import { END, START, StateGraph } from "@langchain/langgraph";

import * as runtime from "./runtime.ts";
import * as stores from "./stores.ts";
import {
  agentFixerOutput,
  agentSummarizerOutput,
  agentTriageOutput,
  flowEnrichInputs,
  flowEnrichNodeFetchOutput,
  flowEnrichOutputs,
  flowTriageInputs,
  flowTriageNodeAnnounceFailedOutput,
  flowTriageNodeAnnounceOutput,
  flowTriageNodeApproveOutput,
  flowTriageNodeEscalateOutput,
  flowTriageNodeVerifyOutput,
  storeDocsToolSearchInput,
  toolDeadLetterInput,
  toolDeadLetterOutput,
  toolRepoGrepInput,
  toolRepoGrepOutput,
  toolReviewQueueInput,
  toolReviewQueueOutput,
} from "./schemas.ts";
import { State } from "./state.ts";
import type { GraphState } from "./state.ts";

// --- Shapes: the declared type an expression reads a value through ---
/**
 * Every declared state channel, so `state.count` is an `int` where the
 * channel says `type: integer` and a `double` where it says `type: number`.
 */
const stateShape: runtime.Shape = {
  properties: {
    "human_decision": "string",
    "matches": {
      "items": "string"
    },
    "patches": {
      "items": "string"
    },
    "report_normalized": "string",
    "summary": "string",
  },
};

/** `flow.enrich` — the `input` root inside it (grammar 7.5). */
const flowEnrichShape: runtime.Shape = {
  "properties": {
    "report": "string"
  }
};

/** `flow.enrich` node `fetch` — the `fetch.output` root its guards read. */
const flowEnrichNodeFetchShape: runtime.Shape = {
  "properties": {
    "report_normalized": "string"
  }
};

/** `flow.triage` — the `input` root inside it (grammar 7.5). */
const flowTriageShape: runtime.Shape = {
  "properties": {
    "pattern": "string",
    "report": "string"
  }
};

/** `flow.triage` node `enrich` — the `enrich.output` root its guards read. */
const flowTriageNodeEnrichShape: runtime.Shape = {
  "properties": {
    "report_normalized": "string"
  }
};

/** `flow.triage` node `scan` — the `scan.output` root its guards read. */
const flowTriageNodeScanShape: runtime.Shape = {
  "properties": {
    "matches": {
      "items": "string"
    }
  }
};

/**
 * `flow.triage` node `classify` — the `classify.output` root its guards read.
 */
const flowTriageNodeClassifyShape: runtime.Shape = {
  "properties": {
    "findings": {
      "items": {
        "properties": {
          "kind": "string"
        },
        "rest": "any"
      }
    }
  }
};

/**
 * `flow.triage` node `announce` — the `announce.output` root its guards read.
 */
const flowTriageNodeAnnounceShape: runtime.Shape = {
  "properties": {
    "status": "int"
  }
};

/**
 * `flow.triage` node `announce_failed` — the `announce_failed.output` root its guards read.
 */
const flowTriageNodeAnnounceFailedShape: runtime.Shape = {
  "properties": {
    "exit_code": "int",
    "stdout": "string"
  }
};

/** `flow.triage` node `verify` — the `verify.output` root its guards read. */
const flowTriageNodeVerifyShape: runtime.Shape = {
  "properties": {
    "exit_code": "int",
    "stdout": "string"
  }
};

/**
 * `flow.triage` node `summarize` — the `summarize.output` root its guards read.
 */
const flowTriageNodeSummarizeShape: runtime.Shape = {
  "properties": {
    "summary": "string"
  }
};

/**
 * `flow.triage` node `remember` — the `remember.output` root its guards read.
 */
const flowTriageNodeRememberShape: runtime.Shape = {
  "properties": {
    "key": "string"
  }
};

/** `flow.triage` node `approve` — the `approve.output` root its guards read. */
const flowTriageNodeApproveShape: runtime.Shape = {
  "properties": {
    "decision": "string",
    "note": "string"
  }
};

/**
 * `flow.triage` node `escalate` — the `escalate.output` root its guards read.
 */
const flowTriageNodeEscalateShape: runtime.Shape = {
  "properties": {
    "status": "int"
  }
};

/**
 * `provider.anthropic` — an `anthropic` connection (grammar 12.1). Every value is read when a node calls it, never at import: a build carries no credential and `./index.ts` is where their presence is checked (PRD 5.9).
 */
const providerAnthropic: runtime.ProviderBinding = {
  address: "provider.anthropic",
  kind: "anthropic",
  get apiKey(): string {
    return runtime.environmentValue("ANTHROPIC_API_KEY", "provider.anthropic.api_key");
  },
};

/**
 * `provider.local` — an `openai_compatible` connection (grammar 12.1). Every value is read when a node calls it, never at import: a build carries no credential and `./index.ts` is where their presence is checked (PRD 5.9).
 */
const providerLocal: runtime.ProviderBinding = {
  address: "provider.local",
  kind: "openai_compatible",
  get apiKey(): string {
    return runtime.environmentValue("LOCAL_LLM_KEY", "provider.local.api_key");
  },
  get baseUrl(): string {
    return runtime.environmentValue("LOCAL_LLM_URL", "provider.local.base_url");
  },
};

/** `model.fast` — `claude-haiku-4-5` on `provider.anthropic` (grammar 12.2). */
const modelFast: runtime.ModelBinding = {
  address: "model.fast",
  id: "claude-haiku-4-5",
  provider: providerAnthropic,
  settings: {
    "max_tokens": 2000,
    "temperature": 0.1,
  },
};

/** `model.offline` — `qwen3-coder-30b` on `provider.local` (grammar 12.2). */
const modelOffline: runtime.ModelBinding = {
  address: "model.offline",
  id: "qwen3-coder-30b",
  provider: providerLocal,
  settings: {
    "temperature": 0.2,
  },
};

/**
 * `model.smart` — `claude-sonnet-4-6` on `provider.anthropic` (grammar 12.2).
 */
const modelSmart: runtime.ModelBinding = {
  address: "model.smart",
  id: "claude-sonnet-4-6",
  provider: providerAnthropic,
  settings: {
    "max_tokens": 8000,
  },
};

/**
 * `store.docs` — a `vector` store with `scope: global`, on the `chroma` backend (the alias `docs_db`, defined by the `staging` target) (grammar 11.1, 11.3).
 */
const storeDocs: stores.StoreBinding = {
  address: "store.docs",
  name: "docs",
  kind: "vector",
  scope: "global",
  description: "Project documentation, chunked, for grounding triage decisions.",
  metadata: true,
  embed: {
    store: "store.docs",
    model: "text-embedding-3-small",
    provider: providerLocal,
    dimensions: 1536,
  },
  backend: {
    provider: "chroma",
    from: "the alias `docs_db`, defined by the `staging` target",
  },
};

/**
 * `store.triage_memory` — a `kv` store with `scope: session`, on the `redis` backend (the `kv` default of the `staging` target) (grammar 11.1, 11.3).
 */
const storeTriageMemory: stores.StoreBinding = {
  address: "store.triage_memory",
  name: "triage_memory",
  kind: "kv",
  scope: "session",
  description: "What this session has already triaged.",
  metadata: false,
  backend: {
    provider: "redis",
    from: "the `kv` default of the `staging` target",
  },
};

/**
 * `tool.dead_letter` — an HTTP request (grammar 6.1). Its arguments are parsed with its own declared `input:` before the implementation sees them, which is the checked signature grammar 8.4 asks for and the model's arguments are held to. The parse is `runtime.parseToolArguments`, so arguments the schema refuses are a `ToolCallRefused`: at a `tools:` attachment the agent's loop hands that back to the model (Decision D119), and at a `function:` node — where grammar 8.4 has already checked the binding field-by-field and no model chose anything — nothing catches it and the node fails, as it always has. The tool's **result** is parsed with `runtime.parseResult` on both surfaces: a tool answering off-contract is not a call anybody can rephrase.
 */
async function toolDeadLetter(args: unknown, context: runtime.RunContext): Promise<unknown> {
  const input = runtime.parseToolArguments(toolDeadLetterInput, args, "the arguments `tool.dead_letter` was called with");
  const roots = { input: runtime.bind(input, {
    "properties": {
      "kind": "string",
      "payload": "string"
    }
  }) };
  return runtime.parseResult(
    toolDeadLetterOutput,
    await runtime.runHttp({
      method: "POST",
      url: ["https://", { env: "QUEUE_HOST", site: "tool.dead_letter.http.url" }, "/v1/dead-letter"],
      headers: [
        { name: "authorization", value: ["Bearer ", { env: "QUEUE_TOKEN", site: "tool.dead_letter.http.headers.authorization" }] },
      ],
      expectStatus: "2xx",
      decoding: { envelope: [], decoded: ["accepted"], empty: false },
    }, {
      body: {
        "kind": runtime.toJson(runtime.evaluate("input.kind", roots)),
        "payload": runtime.toJson(runtime.evaluate("input.payload", roots)),
      },
    }, context),
    "the result of `tool.dead_letter`",
  );
}

/**
 * `tool.repo_grep` — a subprocess (grammar 6.1). Its arguments are parsed with its own declared `input:` before the implementation sees them, which is the checked signature grammar 8.4 asks for and the model's arguments are held to. The parse is `runtime.parseToolArguments`, so arguments the schema refuses are a `ToolCallRefused`: at a `tools:` attachment the agent's loop hands that back to the model (Decision D119), and at a `function:` node — where grammar 8.4 has already checked the binding field-by-field and no model chose anything — nothing catches it and the node fails, as it always has. The tool's **result** is parsed with `runtime.parseResult` on both surfaces: a tool answering off-contract is not a call anybody can rephrase.
 */
async function toolRepoGrep(args: unknown, context: runtime.RunContext): Promise<unknown> {
  const input = runtime.parseToolArguments(toolRepoGrepInput, args, "the arguments `tool.repo_grep` was called with");
  return runtime.parseResult(
    toolRepoGrepOutput,
    await runtime.runExec({
      command: ["repo-grep"],
      args: [
        ["--format"],
        ["json"],
      ],
      cwd: [{ env: "REPO_ROOT", site: "tool.repo_grep.exec.cwd" }],
      env: [
        { name: "RIPGREP_CONFIG_PATH", value: [{ env: "RG_CONFIG_PATH", site: "tool.repo_grep.exec.env.RIPGREP_CONFIG_PATH" }] },
      ],
      expectExit: [0],
      decoding: { envelope: [], decoded: ["matches"], empty: false },
    }, input, context),
    "the result of `tool.repo_grep`",
  );
}

/**
 * `tool.review_queue` — an HTTP request (grammar 6.1). Its arguments are parsed with its own declared `input:` before the implementation sees them, which is the checked signature grammar 8.4 asks for and the model's arguments are held to. The parse is `runtime.parseToolArguments`, so arguments the schema refuses are a `ToolCallRefused`: at a `tools:` attachment the agent's loop hands that back to the model (Decision D119), and at a `function:` node — where grammar 8.4 has already checked the binding field-by-field and no model chose anything — nothing catches it and the node fails, as it always has. The tool's **result** is parsed with `runtime.parseResult` on both surfaces: a tool answering off-contract is not a call anybody can rephrase.
 */
async function toolReviewQueue(args: unknown, context: runtime.RunContext): Promise<unknown> {
  const input = runtime.parseToolArguments(toolReviewQueueInput, args, "the arguments `tool.review_queue` was called with");
  const roots = { input: runtime.bind(input, {
    "properties": {
      "severity": "string",
      "summary": "string"
    }
  }) };
  return runtime.parseResult(
    toolReviewQueueOutput,
    await runtime.runHttp({
      method: "POST",
      url: ["https://", { env: "QUEUE_HOST", site: "tool.review_queue.http.url" }, "/v1/tickets"],
      headers: [
        { name: "authorization", value: ["Bearer ", { env: "QUEUE_TOKEN", site: "tool.review_queue.http.headers.authorization" }] },
      ],
      expectStatus: [201],
      decoding: { envelope: [], decoded: ["ticket_id", "queued"], empty: false },
    }, {
      body: {
        "summary": runtime.toJson(runtime.evaluate("input.summary", roots)),
        "severity": runtime.toJson(runtime.evaluate("input.severity", roots)),
      },
    }, context),
    "the result of `tool.review_queue`",
  );
}

/**
 * `agent.fixer` — one LLM call with structured output (PRD 5.2, grammar 5). The schema below is the **published** JSON Schema of grammar 3.8's table, which is the column the conformance corpus proves equal to the parse its answer then faces.
 */
const agentFixer: runtime.AgentBinding = {
  address: "agent.fixer",
  prompt: "You write minimal unified diffs. Fix exactly the described defect in the\nnamed file and change nothing else.\n",
  model: modelFast,
  output: {
    name: "fixer_output",
    description: "The structured output `agent.fixer` must produce.",
    schema: {
      "additionalProperties": false,
      "properties": {
        "explanation": {
          "description": "One sentence describing the change.",
          "type": "string"
        },
        "patch": {
          "description": "A unified diff.",
          "type": "string"
        }
      },
      "required": [
        "patch",
        "explanation"
      ],
      "type": "object"
    },
  },
  tools: [],
  maxToolIterations: 8,
};

/**
 * `agent.summarizer` — one LLM call with structured output (PRD 5.2, grammar 5). The schema below is the **published** JSON Schema of grammar 3.8's table, which is the column the conformance corpus proves equal to the parse its answer then faces.
 */
const agentSummarizer: runtime.AgentBinding = {
  address: "agent.summarizer",
  prompt: "Summarize the triage run in at most five sentences: what was fixed\nautomatically, what needs a human, and any risk you noticed.\n",
  model: modelFast,
  output: {
    name: "summarizer_output",
    description: "The structured output `agent.summarizer` must produce.",
    schema: {
      "additionalProperties": false,
      "properties": {
        "summary": {
          "description": "The run summary shown to the human reviewer.",
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "summary"
      ],
      "type": "object"
    },
  },
  tools: [],
  maxToolIterations: 8,
};

/**
 * `agent.triage` — one LLM call with structured output (PRD 5.2, grammar 5). The schema below is the **published** JSON Schema of grammar 3.8's table, which is the column the conformance corpus proves equal to the parse its answer then faces.
 */
const agentTriage: runtime.AgentBinding = {
  address: "agent.triage",
  prompt: "You triage incoming bug reports.\n\nEmit one finding per distinct defect. Tag a finding `auto_fixable` only when\nthe fix is mechanical and local to one file. Tag it `needs_human` when it\nrequires judgement, and `duplicate` when the report restates a finding you\nhave already emitted in this run.\n",
  model: modelSmart,
  output: {
    name: "triage_output",
    description: "The structured output `agent.triage` must produce.",
    schema: {
      "additionalProperties": false,
      "properties": {
        "findings": {
          "description": "Every distinct defect, tagged for routing.",
          "items": {
            "oneOf": [
              {
                "additionalProperties": false,
                "properties": {
                  "file": {
                    "type": "string"
                  },
                  "kind": {
                    "const": "auto_fixable"
                  },
                  "patch_hint": {
                    "type": "string"
                  }
                },
                "required": [
                  "kind",
                  "file",
                  "patch_hint"
                ],
                "type": "object"
              },
              {
                "additionalProperties": false,
                "properties": {
                  "kind": {
                    "const": "needs_human"
                  },
                  "severity": {
                    "enum": [
                      "low",
                      "high",
                      "critical"
                    ],
                    "type": "string"
                  },
                  "summary": {
                    "type": "string"
                  }
                },
                "required": [
                  "kind",
                  "summary",
                  "severity"
                ],
                "type": "object"
              },
              {
                "additionalProperties": false,
                "properties": {
                  "kind": {
                    "const": "duplicate"
                  },
                  "of": {
                    "type": "string"
                  }
                },
                "required": [
                  "kind",
                  "of"
                ],
                "type": "object"
              }
            ]
          },
          "maxItems": 50,
          "type": "array"
        }
      },
      "required": [
        "findings"
      ],
      "type": "object"
    },
  },
  tools: [
    {
      name: "docs_search",
      address: "store.docs",
      description: "Search by meaning in `store.docs`. Project documentation, chunked, for grounding triage decisions.",
      schema: {
        "additionalProperties": false,
        "properties": {
          "filter": {
            "additionalProperties": false,
            "default": {},
            "properties": {
              "source": {
                "type": "string"
              },
              "updated_at": {
                "format": "date-time",
                "type": "string"
              }
            },
            "required": [],
            "type": "object"
          },
          "query": {
            "type": "string"
          },
          "top_k": {
            "maximum": 100,
            "minimum": 1,
            "type": "integer"
          }
        },
        "required": [
          "query",
          "top_k"
        ],
        "type": "object"
      },
      invoke: async (args, context) =>
        stores.runStoreTool(
          storeDocs,
          "search",
          runtime.parseToolArguments(storeDocsToolSearchInput, args, "the arguments `docs_search` was called with") as Record<string, unknown>,
          context,
        ),
    },
  ],
  maxToolIterations: 8,
};

// --- flow.enrich ---

/** `flow.enrich` node `fetch` — an inline request (grammar 8.3). */
const flowEnrichNodeFetch: runtime.NodeDescriptor = {
  flow: "flow.enrich",
  node: "fetch",
  // Grammar 9.3, resolved: `retry` from the node, `timeout` from the node, `on_error` from `defaults:`.
  policy: {
    retry: {
      max: 2,
      backoffMs: 1000,
      multiplier: 3,
      maxBackoffMs: 20000,
      jitter: true,
    },
    timeoutMs: 15000,
    onError: "fail",
  },
  shapes: { input: flowEnrichShape, state: stateShape, output: flowEnrichNodeFetchShape },
  input: (roots) => ({
    body: {
      "report": runtime.toJson(runtime.evaluate("input.report", roots)),
    },
  }),
  run: async (input, context) => ({
    output: runtime.parseResult(
      flowEnrichNodeFetchOutput,
      await runtime.runHttp(
{
                  method: "POST",
                  url: ["https://", { env: "TRIAGE_HOST", site: "flow.enrich.node.fetch.http.url" }, "/v1/normalize"],
                  headers: [
                    { name: "authorization", value: ["Bearer ", { env: "TRIAGE_TOKEN", site: "flow.enrich.node.fetch.http.headers.authorization" }] },
                  ],
                  expectStatus: [200],
                  decoding: { envelope: [], decoded: ["report_normalized"], empty: false },
                },
        input as { query?: Record<string, unknown>; body?: unknown },
        context,
      ),
      "the result of `flow.enrich` node `fetch`",
    ),
  }),
  writes: [
    { field: "report_normalized", channel: "report_normalized", reduce: "set" },
  ],
  edges: [
    { to: END },
  ],
};

/** `flow.enrich` — its nodes, its `start` edges, and the compiled graph. */
function flowEnrich() {
  return new StateGraph(State)
    .addNode("fetch", (state: GraphState) => runtime.runNode(flowEnrichNodeFetch, state), {
      ends: [END],
    })
    .addEdge(START, "fetch")
    .compile();
}

/**
 * `flow.enrich`, compiled once. Building it at import is also what checks it: a state model LangGraph refuses, or an edge to a node that is not registered, fails here rather than at the first invocation.
 */
const flowEnrichGraph = flowEnrich();

/**
 * `flow.enrich` as a module: what a `flow:` node instantiates and a `map` dispatches to (grammar 7.5, 8.5).
 */
const flowEnrichBinding: runtime.SubflowBinding = {
  address: "flow.enrich",
  outputs: ["report_normalized"],
  recursionLimit: 26,
  stream: (initial, options) =>
    flowEnrichGraph.stream(initial, {
      ...options,
      streamMode: "values",
      outputKeys: flowEnrichGraph.outputChannels,
    }) as unknown as Promise<AsyncIterable<runtime.GraphStateLike>>,
};

// --- flow.triage ---

/** `flow.triage` node `enrich` — `flow.enrich` (grammar 8.5). */
const flowTriageNodeEnrich: runtime.NodeDescriptor = {
  flow: "flow.triage",
  node: "enrich",
  // Grammar 9.3, resolved: `retry` from `defaults:`, `timeout` from `defaults:`, `on_error` from `defaults:`.
  policy: {
    retry: {
      max: 1,
      backoffMs: 2000,
      multiplier: 2,
      jitter: true,
    },
    timeoutMs: 90000,
    onError: "fail",
  },
  shapes: { input: flowTriageShape, state: stateShape, output: flowTriageNodeEnrichShape },
  input: (roots) => ({
    "report": runtime.toJson(runtime.evaluate("input.report", roots)),
  }),
  run: async (input, context, view) =>
    runtime.runSubflow(flowEnrichBinding, {
      inputs: input as Record<string, unknown>,
      execution: view.run.execution,
      path: runtime.instancePath(view, "enrich"),
      signal: context.signal,
      policy: runtime.instancePolicy(view.run.policy, {
        timeoutMs: 30000,
        onError: "fail",
      }),
    }),
  writes: [
    { field: "report_normalized", channel: "report_normalized", reduce: "set" },
  ],
  edges: [
    { to: "scan" },
  ],
};

/** `flow.triage` node `scan` — `tool.repo_grep` (grammar 8.4). */
const flowTriageNodeScan: runtime.NodeDescriptor = {
  flow: "flow.triage",
  node: "scan",
  // Grammar 9.3, resolved: `retry` from `defaults:`, `timeout` from `defaults:`, `on_error` from `defaults:`.
  policy: {
    retry: {
      max: 1,
      backoffMs: 2000,
      multiplier: 2,
      jitter: true,
    },
    timeoutMs: 90000,
    onError: "fail",
  },
  shapes: { input: flowTriageShape, state: stateShape, output: flowTriageNodeScanShape },
  input: (roots, view) => ({
    "pattern": runtime.toJson(runtime.evaluate("input.pattern", roots)),
    "max_matches": runtime.toJson(runtime.evaluate("25", roots)),
  }),
  run: async (input, context) => ({ output: await toolRepoGrep(input, context) }),
  writes: [
    { field: "matches", channel: "matches", reduce: "set" },
  ],
  edges: [
    { to: "classify" },
  ],
};

/** `flow.triage` node `classify` — `agent.triage` (grammar 8.1). */
const flowTriageNodeClassify: runtime.NodeDescriptor = {
  flow: "flow.triage",
  node: "classify",
  // Grammar 9.3, resolved: `retry` from `defaults:`, `timeout` from `defaults:`, `on_error` from `defaults:`.
  policy: {
    retry: {
      max: 1,
      backoffMs: 2000,
      multiplier: 2,
      jitter: true,
    },
    timeoutMs: 90000,
    onError: "fail",
  },
  retains: true,
  shapes: { input: flowTriageShape, state: stateShape, output: flowTriageNodeClassifyShape },
  input: (roots, view) => ({
    "report": runtime.toJson(runtime.evaluate("state.report_normalized", roots)),
    "matches": runtime.toJson(runtime.evaluate("state.matches", roots)),
  }),
  run: async (input, context, view) => {
    const answer = await runtime.callAgent(
      agentTriage,
      input,
      runtime.historyTurns(view.state["messages"] as unknown[]),
      context,
      { path: runtime.instancePath(view, "classify"), policy: view.run.policy },
    );
    return {
      output: runtime.parseResult(agentTriageOutput, answer.output, "the answer of `agent.triage`"),
      history: answer.history,
      models: answer.models,
      toolDispatches: answer.toolDispatches,
    };
  },
  writes: [],
  edges: [
    { to: "dispatch" },
    { to: "announce" },
  ],
};

/**
 * `flow.triage` node `dispatch` — the fan-out it dispatches (grammar 8.6). `over` resolves against `classify.output.findings`, and `finding` is what an instance's own bindings call the item.
 */
const flowTriageNodeDispatchMap: runtime.MapDescriptor = {
  node: "dispatch",
  as: "finding",
  source: {
    path: "classify.output.findings",
    producer: "classify",
    shape: {
      "properties": {
        "findings": {
          "items": {
            "properties": {
              "kind": "string"
            },
            "rest": "any"
          }
        }
      }
    },
  },
  maxConcurrency: 8,
  onItemError: { retry: {
    max: 2,
    backoffMs: 2000,
    multiplier: 2,
    jitter: true,
  } },
  routeBy: "kind",
  routes: [
    {
      tag: "auto_fixable",
      target: "agent.fixer",
      maxConcurrency: 4,
      detach: false,
      itemShape: {
        "properties": {
          "file": "string",
          "kind": "string",
          "patch_hint": "string"
        }
      },
      input: (roots) => ({
        "file": runtime.toJson(runtime.evaluate("finding.file", roots)),
        "patch_hint": runtime.toJson(runtime.evaluate("finding.patch_hint", roots)),
      }),
      run: async (input, context, site) => {
        const answer = await runtime.callAgent(agentFixer, input, [], context, { path: site.path });
        return {
          output: runtime.parseResult(agentFixerOutput, answer.output, "the answer of `agent.fixer`"),
          models: answer.models,
          toolDispatches: answer.toolDispatches,
        };
      },
      writes: [
        { field: "patch", channel: "patches", reduce: "append" },
      ],
    },
    {
      tag: "needs_human",
      target: "tool.review_queue",
      maxConcurrency: 8,
      detach: false,
      itemShape: {
        "properties": {
          "kind": "string",
          "severity": "string",
          "summary": "string"
        }
      },
      input: (roots) => ({
        "summary": runtime.toJson(runtime.evaluate("finding.summary", roots)),
        "severity": runtime.toJson(runtime.evaluate("finding.severity", roots)),
      }),
      run: async (input, context) => ({ output: await toolReviewQueue(input, context) }),
      writes: [],
    },
  ],
  fallback: {
    tag: "$default",
    target: "tool.dead_letter",
    maxConcurrency: 8,
    detach: false,
    itemShape: {
      "properties": {
        "kind": "string",
        "of": "string"
      }
    },
    input: (roots) => ({
      "kind": runtime.toJson(runtime.evaluate("finding.kind", roots)),
      "payload": runtime.toJson(runtime.evaluate("finding.of", roots)),
    }),
    run: async (input, context) => ({ output: await toolDeadLetter(input, context) }),
    writes: [],
  },
};

/** `flow.triage` node `dispatch` — a fan-out (grammar 8.6). */
const flowTriageNodeDispatch: runtime.NodeDescriptor = {
  flow: "flow.triage",
  node: "dispatch",
  // Grammar 9.3, resolved: `retry` from `defaults:`, `timeout` from `defaults:`, `on_error` from the node.
  policy: {
    retry: {
      max: 1,
      backoffMs: 2000,
      multiplier: 2,
      jitter: true,
    },
    timeoutMs: 90000,
    onError: "skip",
  },
  shapes: { input: flowTriageShape, state: stateShape, output: "any" },
  input: (_roots, view) => runtime.mapPlan(flowTriageNodeDispatchMap, view),
  run: async (input, context) =>
    runtime.runMap(flowTriageNodeDispatchMap, input as runtime.MapPlan, context),
  writes: [],
  edges: [
    { to: "verify" },
  ],
};

/** `flow.triage` node `announce` — an inline request (grammar 8.3). */
const flowTriageNodeAnnounce: runtime.NodeDescriptor = {
  flow: "flow.triage",
  node: "announce",
  // Grammar 9.3, resolved: `retry` from `defaults:`, `timeout` from the node, `on_error` from the node.
  policy: {
    retry: {
      max: 1,
      backoffMs: 2000,
      multiplier: 2,
      jitter: true,
    },
    timeoutMs: 10000,
    onError: { fallback: "announce_failed" },
  },
  shapes: { input: flowTriageShape, state: stateShape, output: flowTriageNodeAnnounceShape },
  input: (roots) => ({
    body: {
      "report": runtime.toJson(runtime.evaluate("state.report_normalized", roots)),
    },
  }),
  run: async (input, context) => ({
    output: runtime.parseResult(
      flowTriageNodeAnnounceOutput,
      await runtime.runHttp(
{
                  method: "POST",
                  url: ["https://", { env: "QUEUE_HOST", site: "flow.triage.node.announce.http.url" }, "/v1/triage-started"],
                  headers: [
                    { name: "authorization", value: ["Bearer ", { env: "QUEUE_TOKEN", site: "flow.triage.node.announce.http.headers.authorization" }] },
                  ],
                  expectStatus: "2xx",
                  decoding: { envelope: ["status"], decoded: [], empty: false },
                },
        input as { query?: Record<string, unknown>; body?: unknown },
        context,
      ),
      "the result of `flow.triage` node `announce`",
    ),
  }),
  writes: [],
  edges: [
    { to: "verify" },
  ],
};

/** `flow.triage` node `announce_failed` — an inline subprocess (grammar 8.2). */
const flowTriageNodeAnnounceFailed: runtime.NodeDescriptor = {
  flow: "flow.triage",
  node: "announce_failed",
  // Grammar 9.3, resolved: `retry` from `defaults:`, `timeout` from `defaults:`, `on_error` from the node.
  policy: {
    retry: {
      max: 1,
      backoffMs: 2000,
      multiplier: 2,
      jitter: true,
    },
    timeoutMs: 90000,
    onError: "skip",
  },
  shapes: { input: flowTriageShape, state: stateShape, output: flowTriageNodeAnnounceFailedShape },
  input: () => ({}),
  run: async (input, context) => ({
    output: runtime.parseResult(
      flowTriageNodeAnnounceFailedOutput,
      await runtime.runExec({
        command: [{ env: "OPS_BIN", site: "flow.triage.node.announce_failed.exec.command" }, "/log-event"],
        args: [
          ["--kind=announce-failed"],
          ["--env=", { env: "DEPLOY_ENV", site: "flow.triage.node.announce_failed.exec.args[1]" }],
        ],
        env: [],
        expectExit: [0],
        decoding: { envelope: ["exit_code", "stdout"], decoded: [], empty: false },
      }, input, context),
      "the result of `flow.triage` node `announce_failed`",
    ),
  }),
  writes: [],
  edges: [
    { to: END },
  ],
};

/** `flow.triage` node `verify` — an inline subprocess (grammar 8.2). */
const flowTriageNodeVerify: runtime.NodeDescriptor = {
  flow: "flow.triage",
  node: "verify",
  // Grammar 9.3, resolved: `retry` from `defaults:`, `timeout` from the node, `on_error` from the node.
  policy: {
    retry: {
      max: 1,
      backoffMs: 2000,
      multiplier: 2,
      jitter: true,
    },
    timeoutMs: 300000,
    onError: "skip",
  },
  shapes: { input: flowTriageShape, state: stateShape, output: flowTriageNodeVerifyShape },
  input: (roots) => ({
    "patches": runtime.toJson(runtime.evaluate("state.patches", roots)),
  }),
  run: async (input, context) => ({
    output: runtime.parseResult(
      flowTriageNodeVerifyOutput,
      await runtime.runExec({
        command: ["run-checks"],
        args: [
          ["--fast"],
        ],
        cwd: [{ env: "REPO_ROOT", site: "flow.triage.node.verify.exec.cwd" }],
        env: [
          { name: "CI", value: ["true"] },
        ],
        expectExit: [0, 1],
        decoding: { envelope: ["exit_code", "stdout"], decoded: [], empty: false },
      }, input, context),
      "the result of `flow.triage` node `verify`",
    ),
  }),
  writes: [],
  edges: [
    { to: "summarize" },
  ],
};

/** `flow.triage` node `summarize` — `agent.summarizer` (grammar 8.1). */
const flowTriageNodeSummarize: runtime.NodeDescriptor = {
  flow: "flow.triage",
  node: "summarize",
  // Grammar 9.3, resolved: `retry` from `defaults:`, `timeout` from `defaults:`, `on_error` from `defaults:`.
  policy: {
    retry: {
      max: 1,
      backoffMs: 2000,
      multiplier: 2,
      jitter: true,
    },
    timeoutMs: 90000,
    onError: "fail",
  },
  shapes: { input: flowTriageShape, state: stateShape, output: flowTriageNodeSummarizeShape },
  input: (roots, view) => ({
    "report": runtime.toJson(runtime.evaluate("state.report_normalized", roots)),
    "patches": runtime.toJson(runtime.evaluate("state.patches", roots)),
  }),
  run: async (input, context, view) => {
    const answer = await runtime.callAgent(
      agentSummarizer,
      input,
      runtime.historyTurns(view.state["messages"] as unknown[]),
      context,
      { path: runtime.instancePath(view, "summarize"), policy: view.run.policy },
    );
    return {
      output: runtime.parseResult(agentSummarizerOutput, answer.output, "the answer of `agent.summarizer`"),
      history: answer.history,
      models: answer.models,
      toolDispatches: answer.toolDispatches,
    };
  },
  writes: [
    { field: "summary", channel: "summary", reduce: "set" },
  ],
  edges: [
    { to: "remember" },
  ],
};

/**
 * `flow.triage` node `remember` — a `set` on `store.triage_memory` (grammar 8.8).
 */
const flowTriageNodeRemember: runtime.NodeDescriptor = {
  flow: "flow.triage",
  node: "remember",
  // Grammar 9.3, resolved: `retry` from `defaults:`, `timeout` from `defaults:`, `on_error` from the node.
  policy: {
    retry: {
      max: 1,
      backoffMs: 2000,
      multiplier: 2,
      jitter: true,
    },
    timeoutMs: 90000,
    onError: "skip",
  },
  shapes: { input: flowTriageShape, state: stateShape, output: flowTriageNodeRememberShape },
  input: (roots) => ({
    key: String(runtime.toJson(runtime.evaluate("execution.session_key", roots))),
    value: {
      "last_report": runtime.toJson(runtime.evaluate("input.report", roots)),
      "patch_count": runtime.toJson(runtime.evaluate("size(state.patches)", roots)),
    },
  }),
  run: async (input, context, view) => ({
    output: await stores.runStoreOp(
      storeTriageMemory,
      "set",
      input as stores.StoreParams,
      context,
      { via: "node", idempotencyKey: [view.run.execution.id, ...runtime.instancePath(view, "remember")].join("/") },
    ),
  }),
  writes: [],
  edges: [
    { to: "approve" },
  ],
};

/**
 * `flow.triage` node `approve` — the pause it holds: what the human is shown, and what an answer has to fit (grammar 8.7, PRD 5.11).
 */
const flowTriageNodeApproveHuman: runtime.HumanDescriptor = {
  flow: "flow.triage",
  node: "approve",
  timeoutMs: 86400000,
  onTimeout: "escalate",
  schema: {
    "additionalProperties": false,
    "properties": {
      "decision": {
        "enum": [
          "approve",
          "reject"
        ],
        "type": "string"
      },
      "note": {
        "type": "string"
      }
    },
    "required": [
      "decision",
      "note"
    ],
    "type": "object"
  },
  parse: (payload) => runtime.parseResult(flowTriageNodeApproveOutput, payload, "the answer to `flow.triage` node `approve`"),
};

/** `flow.triage` node `approve` — a human-in-the-loop pause (grammar 8.7). */
const flowTriageNodeApprove: runtime.NodeDescriptor = {
  flow: "flow.triage",
  node: "approve",
  // Grammar 9.3, resolved: `retry` from exempt (Decision D102), `timeout` from exempt (Decision D102), `on_error` from `defaults:`.
  policy: {
    onError: "fail",
  },
  exempt: true,
  shapes: { input: flowTriageShape, state: stateShape, output: flowTriageNodeApproveShape },
  input: (roots, view) => ({
    "summary": runtime.toJson(runtime.evaluate("state.summary", roots)),
    "patch_count": runtime.toJson(runtime.evaluate("size(state.patches)", roots)),
  }),
  run: async (input, context, view) =>
    runtime.runHuman(flowTriageNodeApproveHuman, input, context, view),
  writes: [
    { field: "decision", channel: "human_decision", reduce: "set" },
  ],
  edges: [
    { to: END, when: "approve.output.decision == 'approve'", readsOutput: true },
    { to: "escalate", when: "approve.output.decision == 'reject'", readsOutput: true },
  ],
};

/** `flow.triage` node `escalate` — an inline request (grammar 8.3). */
const flowTriageNodeEscalate: runtime.NodeDescriptor = {
  flow: "flow.triage",
  node: "escalate",
  // Grammar 9.3, resolved: `retry` from the node, `timeout` from the node, `on_error` from `defaults:`.
  policy: {
    retry: {
      max: 3,
      backoffMs: 1000,
      multiplier: 2,
      jitter: true,
    },
    timeoutMs: 10000,
    onError: "fail",
  },
  shapes: { input: flowTriageShape, state: stateShape, output: flowTriageNodeEscalateShape },
  input: (roots) => ({
    body: {
      "summary": runtime.toJson(runtime.evaluate("state.summary", roots)),
    },
  }),
  run: async (input, context) => ({
    output: runtime.parseResult(
      flowTriageNodeEscalateOutput,
      await runtime.runHttp(
{
                  method: "POST",
                  url: ["https://", { env: "QUEUE_HOST", site: "flow.triage.node.escalate.http.url" }, "/v1/escalations"],
                  headers: [
                    { name: "authorization", value: ["Bearer ", { env: "QUEUE_TOKEN", site: "flow.triage.node.escalate.http.headers.authorization" }] },
                  ],
                  expectStatus: "2xx",
                  decoding: { envelope: ["status"], decoded: [], empty: false },
                },
        input as { query?: Record<string, unknown>; body?: unknown },
        context,
      ),
      "the result of `flow.triage` node `escalate`",
    ),
  }),
  writes: [],
  edges: [
    { to: END },
  ],
};

/** `flow.triage` — its nodes, its `start` edges, and the compiled graph. */
function flowTriage() {
  return new StateGraph(State)
    .addNode("enrich", (state: GraphState) => runtime.runNode(flowTriageNodeEnrich, state), {
      ends: ["scan"],
    })
    .addNode("scan", (state: GraphState) => runtime.runNode(flowTriageNodeScan, state), {
      ends: ["classify"],
    })
    .addNode("classify", (state: GraphState) => runtime.runNode(flowTriageNodeClassify, state), {
      ends: ["dispatch", "announce"],
    })
    .addNode("dispatch", (state: GraphState) => runtime.runNode(flowTriageNodeDispatch, state), {
      ends: ["verify"],
    })
    .addNode("announce", (state: GraphState) => runtime.runNode(flowTriageNodeAnnounce, state), {
      ends: ["verify", "announce_failed"],
    })
    .addNode("announce_failed", (state: GraphState) => runtime.runNode(flowTriageNodeAnnounceFailed, state), {
      ends: [END],
    })
    .addNode("verify", (state: GraphState) => runtime.runNode(flowTriageNodeVerify, state), {
      ends: ["summarize"],
    })
    .addNode("summarize", (state: GraphState) => runtime.runNode(flowTriageNodeSummarize, state), {
      ends: ["remember"],
    })
    .addNode("remember", (state: GraphState) => runtime.runNode(flowTriageNodeRemember, state), {
      ends: ["approve"],
    })
    .addNode("approve", (state: GraphState) => runtime.runNode(flowTriageNodeApprove, state), {
      ends: [END, "escalate"],
    })
    .addNode("escalate", (state: GraphState) => runtime.runNode(flowTriageNodeEscalate, state), {
      ends: [END],
    })
    .addEdge(START, "enrich")
    .compile();
}

/**
 * `flow.triage`, compiled once. Building it at import is also what checks it: a state model LangGraph refuses, or an edge to a node that is not registered, fails here rather than at the first invocation.
 */
const flowTriageGraph = flowTriage();

/**
 * `flow.triage` as a module: what a `flow:` node instantiates and a `map` dispatches to (grammar 7.5, 8.5).
 */
const flowTriageBinding: runtime.SubflowBinding = {
  address: "flow.triage",
  outputs: ["summary", "patches"],
  recursionLimit: 36,
  stream: (initial, options) =>
    flowTriageGraph.stream(initial, {
      ...options,
      streamMode: "values",
      outputKeys: flowTriageGraph.outputChannels,
    }) as unknown as Promise<AsyncIterable<runtime.GraphStateLike>>,
};

/**
 * How a declared flow input reads a command-line value (grammar 13.2).
 *
 * `json` is every structured shape — an object, an array, a tagged union — for
 * which the one honest reading of a shell argument is the document it spells.
 */
export type InputKind = "string" | "integer" | "number" | "boolean" | "json";

/** One compiled flow: what it takes, what it answers, and how to run it. */
export interface CompiledFlow {
  /** Its typed address (grammar 2.2). */
  readonly address: string;
  /** The fields its `inputs:` declares (grammar 7.5). */
  readonly inputs: readonly string[];
  /**
   * What each declared input *is*, so a `--input k=v` argument can be read as
   * the type the field declares rather than reaching Zod as text (grammar 13.2).
   */
  readonly inputKinds: Readonly<Record<string, InputKind>>;
  /** The fields its `outputs:` declares, each read from the channel of that name. */
  readonly outputs: readonly string[];
  /**
   * The `scope: session` stores this flow **reaches**, under the relation
   * grammar 7.7 fixes — its own nodes, its maps' dispatch targets, the flows it
   * instantiates, and the stores of every agent it reaches.
   *
   * A run of this flow needs a session identity exactly when this list is not
   * empty (grammar 11.3): a declared trigger supplies it through `session_key:`,
   * and the CLI through `--session`. Checked at run start rather than at
   * validate, for the reason env-ref presence is: the value does not exist until
   * the invocation does.
   */
  readonly sessionStores: readonly string[];
  /** The superstep ceiling a run of it takes by default. */
  readonly recursionLimit: number;
  /** Parse an invocation's inputs against the flow's own schema (grammar 13.2). */
  parse(inputs: unknown): Record<string, unknown>;
  /**
   * Invoke the compiled graph, answering with the state after each superstep.
   *
   * A stream rather than a plain invocation because of what a **failure** must
   * leave behind. LangGraph's `invoke` is this stream with the last value kept,
   * and an error thrown out of it discards the state it was keeping — the
   * routing trace of PRD 5.3 with it, since nothing here is checkpointed. Taking
   * the supersteps one at a time keeps every one that did complete, which is
   * what `runFlow` reports the failure with.
   */
  stream(
    initial: Record<string, unknown>,
    options: { recursionLimit: number },
  ): Promise<AsyncIterable<GraphState>>;
}

/**
 * Every flow this composition declares, by address.
 *
 * PRD 5.11 makes manual invocation universal — every flow is runnable whether or
 * not a `manual` trigger names it (Decision D64) — so the registry is every
 * flow rather than every triggered one.
 */
export const flows: Readonly<Record<string, CompiledFlow>> = {
  "flow.enrich": {
    address: "flow.enrich",
    inputs: ["report"],
    inputKinds: { "report": "string", },
    outputs: ["report_normalized"],
    sessionStores: [],
    recursionLimit: 26,
    parse: (inputs: unknown) =>
      runtime.parseResult(flowEnrichInputs, inputs, "the `inputs:` of `flow.enrich`") as Record<string, unknown>,
    stream: (initial, options) =>
      flowEnrichGraph.stream(initial, {
        ...options,
        streamMode: "values",
        outputKeys: flowEnrichGraph.outputChannels,
      }) as unknown as Promise<AsyncIterable<GraphState>>,
  },
  "flow.triage": {
    address: "flow.triage",
    inputs: ["report", "pattern"],
    inputKinds: { "report": "string", "pattern": "string", },
    outputs: ["summary", "patches"],
    sessionStores: ["store.triage_memory"],
    recursionLimit: 36,
    parse: (inputs: unknown) =>
      runtime.parseResult(flowTriageInputs, inputs, "the `inputs:` of `flow.triage`") as Record<string, unknown>,
    stream: (initial, options) =>
      flowTriageGraph.stream(initial, {
        ...options,
        streamMode: "values",
        outputKeys: flowTriageGraph.outputChannels,
      }) as unknown as Promise<AsyncIterable<GraphState>>,
  },
};

/** What one run produced. */
export interface FlowRun {
  /** The flow's `outputs:`, materialized from state at quiescence (grammar 7.6.3). */
  readonly outputs: Record<string, unknown>;
  /** Every routing decision the run made, in step order (PRD 5.3). */
  readonly trace: readonly runtime.TraceEntry[];
  /** The whole state at quiescence. */
  readonly state: GraphState;
}

/**
 * Why a flow that reaches a `scope: session` store refuses a run that arrived
 * with no session identity (grammar 11.3, 13.2).
 *
 * One sentence in one place, because it is raised from two and the two must not
 * drift: `src/cli.ts` raises it as a **usage** error, before a `run` starts
 * anything, because a missing `--session` is an argument the caller has to add —
 * the same class as an unknown `--input` name or an absent `${ENV}`, which
 * grammar 11.3 says outright by likening this check to env-ref presence (§4.3);
 * `runFlow` raises it for every other caller, where the key arrives per
 * invocation.
 *
 * Named by the store rather than by the flow, because the store is what the
 * author has to look at. And three ways a run arrives with none are named,
 * because two of them are advice a reader has already taken: a declared
 * `session_key:` that *evaluated* to the empty string — an absent header, a
 * payload member that was not sent — is an identity-less run whose trigger does
 * declare one, and a message offering only the two remedies would send that
 * reader to look at a line that is already there (PRD G3).
 */
export function sessionRefusal(address: string, stores: readonly string[]): string {
  return `\`${address}\` reaches ${stores.map((store) => `\`${store}\``).join(", ")}, which ${stores.length === 1 ? "is" : "are"} \`scope: session\`, so this run needs a session identity and arrived with none: pass \`--session <key>\` to \`agent-compose run\`, or declare \`session_key:\` on the trigger that starts it — and where one is declared, it answered the empty string for this invocation (grammar 11.3, 13.2)`;
}

/**
 * Run one flow to quiescence and materialize its outputs.
 *
 * This is the invocation surface `agent-compose run` and the generated `serve`
 * app are built on (PRD 5.11's `start`), and what an ejected project calls
 * directly. The inputs are parsed against the flow's own `inputs:` schema before
 * anything runs, which is where an invocation that the flow cannot accept is
 * refused by field name (grammar 13.2).
 *
 * A run that produces no answer raises `runtime.FlowFailure`, which carries the
 * trace it did make and the original error as its `cause` — see
 * `CompiledFlow.stream` for why the run is streamed to keep it. Both of the ways
 * that happens raise it: a run that never reached quiescence, and a run that
 * reached quiescence holding no value for one of its `outputs:` fields
 * (grammar 10.1, Decision D78). The second is the one whose trace is complete —
 * every step landed — so dropping it there would lose the whole routing record
 * of a run that made one.
 *
 * A third way is a `human` node (grammar 8.7): a run that reaches one and was
 * started with **no answer surface** stops there, and the `FlowFailure` carries
 * a `runtime.HumanInterrupt` on its `cause` chain — `runtime.interruptOf` is how
 * a caller tells that outcome from a failure. `resumable: true` is what says an
 * answer surface is attached, and there are two callers that pass it, one per
 * surface (PRD §9.21): `src/serve.ts`, whose `POST /executions/:id/resume`
 * delivers the answer, and `src/cli.ts`, when the `run` it is serving may ask
 * at the terminal it was launched from.
 */
export async function runFlow(
  address: string,
  inputs: unknown = {},
  options: {
    readonly executionId?: string;
    readonly sessionKey?: string;
    readonly recursionLimit?: number;
    /**
     * Whether something is standing by to answer a `human` pause this run
     * reaches (grammar 8.7, PRD 5.11).
     *
     * `false` — the default, and what an `agent-compose run` with nobody to ask
     * leaves it at — makes a pause the end of the run rather than a wait
     * nothing can settle. `src/cli.ts` passes `true` where the run may ask at
     * its own standard input, and `src/serve.ts` passes it for the resume
     * route.
     */
    readonly resumable?: boolean;
  } = {},
): Promise<FlowRun> {
  const flow = flows[address];
  if (flow === undefined) {
    throw new Error(
      `\`${address}\` is not a flow of this composition: ${Object.keys(flows).join(", ")}`,
    );
  }
  const parsed = flow.parse(inputs);
  const ceiling = options.recursionLimit ?? flow.recursionLimit;
  const sessionKey = options.sessionKey ?? "";
  // Grammar 11.3, checked where the value first exists: a flow that reaches a
  // `scope: session` store keys off the identity its trigger supplies, and a run
  // started without one would silently address a partition named by the empty
  // string. `src/cli.ts` decides the same thing one step earlier for a `run`,
  // where the identity is a command-line argument; this is the guard for every
  // caller it cannot stand in for — a `serve` request, an ejected invocation —
  // where the key arrives per invocation and its absence really is a failure of
  // that run rather than of the command.
  if (sessionKey === "" && flow.sessionStores.length > 0) {
    throw new Error(sessionRefusal(address, flow.sessionStores));
  }
  const executionId = options.executionId ?? `exec_${globalThis.crypto.randomUUID()}`;
  // Opened before the graph is streamed, so a status route asked the instant
  // after `start` answered already has somewhere to read this run's pauses from
  // (grammar 8.7, PRD 5.11). Every instance nested inside the run registers
  // against the same execution id and is told apart by its instance path.
  runtime.openHumanWaits(executionId, options.resumable === true);
  // `runtime.quiesce` keeps the last state each superstep produced, which is
  // what makes a failure's trace survive; the one failure it restates on the way
  // out is LangGraph stopping the run at the ceiling.
  const { state, error } = await runtime
    .quiesce(
      flow,
      {
        $run: {
          ...runtime.emptyRun(),
          input: parsed,
          execution: { id: executionId, session_key: sessionKey },
        },
      },
      ceiling,
    )
    // `scope: execution` means what it says: whatever this run's own stores held
    // is released when the run ends, however it ended (PRD 5.8, grammar 11.1).
    // A `serve` process runs many executions, so a store that stayed open would
    // be both a leak and a lifetime the composition did not declare. A pause the
    // run was holding goes the same way and for the same reason: a wait that
    // outlived its run would be one a resume could still be delivered to, with
    // no graph left to receive it (grammar 8.7).
    .finally(() => {
      stores.releaseExecution(executionId);
      runtime.releaseHumanWaits(executionId);
    });
  if (error !== undefined) {
    throw new runtime.FlowFailure(
      address,
      "did not run to quiescence",
      runtime.failedTrace(state, error),
      error,
    );
  }
  if (state === undefined) {
    // Unreachable: `streamMode: "values"` emits the state the run started from
    // before any node has run. A run with no state at all is still not one this
    // function can answer for, and saying so beats reading `undefined` as empty.
    throw new Error(`\`${address}\` produced no state`);
  }
  const quiesced = state;

  const outputs: Record<string, unknown> = {};
  try {
    for (const field of flow.outputs) {
      outputs[field] = runtime.channelValue(
        quiesced as unknown as Record<string, unknown>,
        field,
        `\`${address}\`'s output field \`${field}\``,
      );
    }
  } catch (error) {
    // Inside the same record as every other way a run fails to answer: the run
    // got all the way here, so `$run.trace` holds every step it took, and that
    // is the routing record a reader wants most when the flow cannot say what it
    // produced (PRD 5.3).
    throw new runtime.FlowFailure(
      address,
      "reached quiescence without an output",
      quiesced.$run.trace,
      error,
    );
  }
  return { outputs, trace: quiesced.$run.trace, state: quiesced };
}

/**
 * A new builder over this composition's state model.
 *
 * Every flow's topology is added to one of these. Constructing it is also what
 * proves the state model is a shape LangGraph accepts — a channel spec it
 * refuses fails here rather than at the first invocation.
 */
export function createBuilder() {
  return new StateGraph(State);
}
